### ISSUE TITLE
[Feature request] Subclass / interface polymorphism support

### ISSUE THREAD

**Issue by atoktoto** [Kodein-Framework/Kodein-DI#104]
I was surprised to find out that Kodein does seems to ignore object hierarchy in general when matching/binding classes. I provided some examples of expected behaviour using Kodein API. 

Simple case

```
interface SomeInterface{}
class A : SomeInterface

fun main(args: Array<String>) {
    val kodein = Kodein {
       bind<A>() with singleton { A() }
    }

   kodein.instance<SomeInterface>();  // Error: No provider found
}
```

Advanced case, when looking for multiple objects with the same interface:

```
interface SharedInterface {}

class A : SharedInterface
class B : SharedInterface
class C : SharedInterface
class D

fun main(args: Array<String>) {

    val kodein = Kodein {
        bind() from setBinding<SharedInterface>()

        bind<A>().inSet() with singleton { A() }
        bind<B>().inSet() with singleton { B() }
        bind<C>().inSet() with singleton { C() }
        bind<D>().inSet() with singleton { D() }
    }

    val shared = kodein.instance<Set<SharedInterface>>()
}
```

By sifting through the bindings one can **almost** get to the same result:

```
val singletonBindings = kodein.container.bindings.filterValues { it is SingletonBinding<*> }
val singletonInstances = singletonBindings.map { kodein.Instance(it.value.createdType) }
val instanceList = singletonInstances.filterIsInstance<SharedInterface>()
```

Almost because it causes errors when we bind using more general interface then provided (like in the first example) because `kodein.Instance(it.value.createdType)` was never bound as it's `createdType`.

**Comment by SalomonBrys** [comment]
Version 5.0 does not ignore this anymore. In fact, it is the most important change that was made to its core.
Your first example works in 5.0.
Your second example is not, and will not, be supported (You need to define the exact set binding type).
Version 5.0 beta 2 includes the `allInstances` API that may be useful to what you are tring to achieve.

**Comment by SalomonBrys** [comment]
Kodein 5.0 beta2 has been released.

I will close this issue when Kodein 5.0 is released.

**Comment by atoktoto** [comment]
Thank you! I'm impressed :)

**Comment by SalomonBrys** [comment]
Kodein 5.0 stable has been released :)

**Comment by eygraber** [comment]
@SalomonBrys is there a reason this isn't supported anymore?

One of my use cases is where I have a "manager" class which is a monolithic implementation of a bunch of interfaces. For example:

```
interface A
interface B
interface C
interface Manager : A, B, C

class ManagerImpl { ... }
```
Most of the code that uses this only needs to interface with `A`, `B`, or `C`, but there is some specialized code that deals with all of them, and so it uses `Manager`.

If I have bindings that looks like:

```
bind<Manager>() with provider { Manager.getImpl() }
bind<A>() with provider { Manager.getImpl() }
```

Then Kodein crashes when I try to retrieve `A` saying that 2 bindings were found that match `bind<A>`.

```
val a: A = instance()
```

**Comment by eygraber** [comment]
Is this what `subtypes` is for?
