### ISSUE TITLE
AScopedBinding Construtor is Internal

### ISSUE THREAD

**Issue by exallium** [Kodein-Framework/Kodein-DI#105]
I'm curious why this is? Would there be more sense in making it simply protected so that people can write their own bindings?  For example, I'd like to write a binding that automatically adds a `Disposable` dependency to a `DisposableContainer` that is provided by scope

```
abstract class AScopedBinding<A, out C, T : Any> internal constructor(
        private val _creator: NoArgBindingKodein.(C) -> T
)
```

**Comment by SalomonBrys** [comment]
Scoping has radically changed in [Kodein 5.0 beta](https://salomonbrys.github.io/Kodein/?5.0).
I will close this issue once the stable 5.0 will be released.

**Comment by SalomonBrys** [comment]
Kodein 5.0 stable has been released :)
