### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by gustavkarlsson** [Kodein-Framework/Kodein-DI#118]
The word _dice_ is plural of _die_

One die
Many dice

```kotlin
val dice = arrayOf(Die(1), Die(3), Die(5))
```

**Comment by tonilopezmr** [comment]
> Have a look at the Android demo project! (LINK BROKEN)
The Android demo project link is borken here http://kodein.org/Kodein-DI/?5.0/android

**Comment by SalomonBrys** [comment]
This is corrected.
Thanks to both of you for the report ;)
