### ISSUE TITLE
Failed to resolve: org.kodein.di:kodein-di-generic-jvm:5.0.0

### ISSUE THREAD

**Issue by pandasys** [Kodein-Framework/Kodein-DI#121]
Same for: Failed to resolve: org.kodein.di:kodein-di-framework-android:5.0.0

implementation 'org.kodein.di:kodein-di-erased-jvm:5.0.0' works

I copied/pasted the lines and don't see an obvious typo.

**Comment by apatrida** [comment]
Me too, the dependency is not there.
Your deploy of the release did not upload this @SalomonBrys 

https://jcenter.bintray.com/org/kodein/di/

**Comment by SalomonBrys** [comment]
I have.
And I checked...
No idea what's going on, but at the moment, I can't access https://bintray.com/kodein-framework/Kodein-DI
Looks like bintray is having some issues (https://bintray.statuspage.io).
I'll check what's going on as soon as possible.

**Comment by celtric** [comment]
Same problem here. As a note, on Thursday I had the same issue with the beta. The only way I could use it through Gradle was using JitPack.

**Comment by apatrida** [comment]
that works for now.

**Comment by SalomonBrys** [comment]
So,
out of 12 packages, 7 made it to jcenter, 5 didn't.
I have messages from Bintray approving including all 12 packages into jcenter.
I suppose their recent issues prevented those 5 packages to be included.
I have messaged Bintray through their internal messaging system, wainting for their answer.

**Comment by SalomonBrys** [comment]
Bintray has resolved the issue :D

**Comment by mensly** [comment]
I'm having this same issue with version 5.2.0. Temporary workaround worked, however.

**Comment by diegolucasb** [comment]
Same issue with 5.2.0. Temporary workaround worked!
