### ISSUE TITLE
Missing 'getValue(App, KProperty<*>)' method on delegate type 'LazyKodein'

### ISSUE THREAD

**Issue by HirogaKatageri** [Kodein-Framework/Kodein-DI#122]
When implementing KodeinAware in Application Class. Before and after binding anything at all. This error appears.

![image](https://user-images.githubusercontent.com/8166484/38412746-9cd46f08-39bc-11e8-8711-7d7129d9a522.png)

**Comment by HirogaKatageri** [comment]
I replaced 'by' with = based on the demo app on the project, error doesn't occur anymore.
Documentation is suggesting to use by instead of '='

**Comment by AleksanderMielczarek** [comment]
I have same issue. Kodein 5.0.

**Comment by SalomonBrys** [comment]
Use `=`, not `by`.
Kodein.Lazy is not a property delegate, it is a Kodein implementation that will actually create the binding lambda upon the first retrieval.

**Comment by ma-za-kpe** [comment]
Im having the same issue
Type 'KodeinPropertyDelegateProvider<Context>' has no method 'getValue(TodayFragment, KProperty<*>)' and thus it cannot serve as a delegate

The application class is being called in the manifest and showing that it was never used.

class WeatherForecast: Application(), KodeinAware {

    //Using Kodein.lazy allows you to access the Context at binding time.
    override val kodein = Kodein.lazy {
        import(androidXModule(this@WeatherForecast))
//        import(androidModule(this@WeatherForecast))

        bind() from singleton { ForecastDatabase(instance()) }
        bind() from singleton { instance<ForecastDatabase>().currentWeatherDao() }
        bind<ConnectivityInterceptor>() with singleton { ConnectivityInterceptorImpl(instance()) }
        bind() from singleton { ApixuApiWeatherService(instance()) }
        bind<WeatherNetworkDataSource>() with singleton { WeatherNetworkDataSourceImpl(instance()) }
        bind<ForeCastRepository>() with singleton { ForeCastRepositoryImpl(instance(), instance()) }
        bind() from provider { TodayViewModelFactory(instance()) }

//        bind<ViewModelProvider.Factory>() with singleton { TodayViewModelFactory(instance()) }

    }
}
