### ISSUE TITLE
Error for factory with multiple args

### ISSUE THREAD

**Issue by kalayda** [Kodein-Framework/Kodein-DI#130]
I use kodein-di-generic-jvm 5.0.0

For:

```
class UsersManagerImpl(userGenerator: (name: String, age: Int) -> User) : UsersManager {
 ...
}

...

bind<User>() with factory { name: String, age: Int -> UserImpl(name, age) }
bind<UsersManager>() with singleton { UsersManagerImpl(factory()) }
```

I got compiler error:

> Type inference failed. Expected type mismatch: inferred type is (???) -> ??? but (String, Int) -> User was expected

for `bind<UsersManager>` definition line.

Docs say, that I can use up to 5 args for factory, but `factory` implementation in GDKodein take only one parameter.

What I'm missing?

**Comment by SalomonBrys** [comment]
There is a limitation of reified generics that makes it very hard to solve:

```kotlin
inline fun <reified A1, reified A2, reified A3> multi3Generic() = generic<Multi3<A1, A2, A3>>()

fun main(args: Array<String>) {

    println(generic<Multi3<String, String, Int>>().simpleDispString())
    // Multi3<String, String, Int>
    
    println(multi3Generic<String, String, Int>().simpleDispString())
    // Multi3<A1, A2, A3>
}
```

Right now, I suggest to use ONE argument as a `data class`.
I know this is sub-optimal, and looking if there's anything I can do to propose an easier way, but there's no guarantee I'll find one...

**Comment by SalomonBrys** [comment]
Kodein 5.0.1 introduces `factory2()`, `factory3()`, `factory4()` and `factory5()` that solves this issue.

```kotlin
bind<UsersManager>() with singleton { UsersManagerImpl(factory2()) }
```
