### ISSUE TITLE
Update Kodein 5 documentation to reflect new singleton reference DSL

### ISSUE THREAD

**Issue by jdorleans** [Kodein-Framework/Kodein-DI#131]
I'm migrating from Kodein 4 to 5 and am reading the new documentation. It seems the old method `refSingleton` was replaced with `singleton(refMaker)` in version 5, however the documentation still pointing to the old one: http://kodein.org/Kodein-DI/?5.0/core#_jvm_soft_weak

**Comment by SalomonBrys** [comment]
This has been corrected by #128
