### ISSUE TITLE
NullPointerException when using "by" in init

### ISSUE THREAD

**Issue by Cililing** [Kodein-Framework/Kodein-DI#133]
Hey. I have a fragment. My fragment implements "KodeinAware". Actually, there is no big differences between example project: https://github.com/Kodein-Framework/Kodein-DI/blob/5.0/demo/demo-android/src/main/java/kodein/di/demo/MainFragment.kt and my project

When I try:
`class KodeinFragment : Fragment(), KodeinAware {
     override val kodein: Kodein by closestKodein()
    val myInjectedInstance by kodein.instance<System>()
}`

i get an error - NullPointerException (because my kodein is null...). If i get dependencies after onCreate everthing is fine (I mean there is no error)

What am I doing wrong? My activity also is KodeinAware.

**Comment by eygraber** [comment]
@SalomonBrys I got bit on the butt badly by this :smile: 

It probably should be highlighted in the docs.
