### ISSUE TITLE
Please provide an example for allInstances usage

### ISSUE THREAD

**Issue by andrasferenczi** [Kodein-Framework/Kodein-DI#134]
First off, thank you for the great library.

I am going through a couple examples and I cannot seem to get `allInstances` to work.

Why does `Kodein` always give an empty list to the `allInstances()` call?

Please look at this example:
    
```Kotlin
package testing

import org.kodein.di.Kodein
import org.kodein.di.erased.*
import java.util.*

interface X

class Y : X

class Z : X

fun main(args: Array<String>) {

    // Also tried with Kodein { // Without .direct
    val kodein = Kodein.direct {

        bind<X>(tag = "one") with singleton { Y() }
        bind<X>(tag = "two") with provider { Z() }
        bind<X>(tag = "three") with factory { _: Int -> object : X {} }

        bind<List<X>>(tag = "maybe") with provider { listOf(Y()) }

    }

    val instances: List<X> = kodein.allInstances<X>()

    println(Arrays.toString(instances.toTypedArray()))
}
```
I know binding `List<X>` will probably be not found due to type erasure, it is just a test.

This prints out:

    []

I expected this to return `Y` and `Z` at least, since no factory arguments are provided. 

Sorry for asking this obvious question, the [example in the wiki](http://kodein.org/Kodein-DI/?5.0/core#_all_matches_2) did not provide a full example.

Thank you.

**Comment by andrasferenczi** [comment]
I just realized calling `allInstances()` is the same as `allInstances(tag=null)` so it returns only the empty tags. Is there a way to return all tags for a specific binding?

**Comment by SalomonBrys** [comment]
No there's not.
However, you can explore all bindings and their information by accessing `kodein.container.bindings`.

http://kodein.org/Kodein-DI/?5.1/core#_hack_the_container

**Comment by pusolito** [comment]
Is allInstances available for kodein.js?

**Comment by YuryMikhailuts** [comment]
> Доступны ли allInstances для kodein.js?

I join this question. It is completely unclear what is happening with `allInstances` in the `multiplatform`. What is in the picture is all that is in the official documentation for `allInstances`.

1. It is not specified on which platforms it is supported.
2. It is not explained why not on others and whether it will be.
3. There are no `allInstances` replacement proposals for the `multiplatform`.

![image](https://github.com/kosi-libs/Kodein/assets/48589388/0ba0fea7-2793-428b-814f-9b1c976a57f3)
