### ISSUE TITLE
Does Kodein have support for something like Dagger2's @Reusable annotation?

### ISSUE THREAD

**Issue by mateherber** [Kodein-Framework/Kodein-DI#137]
On Android it really makes sense to optimize by making several stateless objects singletons even when we don't really need them to be "true" singletons we just don't want to recreate them over and over.

Dagger has a mechanism for that using [@Reusable](https://google.github.io/dagger/api/2.14/dagger/Reusable.html) annotation.

Here's a great blogpost about this too: [Single vs Double check](https://proandroiddev.com/dagger-2-check-singlecheck-doublecheck-scopes-4ee48fc31736)

I couldn't find something similar but I may have missed something. If there's not would you consider to add support?

**Comment by SalomonBrys** [comment]
Well, I find this `@Reusable` annotation very badly named!

If I understand Dagger's [SingleCheck code](https://github.com/google/dagger/blob/master/java/dagger/internal/SingleCheck.java), it's basically a singleton that is not atomically checked, so it *may* be constructed multiple times in the very rare case of multiple DI request to this type at the exact same time.

What I don't understand is why this is desirable. Especially in Android where allocation is heavy, and where it's probably cheaper to make a double check.
The synchronized part of the double check happens only on allocation and on that rare case of multiple concurent first access.

I need more use case before adding such a corner case to Kodein, which is already a very complex lib!

**Comment by mateherber** [comment]
Indeed allocation is heavy as well but the case which leads to multiple allocation can be considered an edge case itself. In our complex application (which has a deep dependency tree with occasionally several tens maybe hundreds of singletons being initialized on app start) we had significant improvement on App launch time by moving to single checks and keep double where it was not absolutely necessary to be thread safe. It is really rare that the singletons are accessed parallel first time so multiple allocation is pretty rare too.

**Comment by SalomonBrys** [comment]
Version 5.3.0 of Kodein will support `singleton(sync = false)` and `multiton(sync = false)`.
Using `sync = false` will disable the use of `synchronized`, which is indeed a significant startup performance boost.

I'll close this issue once version 5.3.0 is released ;)

**Comment by SalomonBrys** [comment]
Kodein DI 5.3.0 has been released :)

http://kodein.org/Kodein-DI/?5.3/core#_non_synced_singleton
