### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/main.kotlin_module'

### ISSUE THREAD

**Issue by hrach** [Kodein-Framework/Kodein-DI#138]
Hi, after upgrading to Kodein 5 I encounter 
`More than one file was found with OS independent path 'META-INF/main.kotlin_module'`
error.
It seems that the file is both packages:

![image](https://user-images.githubusercontent.com/284263/42023104-5a01c254-7abf-11e8-8058-93a00969174c.png)

I can add it to ignore, but it also seems it propagates the error through my library to the end-developer app and that's not good.

**Comment by Rasalexman** [comment]
so what the problem to exclude?
packagingOptions {
        exclude 'META-INF/main.kotlin_module'
    }

**Comment by SalomonBrys** [comment]
Looks like

```
packagingOptions {
exclude 'META-INF/main.kotlin_module'
}
```

is the right answer.

I'll add that to the documentation

**Comment by hrach** [comment]
@SalomonBrys I know this but I do not think this is a correct solution. 

a) It's quite unnecessary fixing some packaging bug on consumer's (=developer's) end
b) It sadly propagates, so if my library uses internally Kodein, it propagates the error and also I have to document this "fix" for users of my library (an sdk).

Please, I think it is possible to fix it in Kodein directly.
I've read that this module should be named as the final artifact, e.g. group name and the artifact id.

Also, Kotlin's docs provides some info & guide: https://kotlinlang.org/docs/reference/using-gradle.html#module-names

**Comment by SalomonBrys** [comment]
I didn't know this option existed ^^.
This will be done in the next version of Kodein :)

**Comment by hrach** [comment]
@SalomonBrys Hi, would you mind take a look at PR? :)

**Comment by SalomonBrys** [comment]
@hrach I don't think it is needed.
When I clean and regenrate, those file do not exist.

I think they come from some test main function that I made, and that I forgot to clean.
I'll investigate more.

**Comment by hrach** [comment]
@SalomonBrys Thanks a lot :)

**Comment by SalomonBrys** [comment]
Kodein DI 5.3.0 has been released :)
