### ISSUE TITLE
Failed to resolve: org.kodein.di:kodein-di-framework-android-core:5.2.0

### ISSUE THREAD

**Issue by ofdrykkja** [Kodein-Framework/Kodein-DI#140]
same problem with another versions of kodein-di-framework-android-core. org.kodein.di:kodein-di-generic-jvm:5.2.0 resolved well

**Comment by mateherber** [comment]
As a quick fix you can add to your repositories:
`maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }`

**Comment by 089apps** [comment]
https://dl.bintray.com/kodein-framework/Kodein-DI/org/kodein/di/kodein-di-framework-android/
contains max 5.1.1, but 5.2.0 is missing

**Comment by ofdrykkja** [comment]
@089apps that's doesn't matter because 5.1.1 also can't be resolved

**Comment by ofdrykkja** [comment]
@mateherber your fix didn't work for me

**Comment by mateherber** [comment]
![image](https://user-images.githubusercontent.com/13942888/42622694-4befe620-85c1-11e8-8479-5d12e50d6d6b.png)

@089apps you're using the wrong package

it should be kodein-di-framework-android-core

@ofdrykkja 

It's there, you sure you added to the right place?: https://dl.bintray.com/kodein-framework/Kodein-DI/org/kodein/di/kodein-di-framework-android-core/

**Comment by ofdrykkja** [comment]
i had tried to add `maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }` into the `buildscript { repositories {` and into` allprojects { repositories` of project build.gradle

**Comment by mateherber** [comment]
@ofdrykkja For me the allprojects one worked :( :
![image](https://user-images.githubusercontent.com/13942888/42623448-324df8b8-85c3-11e8-88ed-73864c0a4633.png)

![image](https://user-images.githubusercontent.com/13942888/42623513-5678d58c-85c3-11e8-9050-2a95712b6e36.png)

**Comment by SalomonBrys** [comment]
This component *do not exist* in Kodein 5.2.0 and has been replaced by either:
- `org.kodein.di:kodein-di-framework-android-core:5.2.0` (for only core Android)
- `org.kodein.di:kodein-di-framework-android-support:5.2.0` (For core Android *and* Support library)
- `org.kodein.di:kodein-di-framework-android-x:5.2.0` (For core Android *and* AndroidX library)

**Comment by nologinatgit** [comment]
I have the following lines in my _build.gradle_ files:

Project: 
```
allprojects {
    repositories {
        google()
        jcenter()
        maven {url "https://jitpack.io"}
    }
}
```

Module:

```
implementation 'org.kodein.di:kodein-di-generic-jvm:5.2.0'
implementation 'org.kodein.di:kodein-di-framework-android-support:5.2.0'

```
All I get is this: 

Failed to resolve: org.kodein.di:kodein-di-framework-android-core:5.2.0

So should I add the **_exact_** download link to use the library? Why isn't it available in the major repositories?

**Comment by CoolMind** [comment]
@nologinatgit, it writes that `org.kodein.di:kodein-di-framework-android-support:5.2.0` is not resolved, (also 5.1.1). I added `maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }` and it synced.

**Comment by mradzinski** [comment]
Same issue, `org.kodein.di:kodein-di-framework-android-core:5.2.0` doesn't resolve properly. It only does after adding `maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }` to the repositories of the project. Not that it's a big deal, but pretty sure people will start opening issues 🤷‍♂️

**Comment by gkpatel461** [comment]
> ![image](https://user-images.githubusercontent.com/13942888/42622694-4befe620-85c1-11e8-8479-5d12e50d6d6b.png)
> 
> @089apps you're using the wrong package
> 
> it should be kodein-di-framework-android-core
> 
> @ofdrykkja
> 
> It's there, you sure you added to the right place?: https://dl.bintray.com/kodein-framework/Kodein-DI/org/kodein/di/kodein-di-framework-android-core/

This is work for me
for support androidx 
    implementation 'org.kodein.di:kodein-di-generic-jvm:6.5.0'
    implementation 'org.kodein.di:kodein-di-framework-android-x:5.2.0'

and without Androidx
    implementation 'org.kodein.di:kodein-di-generic-jvm:6.5.0'
    implementation 'org.kodein.di:kodein-di-framework-android:5.1.1'
