### ISSUE TITLE
Invoke kodein.direct.instance() dynamically?

### ISSUE THREAD

**Issue by chaschev** [Kodein-Framework/Kodein-DI#145]
Is there a way to retrieve my interface implementation by providing it's class at runtime?

`KO.direct.instance<MyClass>() vs KO.direct.instance(MyClass::class)`

Thanks~

**Comment by SalomonBrys** [comment]
Yes, you need to use capaitalized methods:

```
kodein.direct.Instance(MyClass::class.java, null)
```

**Comment by chaschev** [comment]
Note: for dynamic purposes, one should also wrap it with `TT`: `KO.direct.Instance(TT(myClass))`
