### ISSUE TITLE
How to use context and scopes?

### ISSUE THREAD

**Issue by jcornaz** [Kodein-Framework/Kodein-DI#146]
Hello, 

After reading the [documentation](http://kodein.org/Kodein-DI/?5.2/core#_creating_from_environment) I now that:
> It is easy to create your own scopes.

But I don't know how to do it. And I don't understand how to pass the context when retrieving a dependency.

I would be pleased to find some example of code about:
* Passing a context when retrieving an instance
* Creating a scope
* Passing a scope when retrieving an instance

**Comment by SalomonBrys** [comment]
Please read the section names "creating your own scope" of the documentation: http://kodein.org/Kodein-DI/?5.2/core#_create_your_own_scopes

Feel free to reopen this issue if you feel this documentation is not enough ;)

**Comment by jcornaz** [comment]
Thank you @SalomonBrys 

However, I still don't understand.

* Examples in the chapter you shared are incorrect. `SimpleScope` has 2 generic arguments not one. (`C` an `in A`). I *guess* `C` is the context type. But I have no idea what `A` is. And the Javadoc doesn't tell me more.
* I still don't know how to pass context/scope when I retrieve an instance? As far as I can see, `instance` only take tags and arguments. So how do I pass a context and/or a scope?

So please re-open the issue. I'm not able to do it myself.

**Comment by filipproch** [comment]
@jcornaz Hi, I also had trouble figuring this out, it's not very understandable how to use it from the documentation.

The last argument in scope, `A`, is the `argument` of the binding definition (for example, `multiton` has argument). 

To set the scope, you set the `Context` which is described in the documentation here: http://kodein.org/Kodein-DI/?5.2/core#_defining_context

A very simple example the could be:

**Scope**
```kotlin
object TestScope : WeakContextScope<TestContext, Any?>({
    MultiItemScopeRegistry()
})
```

**Binding**
```kotlin
bind<SuperUsefulClass>() with scoped(TestScope).singleton {
    SuperUsefulClassImpl(
        testContext = context
    )
}
```

**Retrieval**
Works in any Kodein instance, that has defined a context of the specified `TestContext` type.
```kotlin
val myKodein = ...;

myKodeinWithContext = myKodein.on(context = TestContext())

val scopedInstance by myKodeinWithContext.instance<SuperUsefulClass>()
```

I hope this helps anyone having the same troubles with this, so far poorly documented part. If I find more time, I will contribute to the documentation to improve it.

**Comment by jcornaz** [comment]
Thanks @filipproch. This is a lot clearer now.

@SalomonBrys Will you consider improving the documentation on this point?

**Comment by SalomonBrys** [comment]
OK, so based on the discussion here, I have simplified a lot the `Scope` interface and the process of scope creation.
I have also rewritten the relevant documentation: http://kodein.org/Kodein-DI/?6.0/core#_using_the_environment

Hope this provides a better experience.

**Comment by shasharm** [comment]
How do we declare a context object? I am trying with `val singletonContext = KodeinContext
` but it doesn't work in getting me the created singleton object in a different class. I want to inject the singleton dependencies in different modules for which I need to create a global context and hence, I am not restricted to the type<C> of the KodeinContext object.
