### ISSUE TITLE
In Kotlin Native project: Unable to find a matching configuration of org.kodein.di:kodein-di-core-native_kodein_di_core_native_macos_x64:5.2.0

### ISSUE THREAD

**Issue by luca992** [Kodein-Framework/Kodein-DI#150]
First of all kodein-di-erased-native does not link to the macos_x64 library

    dependencies {
        implementation 'org.kodein.di:kodein-di-erased-native:5.2.0'
    }

results with 

> Could not resolve org.kodein.di:kodein-di-erased-native:5.2.0.
  Required by:
      project :domain:domain-native
   > Unable to find a matching configuration of org.kodein.di:kodein-di-erased-native:5.2.0:
       - Configuration 'kodein-di-erased-native_android_arm32Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'android_arm32'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_android_arm64Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'android_arm64'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_linux_arm32_hfpLink':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'linux_arm32_hfp'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_linux_mips32Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'linux_mips32'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_linux_mipsel32Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'linux_mipsel32'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_linux_x64Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'linux_x64'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.
       - Configuration 'kodein-di-erased-native_wasm32Link':
           - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
           - Required org.gradle.native.kotlin.platform 'macos_x64' and found incompatible value 'wasm32'.
           - Found org.gradle.native.linkage 'STATIC' but wasn't required.
           - Required org.gradle.native.operatingSystem 'osx' but no value provided.
           - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
           - Found org.gradle.status 'release' but wasn't required.
           - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.

Then specifiying kodein-di-core-native_kodein_di_core_native_macos_x64 directly

    dependencies {
            implementation 'org.kodein.di:kodein-di-core-native_kodein_di_core_native_macos_x64:5.2.0'
    }

results with 

> Could not resolve org.kodein.di:kodein-di-core-native_kodein_di_core_native_macos_x64:5.2.0.
  Required by:
      project :domain:domain-native
   > Unable to find a matching configuration of org.kodein.di:kodein-di-core-native_kodein_di_core_native_macos_x64:5.2.0: Configuration 'kodein-di-core-native_macos_x64Link':
       - Required org.gradle.native.debuggable 'true' and found incompatible value 'false'.
       - Required org.gradle.native.kotlin.platform 'macos_x64' and found compatible value 'macos_x64'.
       - Found org.gradle.native.linkage 'STATIC' but wasn't required.
       - Required org.gradle.native.operatingSystem 'osx' but no value provided.
       - Required org.gradle.native.optimized 'false' and found compatible value 'false'.
       - Found org.gradle.status 'release' but wasn't required.
       - Required org.gradle.usage 'kotlin-native-klib' and found incompatible value 'native-link'.

**Comment by SalomonBrys** [comment]
This is due to an issue in artifact publishing in the K/N Gradle plugin that should have been resolved by now (so the dev in charge says).
It should be corrected in 5.2.1 & 5.3.0.

I'll post here once they have been published.

**Comment by SalomonBrys** [comment]
Kodein DI 5.3.0 has been released :)
