### ISSUE TITLE
Kodien Android 5.2.0 Core Not in JCenter

### ISSUE THREAD

**Issue by AndrewReitz** [Kodein-Framework/Kodein-DI#152]
Hey, it looks like the dependency didn't get deployed correctly yesterday.

I don't see it here https://jcenter.bintray.com/org/kodein/di/ and when trying to build using 
`implementation("org.kodein.di:kodein-di-framework-android-core:5.2.0")` or `implementation("org.kodein.di:kodein-di-framework-android-x:5.2.0")` 

I see

> Could not find org.kodein.di:kodein-di-framework-android-core:5.2.0.
     Searched in the following locations:
       - file:/Users/z002qd2/Library/Android/sdk/extras/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - file:/Users/z002qd2/Library/Android/sdk/extras/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - file:/Users/z002qd2/Library/Android/sdk/extras/google/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - file:/Users/z002qd2/Library/Android/sdk/extras/google/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - file:/Users/z002qd2/Library/Android/sdk/extras/android/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - file:/Users/z002qd2/Library/Android/sdk/extras/android/m2repository/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - https://dl.google.com/dl/android/maven2/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - https://dl.google.com/dl/android/maven2/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - https://jcenter.bintray.com/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - https://jcenter.bintray.com/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - https://maven.fabric.io/public/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - https://maven.fabric.io/public/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar
       - https://jitpack.io/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.pom
       - https://jitpack.io/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar

Let me know if you need any more details.
Thanks!

**Comment by jpardogo** [comment]
it is in here: https://dl.bintray.com/kodein-framework/Kodein-DI/org/kodein/di/kodein-di-framework-android-core/5.2.0/

but not here: https://jcenter.bintray.com/org/kodein/di/kodein-di-framework-android-core/5.2.0/kodein-di-framework-android-core-5.2.0.jar

Notice the url where it is says: https://dl.bintray.com.

I found this StackOverflow issue related: https://stackoverflow.com/questions/48677656/failed-to-resolve-after-bintray-upload-and-jcenter-link

**Comment by SalomonBrys** [comment]
This is due to a misunderstanding on my part about how bintray handles jcenter sync.

I'll correct that asap.

**Comment by SalomonBrys** [comment]
Fixed :)
