### ISSUE TITLE
Publish to maven central repository

### ISSUE THREAD

**Issue by ufoscout** [Kodein-Framework/Kodein-DI#157]
Would it be possible to publish kodein artifacts to maven central repository? This would make it available without the need to configure an additional repository in the project configuration.

**Comment by SalomonBrys** [comment]
I'm pretty happy with JCenter.
Also, I need (for stats) the artifacts to be only in one location.

I don't think it's going to happen, sorry.

**Comment by charleskorn** [comment]
Given the recent behaviour of Bintray (see https://blog.autsoft.hu/a-confusing-dependency/), I'm very hesitant to continue using JCenter. 

Kodein is the only library I depend on that isn't in Maven Central - would you reconsider moving (or at least mirroring) the package there?

**Comment by SalomonBrys** [comment]
I understand the fear of such articles, but you need to know that publishing to MavenCentral is, by no means, safer.
I have published several libraries into MC, and Sonatype's verification is exactly the same as Bintray's: check that the library exists & that the package name corresponds.
At no point did they ask me anything to prove I was the owner of the repo.
Hence, I don't believe MC is any safer than JC.
I'll have a look at publishing to MC, but no promises there.
