### ISSUE TITLE
Kotlin native 9.3 support

### ISSUE THREAD

**Issue by luca992** [Kodein-Framework/Kodein-DI#159]
I see v5.3.0 is built with kotlin native 9.2. Support for the latest (9.3) would be great.

**Comment by Dkhusainov** [comment]
I really need this too.

**Comment by luca992** [comment]
At this point, you should probably target native 1.0.1 which is what the kotlin 1.3.0 release is using

**Comment by SalomonBrys** [comment]
Kodein 6.0.0 is built with Kotlin 1.3.0, hence Kotlin/Native 1.0.1.
