### ISSUE TITLE
kotlin-multiplatform and Gradle 4.10

### ISSUE THREAD

**Issue by Dkhusainov** [Kodein-Framework/Kodein-DI#160]
What's the ETA for supporting new `kotlin-multiplatform` plugin and 0.4 version of gradle metadata? Right now if I try to import kodein ina `kotlin-multiplatform` with Gradle 4.10, it gives me an error `Unsupported format version 0.3 specified in module metadata. This version of Gradle supports format version 0.4 only`. Some other dependencies in my module are already using 0.4, so I can't use the library.

**Comment by luca992** [comment]
That's dependant on kotlin being compiled with gradle >4.7.

Related. https://github.com/Kotlin/kotlinx.coroutines/issues/564

As a workaround, you could compile and locally publish your other dependencies using gradle 4.7

**Comment by Dkhusainov** [comment]
Looks like I'll have to do that for now. What about support for `kotlin-multiplatform`?

**Comment by luca992** [comment]
they didn't build it with kotlin-multiplatform.. but that doesn't mean you can't use it while using kotlin-multiplatform in your project.

Just add kodein-di-core-common as a dependency to your common source set, and kodein-di-core-jvm to your jvm source set, and so on.... for example

**Comment by Dkhusainov** [comment]
Okay, I will do that. You can close the issue. Thanks.

**Comment by SalomonBrys** [comment]
OK, so I've published version 6.0.0 AND version6.0.0-LGM.
LGM stands for Latest Gradle Metadata, and is the exact same kodein, except with Gradle Metadata 0.4.

LGM versions are NOT in JCenter, so you need to add the Kodein-LGM repository to access the artifacts.

http://kodein.org/Kodein-DI/?6.0/core#_latest_gradle
