### ISSUE TITLE
Kodein plugin

### ISSUE THREAD

**Issue by Dwite** [Kodein-Framework/Kodein-DI#162]
There is a mention of Kodein plugin at the documentation, but unfortunatelly link is directing to [todo](http://todo/) . Could you please provide the link and fix documentation?

> There is an official plugin to ease the use of Kodein in Android, you can read more about it on the dedicated document.

**Comment by SalomonBrys** [comment]
This is not a "plugin" per se, it is a separate module.
See http://kodein.org/Kodein-DI/?5.3/android

**Comment by Dwite** [comment]
> This is not a "plugin" per se, it is a separate module.
> See http://kodein.org/Kodein-DI/?5.3/android

At the [documentation](http://kodein.org/Kodein-DI/?5.3/core), you can find such text:


> There is an official plugin to ease the use of Kodein in Android, you can read more about it on the dedicated document.

That's what I proposed to update.
