### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.kodein.di.Kodein

### ISSUE THREAD

**Issue by Houdini** [Kodein-Framework/Kodein-DI#164]
When use gradle directly all is fine,
however after ./gradle shadowJar I catch this error:

```
Caused by: java.lang.ClassNotFoundException: org.kodein.di.Kodein
```

Add `maven { url "https://dl.bintray.com/kodein-framework/Kodein-DI" }` doesn't work

**Comment by SalomonBrys** [comment]
This looks like a bug in the shadowJar plugin.
There's no need for the maven repository anymore (unless you are using LGM)
