### ISSUE TITLE
"The tree contains a key that is not in the map." in 6.0.0

### ISSUE THREAD

**Issue by mopsalarm** [Kodein-Framework/Kodein-DI#167]
Starting with kodein erased 6.0.0 on jvm i get the error message from the title. No changes except the kodein update:

![20181124-163713](https://user-images.githubusercontent.com/11006365/48970032-697c6f00-f007-11e8-87fa-36eac7828125.png)

**Comment by SalomonBrys** [comment]
That is very troubling.
I'll have a look.

**Comment by SalomonBrys** [comment]
This is an internal bug that should never happen.
Yet, it happens...
I can't find a way to reproduce it. This is very troubling.
Can you share the binding that you are trying to retrieve and that makes Kodein crash ?

**Comment by mopsalarm** [comment]
Thats difficult as I did not get this error myself. I only see it in firebase crashlytics.
It looks like it is trying to get a normal singleton binding (that at this point should already be injected somewhere else once or twice). 

Kodein is multithread compatible, yes? I normally only do injections in android main thread, only at some places I fetch some injections from another place.

I build my bindings here:
https://github.com/mopsalarm/Pr0/blob/master/app/src/main/java/com/pr0gramm/app/ApplicationClass.kt#L126

**Comment by SalomonBrys** [comment]
This is baffeling.
I am completely unsetteled about this. This should never happen.
The tree and the cache (map) are constructed and filled at the same time, and I see no way this error could occur.
Still, it did.
It MAY be about parrallelism (but I don't believe it). However, there was a potential race condition, so I removed it (thanks for making me check).

I have modified the error in 6.0.1 so its message gives more information.
If it happen again in 6.0.1 +, please re-file a new issue with the new message.

I'll close this issue when 6.0.1 is published.

**Comment by SalomonBrys** [comment]
Version 6.0.1 is live.
Please open a new issue with the updated exception message if this happens again.
Thanks a lot for the report.
