### ISSUE TITLE
Maven Cannot resolve kodein-di-jx-inject-jvm:jar:6.0.1

### ISSUE THREAD

**Issue by ufoscout** [Kodein-Framework/Kodein-DI#169]
Maven cannot resolve either version 6.0.0 and 6.0.1 of org.kodein.di:kodein-di-jx-inject-jvm
```
[ERROR] Failed to execute goal on project my-project: Could not resolve dependencies for project my-project:kodein:jar:1.0.0-SNAPSHOT: Could not find artifact org.kodein.di:kodein-di-jx-inject-jvm:jar:6.0.1 in bintray (https://dl.bintray.com/kodein-framework/Kodein-DI/) -> [Help 1]
```

Mvn repo shows up to version 5.3.0: 
https://mvnrepository.com/artifact/org.kodein.di/kodein-di-jx-inject-jvm

**Comment by SalomonBrys** [comment]
In 6.0.0, `jx-inject` has been renamed to `jxinject` for naming / categorizing reasons.
I have completely forgot to update the documentation.
Sorry about that.

You need to import `org.kodein.di:kodein-di-jxinject-jvm:jar:6.0.1`.

The documentation has been fixed.
