### ISSUE TITLE
Kodein cannot be used in common code of a multiplatform project

### ISSUE THREAD

**Issue by NorbertSandor** [Kodein-Framework/Kodein-DI#177]
At least, I haven't found a corresponding Gradle dependency...

**Comment by DrewCarlson** [comment]
Kodein can be used in common sources.

The following multiplatform configuration will include Kodein in your common sources.
```groovy
kotlin {
  // ... targets ...
  sourceSets {
    all {
      dependencies {
        implementation "org.kodein.di:kodein-di-core:$kodein_version"
        implementation "org.kodein.di:kodein-di-erased:$kodein_version"
      }
    }
}
```

If you have native targets, you will need to wait for a new release of Kodein to target Kotlin 1.3.20.

**Comment by NorbertSandor** [comment]
While experimenting I added to following modules to commonMain and it seems to work:

```
implementation("org.kodein.di:kodein-di-core-metadata:$kodeinVersion")
implementation("org.kodein.di:kodein-di-erased-metadata:$kodeinVersion")
```

Although I don't know what these modules do :)

**Comment by DrewCarlson** [comment]
What version of Gradle are you using?  Do you have `enableFeaturePreview('GRADLE_METADATA')` enabled in your `settings.gradle` file?  Can you post the Kotlin configuration section of your build script?

Note that Kodein 6.0.1 will not work with native targets using Kotlin 1.3.20.

**Comment by SalomonBrys** [comment]
Kodein 6.1.0 is compiled with Kotlin 1.3.20.
Its gradle metadata is version 0.4 :)
