### ISSUE TITLE
Why instance can't be found in fragment?

### ISSUE THREAD

**Issue by ChenJia-X** [Kodein-Framework/Kodein-DI#178]
I have a top-level variable `loginKodeinModule`, importing it in `LoginActivity`. 

```kotlin
val loginKodeinModule = Kodein.Module(LOGIN_MODULE) {
    bind<LoginViewModel>() with scoped<AppCompatActivity>(AndroidLifecycleScope).singleton {
        LoginViewModel.instance(context, instance())
    }
}   
```

```kotlin
class LoginActivity : BaseActivity<ActivityLoginBinding>() {
    override val kodein:Kodein by retainedKodein {
        extend(parentKodein, copy = Copy.All)
        import(loginKodeinModule)
    }
}
```

And  I want to get a instance of  `LoginViewModel` in `LoginWithCodeFragment`.  `LoginActivity` contains `LoginWithCodeFragment`  and shows it with `Navigation` of Android Jetpack.

```kotlin
class LoginWithCodeFragment : BaseFragment<FragmentLoginBinding>() {
    override val kodein: Kodein by closestKodein()
    
    val loginViewModel:LoginViewModel by instance()
}
```

But when I run , it throws exceptions:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{***.LoginActivity}: org.kodein.di.Kodein$NotFoundException: No binding found for bind<LoginViewModel>() with ?<Fragment>().? { ? }
    Available bindings for this type:
            module LoginModule {
                bind<LoginViewModel>() with scoped(AndroidLifecycleScope.multiItem).singleton { LoginViewModel }
            }
```

Are there some problems in **binding LoginViewModel**, such as `scoped<AppCompatActivity>`?

How can i get a instance in Fragment when it imported at Activity ?

**Comment by SalomonBrys** [comment]
At that time, Kodein do not know how to access the fragment's activity.
For this, you have multiple options:

1. Manually give the activity to Kodein:
```kotlin
val loginViewModel: LoginViewModel by lazy { on(requireActivity()).direct.instance<LoginViewModel>() }
```
Note that version 6.1.0 will allow for lazy contexts, which means an easier syntax.
2. Import the androidModule that contains (between a lot of other things) the context translator needed by Kodein to understand how to transform a Fragment context into an Activity context:
```kotlin
val kodein = Kodein {
    import(androidModule) // or androidXModule, or androidSupportModule
}
```
Note that version 6.1.0 will allow you to access these translators without the rest of the module.
3. Manually register said context translator:
```kotlin
val kodein = Kodein {
    registerContextTranslator { f: Fragment -> f.activity }
}
```
