### ISSUE TITLE
Please guide : org.kodein.di.Kodein$NotFoundException: No binding found

### ISSUE THREAD

**Issue by GautamMandsorwale** [Kodein-Framework/Kodein-DI#180]
Hi Team,

I am not sure if this is an issue or I am doing something wrong. Please guide.

**Issue :**
```
org.kodein.di.Kodein$NotFoundException: No binding found for bind<WeatherForecastDatabase>() with ?<CurrentWeatherFragment>().? { ? }
    Registered in this Kodein container:
            bind<CurrentWeatherDao>() with singleton { CurrentWeatherDao }
            bind<CurrentWeatherViewModelFactory>() with provider { CurrentWeatherViewModelFactory }
            bind<Unit>() with singleton { Unit }
            bind<WeatherNetworkDataSource>() with singleton { WeatherNetworkDataSourceImpl }
            bind<WeatherForecastRepository>() with singleton { WeatherForecastRepositoryImpl }
            bind<ConnectivityInterceptor>() with singleton { ConnectivityInterceptorImpl }
            bind<WeatherApiService>() with singleton { WeatherApiService }
```

I am using below grade dependencies,
```
implementation "org.kodein.di:kodein-di-generic-jvm:6.1.0"
implementation "org.kodein.di:kodein-di-framework-android-x:6.1.0"
```

Here is my Application class below, which I have also added in AndroidManifest.xml,

```
class WeatherForecastApplication : Application(), KodeinAware {

    override val kodein = Kodein.lazy {
        import(androidXModule(this@WeatherForecastApplication))

        bind() from singleton { WeatherForecastDatabase(instance()) }

        bind() from singleton { instance<WeatherForecastDatabase>().getCurrentWeatherDao() }

        bind<ConnectivityInterceptor>() with singleton { ConnectivityInterceptorImpl(instance()) }

        bind() from singleton { WeatherApiService(instance()) }

        bind<WeatherNetworkDataSource>() with singleton { WeatherNetworkDataSourceImpl(instance()) }

        bind<WeatherForecastRepository>() with singleton { WeatherForecastRepositoryImpl(instance(), instance()) }

        bind() from provider { CurrentWeatherViewModelFactory(instance()) }
    }

    override fun onCreate() {
        super.onCreate()

        // init threetenbp library.
        AndroidThreeTen.init(this)
    }

}
```

And this is how I am referencing instances in Fragment,
```
class CurrentWeatherFragment : Fragment(), KodeinAware {
    override val kodein by kodein()
    private val factory: CurrentWeatherViewModelFactory by instance()

    private lateinit var viewModel: CurrentWeatherViewModel

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.current_weather_fragment, container, false)
    }

    override fun onActivityCreated(savedInstanceState: Bundle?) {
        super.onActivityCreated(savedInstanceState)
        viewModel = ViewModelProviders.of(this, factory).get(CurrentWeatherViewModel::class.java)
    }
}
```

**Comment by SUMAR7** [comment]
**I am facing a similar issue:**
` No binding found for bind<Activity>() with ?<MainActivity>().? { ? }
    Registered in this Kodein container:`

**Kodein Version : 6.1.0**

**My Activity Code**
`class MainActivity : AppCompatActivity(), KodeinAware {
    override val kodein by kodein()
    private val fusedLocationProviderClient: FusedLocationProviderClient by instance()
...............................
..............................
}`

**Comment by SUMAR7** [comment]
**I was able to fix this issue by explicitly specifying the instance** i.e. **Context**
`            bind() from provider { LocationServices.getFusedLocationProviderClient(instance<Context>()) }
`

**Comment by GautamMandsorwale** [comment]
@SUMAR7 

Tried your way, but couldn't get it to work :( . Glad it worked for you.

**Comment by SalomonBrys** [comment]
This is a very weird bug.
It seems that kodein never received the `WeatherForecastDatabase` binding, even though it is clearly in your code.

@SUMAR7 Do you have any repository I could clone ?

**Comment by SalomonBrys** [comment]
Reading your error, have you noticed this line in the error:

```kotlin
bind<Unit>() with singleton { Unit }
```

Are you sure that `WeatherForecastDatabase(instance())` is a class and not a function returning a Unit ?

Can you change the binding to be explicit?

```kotlin
bind<WeatherForecastDatabase>() with singleton { WeatherForecastDatabase(instance()) }
```

**Comment by SUMAR7** [comment]
@SalomonBrys I don't have any public repository to share because I haven't completed that series yet, however this is my code snip and it is working find.

`class EasyWeatherApplication : Application(), KodeinAware {
    override val kodein: Kodein
        get() = Kodein.lazy {
            import(androidXModule(this@EasyWeatherApplication))
            bind() from singleton { ForecastDatabase(instance()) }
            bind() from singleton { instance<ForecastDatabase>().currentWeatherDao() }
            bind() from singleton { instance<ForecastDatabase>().weatherLocationDao() }
            bind<ConnectivityInterceptor>() with singleton {
                ConnectivityInterceptorImpl(instance())
            }
            bind() from singleton { ApixuWeatherApiService(instance()) }
            bind<WeatherNetworkDataSource>() with singleton { WeatherNetworkDataSourceImpl(instance()) }
            if (ContextCompat.checkSelfPermission(
                    this@EasyWeatherApplication,
                    android.Manifest.permission.ACCESS_COARSE_LOCATION
                ) == PackageManager.PERMISSION_GRANTED
            )
                bind() from provider { LocationServices.getFusedLocationProviderClient(instance<Context>()) }
            bind<LocationProvider>() with singleton { LocationProviderImpl(instance(), instance()) }
            bind<ForecastRepository>() with singleton {
                ForecastRepositoryImpl(
                    instance(),
                    instance(),
                    instance(),
                    instance()
                )
            }
            bind<UnitProvider>() with singleton { UnitProviderImpl(instance()) }
            bind() from provider { CurrentWeatherViewModelFactory(instance(), instance()) }
        }

    override fun onCreate() {
        super.onCreate()
        AndroidThreeTen.init(this)
        PreferenceManager.setDefaultValues(this, R.xml.prefrences, false)
    }`

And there is nothing fancy in **CurrentWeatherFragment**


`class CurrentWeatherFragment : ScopedFragment(), KodeinAware {

    override val kodein by kodein()
    private val viewModelFactory: CurrentWeatherViewModelFactory by instance()

    private lateinit var viewModel: CurrentWeatherViewModel
}
`

**Comment by SalomonBrys** [comment]
@SUMAR7 I'm confused : are you saying that this is working, and that the bug is "gone" ?

**Comment by SUMAR7** [comment]
@SalomonBrys I am saying I'm not facing this bug anymore. Everything is working as expected. I have faced **No binding issue** few times but I was able to fix the issue as mentioned above. So I'm not sure if this is a bug on Kodein side.

**Comment by GautamMandsorwale** [comment]
@SalomonBrys 

I did recheck my `WeatherForecastDatabase` as suggested by you, and found that although it is a class, the function that was used to get an instance of this class returned nothing, which essentially meant `Unit`. Have made proper change and was able to get the app running.

Thanks a lot for your input. I had no clue that this could be a problem even though I read the crash logs mentioned above so many times. Had given up..

Maybe the team can add this in one of their README, as when this can happen and how to solve it?

Thanks again!

**Comment by SalomonBrys** [comment]
There's a better solution: Kodein could error when using `bind() from` with a binding that returns a `Unit`, as this is, in 99% of cases, an error. Being explicit (e.g. `bind<Unit>() with`) would still be allowed (also I cannot see why someone would consciously do that).

I'll close this issue once it is implemented.

**Comment by GautamMandsorwale** [comment]
@SalomonBrys 

Sure, this sounds helpful of having a bit more descriptive error message for this error.
Thanks!

**Comment by Mauricio-Souza** [comment]
Did you resolve this error? I had the same problem.

**Comment by EhsanFallahi** [comment]
> @SalomonBrys
> 
> I did recheck my `WeatherForecastDatabase` as suggested by you, and found that although it is a class, the function that was used to get an instance of this class returned nothing, which essentially meant `Unit`. Have made proper change and was able to get the app running.
> 
> Thanks a lot for your input. I had no clue that this could be a problem even though I read the crash logs mentioned above so many times. Had given up..
> 
> Maybe the team can add this in one of their README, as when this can happen and how to solve it?
> 
> Thanks again!

hi....please display your change in function into WeatherForecastDatabase...Because I have such a problem
