### ISSUE TITLE
Currying multi-variable factories

### ISSUE THREAD

**Issue by maxkrass** [Kodein-Framework/Kodein-DI#181]
Kodein Version: 6.1
Platform: Android

The basic idea is this:
I have a `MyFragment` class that has a `newInstance()` function. This function takes two arguments, `index: Int` and `adapter: MyAdapter`. The `adapter` is the same across all instances of the Fragment. The `index` will be different in every instance.

I have declared this dependency:
`bind<MyFragment>() with factory { index: Int, adapter: MyAdapter -> MyFragment.newInstance(index, adapter) }`

Now in `MyAdapter`, I want to have a factory method, that takes an `index: Int` and gives me the corresponding `MyFragment` instance. Sort of like this:
`fun someFun() {
val myFirstFragment = myFragmentFactory(0)
}`

To make this work, I declared `myFragmentFactory` inside `MyAdapter` as following:
`val myFramentFactory: (Int) -> MyFragment by kodein.factory()`
I realize, that, at this point, I will have to pass `adapter` (here `this`) to kodein. However, I can't find a way to neither pass an argument to `factory`, nor get a factory function back from `provider`, as `provider` returns a function that takes no arguments.

How could I make this work? This seems like something Kodein should be able to do but I can't figure out how. When declaring the dependency, should I use `multiton`, instead of `factory`?

Thanks a lot for your help and time!

**Comment by SalomonBrys** [comment]
```kotlin
val myFramentFactory: (Int) -> MyFragment = { kodein.direct.instance(arg = M(it, this)) }
```
