### ISSUE TITLE
TypeToken.isAssignableFrom() doesn't support interfaces with generics

### ISSUE THREAD

**Issue by dmarcato** [Kodein-Framework/Kodein-DI#185]
I think I found an issue when checking types compatibility when a class implements an interface with generics. An example is probably going to help clarify:

```kotlin
interface A

interface B : A

interface Base<T : A>

class Concrete : Base<B>

fun main() {

    val concrete = Concrete()
    val base: Base<out B> = concrete // correctly compiles

    val typeOfConcrete = TTOf(concrete)
    
    val typeToTest1 = generic<Base<out A>>()
    typeToTest1.isAssignableFrom(typeOfConcrete) // return true, correctly

    val typeToTest2 = generic<Base<out B>>()
    typeToTest2.isAssignableFrom(typeOfConcrete) // return false, wrongly
}
```

The last call to `isAssignableFrom` should still return true, since `Concrete` implements `Base<B>`, and so it should be assignable to `Base<out B>`.
At a first glance I think the issue might be [here](https://github.com/Kodein-Framework/Kodein-DI/blob/22a3780b80696282f06a849e3356ee8f74326985/kodein-di-core/src/jvmMain/kotlin/org/kodein/di/types.kt#L256), where it's being called `interfaces` instead of `genericInterfaces`.
Thoughts?

**Comment by SalomonBrys** [comment]
Thanks for a perfect test...
...and for a quasi-perfect explanation (the issue was in two places of the code) :smile:.
I've integrated it as-is and corrected the issue :+1:.
