### ISSUE TITLE
Deprecation of closestKodein and injected fragments

### ISSUE THREAD

**Issue by jpventura** [Kodein-Framework/Kodein-DI#188]
I've created `InjectedActivity` 

    abstract class InjectedActivity : AppCompatActivity(), KodeinAware {
    
        // kodein() automatically fetches app Kodein scope.
        private val appKodein by kodein()
    
        override val kodein: Kodein by retainedKodein {
            extend(appKodein)
            import(baseActivityModule(this@InjectedActivity), allowOverride = true)
            importOnce(activityModule())
            bind<ViewModelProvider.Factory>() with singleton {
                ViewModelFactory(kodein.direct)
            }
            (app().overrideBindings)()
        }
    
        /**
         * Optional to override, if your activity needs specific DI.
         */
        open fun activityModule() = Kodein.Module(
            "activityModule",
            allowSilentOverride = true
        ) {}
    }
    
    fun Activity.app() = applicationContext as RdApplication

and a `InjectedFragment`

    abstract class InjectedFragment : Fragment(), KodeinAware {

        private val activityKodein by kodein()
    
        override val kodein = Kodein.lazy {
            extend(activityKodein)
            import(baseFragmentModule(this@InjectedFragment), allowOverride = true)
            import(fragmentModule())
            bind<ViewModelProvider.Factory>(overrides = true) with singleton {
                ViewModelFactory(kodein.direct)
            }
            (app().overrideBindings)()
        }
    
        /**
         * Optional to override, if your fragment needs specific DI.
         */
        open fun fragmentModule() = Kodein.Module("fragmentModule") {}
    }
    
    fun Fragment.activity() = requireActivity() as InjectedActivity
    fun Fragment.app() = requireActivity().app()

Since `closestKodein` was deprecated and replaced by `kodein`, the following warning message is showing at `InjectedFragment`: *_Type checking has run into a recursive problem. Easiest workaround: specify types of your declarations explicitly._*

How could I refactor `InjectedFragment` using only `kodein`?

**Comment by jacobocl** [comment]
You have to use the `org.kodein.di:kodein-di-framework-android-x` (if you are using AndroidX's Fragment) or `org.kodein.di:kodein-di-framework-android-support` (if you are using Android Support's Fragment) dependency instead of the `org.kodein.di:kodein-di-framework-android-core` dependency. This way, you could import the kodein() specific function for the Fragment.

**Comment by SalomonBrys** [comment]
What you are trying to do has been replaced by subKodein: http://kodein.org/Kodein-DI/?6.1/android#_component_based_sub_kodein

In essence:

```kotlin
abstract class InjectedFragment : Fragment(), KodeinAware {
    override val kodein by subKodein {
        import(baseFragmentModule(this@InjectedFragment), allowOverride = true)
        import(fragmentModule())
        bind<ViewModelProvider.Factory>(overrides = true) with singleton {
            ViewModelFactory(kodein.direct)
        }
        (app().overrideBindings)()
    }

    /**
     * Optional to override, if your fragment needs specific DI.
     */
    open fun fragmentModule() = Kodein.Module("fragmentModule") {}
}
```
