### ISSUE TITLE
Is it possible to add Bindings after initialization?

### ISSUE THREAD

**Issue by PieterPicup** [Kodein-Framework/Kodein-DI#189]
Question:

Is it possible to add bindings to the Kodein instance after the initialization has finished on the main instance?

My problem:
I am using Kodein in an android app which has a large number of classes to be injected and this is causing my dex file to be to big because the initialization happens in the Application class and the dex building is including all of the classes being injected. Most of the injected classes are only needed much deeper in the app and are not needed in the main dex file. So I am looking for a way to add the remaining items to the Kodein object bindings later in the app lifecycle.

I have tried using a subKodein with a module importOnce but this still gives me a "must not override an existing binding." exception as I tried to create the subKodein in the activity and its fragments.

Please can someone guide me in the right direction to either get my dex file to stay small enough with all classes binding at the Application class or how to add the bindings later in lifecycle.

TIA

**Comment by SalomonBrys** [comment]
Have a look at Configurable Kodein:
http://kodein.org/Kodein-DI/?6.1/configurable

**Comment by PieterPicup** [comment]
@SalomonBrys Thanks. I will look at implementing this
