### ISSUE TITLE
Build with Kotlin 1.3.30

### ISSUE THREAD

**Issue by webfrea-k** [Kodein-Framework/Kodein-DI#190]
When can we expect a version bundled with Kotlin 1.3.30? 
Due to some other issues, we would really like to upgrade to 1.3.30, and the only thing missing is this lovely library :)

**Comment by Judrummer** [comment]
Can't agree more

**Comment by SalomonBrys** [comment]
Working on it ;)

**Comment by SalomonBrys** [comment]
Kodein-DI `6.2.0` has been released.
It is compiled with Kotlin `1.3.30`.

Enjoy ;)

**Comment by webfrea-k** [comment]
Thank you @SalomonBrys . Appreciate it. :)
