### ISSUE TITLE
Core packages removed from jcenter

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/Kodein-DI#192]
We're getting errors on clean builds of our project saying that `org.kodein.di:kodein-di-core-jvm:6.2.0` doesn't exist. [Looking at jcenter, I can confirm that it no longer exists](http://jcenter.bintray.com/org/kodein/di/).

We depend on:

"org.kodein.di:kodein-di-erased-jvm:6.2.0"
"org.kodein.di:kodein-di-generic-jvm:6.2.0"
"org.kodein.di:kodein-di-framework-android-x:6.2.0"

**Comment by eygraber** [comment]
To clarify, this project has been working fine for months, and this issue started today.

**Comment by RazmikDev** [comment]
Use ```maven { url = uri("https://dl.bintray.com/kodein-framework/Kodein-DI") }``` as a workaround

**Comment by sam43** [comment]
Temporary work around is not working for me. Anything else that can help? Please let me know...

**Comment by jpventura** [comment]
Thanks to @RazmikDev and [Gradle Docs](https://docs.gradle.org/current/userguide/declaring_repositories.html), I've made this quick dirty hack that solved for me

    allprojects {
        repositories {
            google()
            jcenter()
            maven { url 'http://dl.bintray.com/kotlin/kotlin-eap' }
            maven {
                url 'https://jitpack.io'
                content {
                    // Exclude Kodein artifacts
                    excludeGroupByRegex "org\\.kodein.*"
                }
            }
            maven { url 'https://dl.bintray.com/kodein-framework/Kodein-DI' }
        }
    }

**Comment by GabriellCosta** [comment]
> Thanks to @RazmikDev and [Gradle Docs](https://docs.gradle.org/current/userguide/declaring_repositories.html), I've made this quick dirty hack that solved for me
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         maven { url 'http://dl.bintray.com/kotlin/kotlin-eap' }
>         maven {
>             url 'https://jitpack.io'
>             content {
>                 // Exclude Kodein artifacts
>                 excludeGroupByRegex "org\\.kodein.*"
>             }
>         }
>         maven { url 'https://dl.bintray.com/kodein-framework/Kodein-DI' }
>     }
> }
> ```

Why you need to exclude it? if not find in jcenter he will not look in `dl.bintray.com` for the artifacts ?

**Comment by SalomonBrys** [comment]
Bintray has removed the packages from JCenter due to an internal repository re-organisation.
I've contacted them to fix this issue.

In the meantime, add this repository to gradle:

```
maven { url 'https://dl.bintray.com/kodein-framework/Kodein-DI' }
```

**Comment by SalomonBrys** [comment]
Fixed: https://jcenter.bintray.com/org/kodein/di/
