### ISSUE TITLE
Please make at least some page with deprecations

### ISSUE THREAD

**Issue by hanibalsk** [Kodein-Framework/Kodein-DI#194]
I found several functions not existed anymore.

Like:
// Currying:
val appPrefs: Prefs = kodein.with("app").instance()

and etc.

It would be nice to have at least some major page with some major changes of API. It took me 2 hours to figure out this: val appPrefs: Prefs by kodein.instance(args = "app")

**Comment by romainbsl** [comment]
It seems you updated from a version lower than `5.0.0` ?
You could have found this in the migration guide (`from 4 to 5`):

```kotlin
// Kodein 4
val dice: Dice = kodein.with(6).instance()
// Kodein 5
val ds: DataSource by kodein.instance(arg = 6)
```

https://kodein.org/Kodein-DI/?6.2/migration-4to5#_currying_2

**Comment by hanibalsk** [comment]
I am really sorry. I was looking for it there and I was blind
