### ISSUE TITLE
Gradle dependency issue for Android for 5.3.0

### ISSUE THREAD

**Issue by roy989898** [Kodein-Framework/Kodein-DI#199]
Last week still ok

Here is the error

ERROR: Failed to resolve: kodein-di-generic-jvm
Affected Modules: app

ERROR: Failed to resolve: kodein-di-framework-android-support
Affected Modules: app

ERROR: Failed to resolve: kodein-di-framework-android-core
Affected Modules: app

ERROR: Failed to resolve: kodein-di-core-jvm
Affected Modules: app

ERROR: Failed to resolve: kodein-di-core-common
Affected Modules: app

**Comment by Weightang** [comment]
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/kodein-framework/Kodein-DI/' }
    }
}
```
I hope to help you.

**Comment by SalomonBrys** [comment]
Duplicate of #192
