### ISSUE TITLE
Removal of ActivityRetainedScope.MultiItem in 6.2.0

### ISSUE THREAD

**Issue by rabidaudio** [Kodein-Framework/Kodein-DI#202]
`ActivityRetainedScope.MultiItem` in the Android lib is no longer defined in 6.2.0.

Was the removal of [this line](https://github.com/Kodein-Framework/Kodein-DI/commit/4d2f5eba5345c8773ca9d915d91c08828fcb3a8f#diff-8b0761f21d8250ee4fbe75de621328eeL34) intentional, or did you just mean to remove the deprecated definitions?

**Comment by SalomonBrys** [comment]
This looks like an error.
I'll investigate.
Thanks for the report.

**Comment by SalomonBrys** [comment]
Version 6.2.1 was just released with the fix.

Sorry about that.
