### ISSUE TITLE
Kotlin native problems with erased types.

### ISSUE THREAD

**Issue by flaquir4** [Kodein-Framework/Kodein-DI#208]
I have this code in kodein erased, wich returns all instances of Foo. 

` 
Bind(erasedComp1<List<Foo>, Foo>()) with singleton {
            val key = Kodein.Key(kodein.kodeinContext.anyType, UnitToken, erased<Foo>(), null)
            kodein.container.allProviders(key, context).map { it.invoke() }
}`

My project is android ios multiplatform, and this code is working on Android, but crashes on iOS.

Do you know why?

**Comment by romainbsl** [comment]
We may have change a lot of thing on this topic, don't hesitate to give us feedback if you still have issues.
