### ISSUE TITLE
function kodein() not available in Android Application class

### ISSUE THREAD

**Issue by lamba92** [Kodein-Framework/Kodein-DI#211]
The pattern shown [here](https://kodein.org/Kodein-DI/?6.2/android#_being_kodeinaware) is not available. Maybe something changed?

**Comment by lamba92** [comment]
The `org.kodein.di.android.kodein` function import suggestion is shadowed by the `kodein` property of `KodeinAware` interface. The import must be added manually and is not written in the documentation anywhere. I suggest to change the name of the `kodein` interface property or the `kodein()` extension function to properly allow IntelliJ to suggest the import. 

This may be an IntelliJ suggestion as well.

**Comment by SalomonBrys** [comment]
In Kodein 6.3.0 you can use either `closestKodein()` or `kodein()`
