### ISSUE TITLE
"Unable to find a matching variant" after upgrading to 6.3

### ISSUE THREAD

**Issue by charleskorn** [Kodein-Framework/Kodein-DI#219]
After updating to v6.3.0, I'm seeing these errors when Gradle starts:

```
Execution failed for task ':app:compileKotlin'.
> Could not resolve all files for configuration ':app:compileClasspath'.
   > Could not resolve org.kodein.di:kodein-di-generic-jvm:6.3.0.
     Required by:
         project :app
      > Unable to find a matching variant of org.kodein.di:kodein-di-generic-jvm:6.3.0:
          - Variant 'apiElements' capability org.kodein.di:kodein-di-generic-jvm:6.3.0:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '12'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api-jars'.
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'jvm' and found compatible value 'jvm'.
          - Variant 'runtimeElements' capability org.kodein.di:kodein-di-generic-jvm:6.3.0:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '12'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Found org.gradle.status 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime-jars'.
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
                  - Required org.jetbrains.kotlin.platform.type 'jvm' and found compatible value 'jvm'.
```

Does Kodein 6.3 only support Java 12? Or do I not have something configured correctly?

**Comment by brezinajn** [comment]
Same here

**Comment by romainbsl** [comment]
yep, sorry for the issue. We recently move onto jdk12 to build our Kodein modules. However, this should not be a no go for the projects that use 1.8, we might have broke something in the process.

I'll looked into it.

**Comment by romainbsl** [comment]
While waiting for us to fix the issue, you can add the following configuration into your gradle build file to be able to compile your projects:

```
java {
    disableAutoTargetJvm()
}
```
Source:
https://docs.gradle.org/current/userguide/upgrading_version_5.html#automatic_target_jvm_version

**Comment by romainbsl** [comment]
fixed with patch version `6.3.1`

**Comment by niiamon** [comment]
@romainbsl hi! this issue still persists in `6.5.4`.

**Comment by niiamon** [comment]
@romainbsl on closer reading, I think my issue is different:

> Could not resolve all files for configuration ':sampleProject:jooqRuntime'.
   > Could not resolve org.kodein.di:kodein-di-conf-jvm:6.5.4.
     Required by:
         project :sampleProject > com.strategies.jooq:default-jooq-strategy:0.0.103
      > Cannot choose between the following variants of org.kodein.di:kodein-di-conf-jvm:6.5.4:
          - jvm-api
          - jvm-runtime
          - metadata-api
        All of them match the consumer attributes:
          - Variant 'jvm-api' capability org.kodein.di:kodein-di-conf-jvm:6.5.4:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-api-jars' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'jvm-runtime' capability org.kodein.di:kodein-di-conf-jvm:6.5.4:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'java-runtime-jars' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
          - Variant 'metadata-api' capability org.kodein.di:kodein-di-conf-jvm:6.5.4:
              - Unmatched attributes:
                  - Found org.gradle.status 'release' but wasn't required.
                  - Found org.gradle.usage 'kotlin-api' but wasn't required.
                  - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.

**Comment by romainbsl** [comment]
Hi @niiamon

**Comment by niiamon** [comment]
@romainbsl found https://github.com/Kodein-Framework/Kodein-DI/issues/264 which fixes the issue for me.

**Comment by niiamon** [comment]
@romainbsl thanks a lot for the test! I am going to spin up a separate project to try that out and see what I end up with.
