### ISSUE TITLE
Go back to a standard branching model

### ISSUE THREAD

**Issue by SalomonBrys** [Kodein-Framework/Kodein-DI#230]
- [x] Branching: create `stable`, current `master` becomes `stable`, current `dev` becomes `master`, delete `dev`.
- [x] Update the documentation JS script that lives in the branch `gh-pages` to use branch `stable` by default instead of `master`.

**Comment by romainbsl** [comment]
**-> done**
- `stable` creation based on `master`
- `gh-pages` update to work on `stable` branch
- `dev` branch forced pushed onto `master`
- `dev` branch deletion
