### ISSUE TITLE
Resolving cyclic dependencies

### ISSUE THREAD

**Issue by LimmaPaulus** [Kodein-Framework/Kodein-DI#231]
Hi!

Are there any simple way to cope with cyclic dependencies. For example something like section "Break the cycle with provider" in Guice manual
https://github.com/google/guice/wiki/CyclicDependencies
I'm wondering why the following is not working
```
val kodein = Kodein {
    bind() from provider { Shop(instance()) }
    bind() from provider { Clerk(kodein) }
}

class Shop(val clerk: Clerk) {

    val name = "shop name"
}

class Clerk(override val kodein: Kodein) : KodeinAware {

    private val shop: Shop by kodein.instance()

    fun doSomething() {
        val shopName = shop.name
    }
}
```
When I run following code
```
val clerk : Clerk by kodein.instance()
clerk.doSomething()
```
I got a DependencyLoopException in the doSomething(). I would imagine that it would be possible to manage this situation, because it is possible to create a Clerk without having a Shop. So why not to 

Create Clerk -> Create Shop and pass the Clerk -> Pass Shop to Clerk's property when it is asked

**Comment by romainbsl** [comment]
Hi! 

You could do the following thing in your `Clerk` class:

`private val shop: Shop by instance()`

instead of 

`private val shop: Shop by kodein.instance()`

As your class is KodeinAware, the `kodein` is not necessary, thus you can just write `by instance()`. This would resolve the dependency loop, as the `shop` will be lazily retrieved when needed.

Hope this explanation is clear enough.

**Comment by LimmaPaulus** [comment]
Thank you, it works now :)

**Comment by romainbsl** [comment]
Hello,

I'll suggest you to break the cycle between the `Clerk` and the `Shop`.

Otherwise, the injection cannot be done (as for guice neither).

Still, you could be able to do it by using a factory for the shop, regarding the following code.

```kotlin
fun main() {
    val kodein = kodein.on(context = Context("test value"))
    val clerk by kodein.instance<Clerk>()
    clerk.doSomething()
}

data class Context(val contextValue: String)

val kodein = Kodein {
    bind() from contexted<Context>().factory { clerk: Clerk -> Shop(clerk) }
    bind() from contexted<Context>().provider { Clerk(kodein, context) }
}

class Shop(val clerk: Clerk) {
    val name = "shop name"
}

class Clerk(
    override val kodein: Kodein,
    private val context: Context
) : KodeinAware {

    private val shop: Shop by instance(arg = this)

    override val kodeinContext: KodeinContext<*>
        get() = kcontext(context)

    fun doSomething() {
        val shopName = shop.name
        println(shopName)
    }
}
```

**Comment by LimmaPaulus** [comment]
Hmm, I don't really understand why using Context messed things up so that it is impossible to do the injection now, but I trust you. Breaking the dependency in my real world scenario is very tricky, and the solution you suggested has a drawback that I have to forward factory argument long way down on each injection. But I will find solution with one or the other way, thank you!
