### ISSUE TITLE
Android Dynamic Delivery confusion

### ISSUE THREAD

**Issue by igorwojda** [Kodein-Framework/Kodein-DI#235]
What is the best way to deal with Android Dynamic Delivery? 
The assumption here is that part of Android app (`com.android.dynamic-feature` module) will be downloaded latter at some point. Assuming this dynamic Android module contains Kodein module is there any way to dynamically add it to kodein dependency tree?

Current solution works fine when all modules are known at app start.
```
class MyCustomApplication : KodeinAware {
    override val kodein = Kodein.lazy {
        import(androidXModule(this@ShowcaseApplication))
        import(appModule)
    }
}
```

However with Android dynamic modules
```
class MyCustomApplication : KodeinAware {
    override val kodein = Kodein.lazy {
        import(androidXModule(this@ShowcaseApplication))
        import(appModule)
    }

	//...
	fun onFeatureAlbumModuleDownloaded() {
		// retrieve insatnce of kodein module from the 
        // downloaded module via reflection

		//Add it somehow to "App level kodein"?
    } 
}
```

**Comment by romainbsl** [comment]
Hello, 
If you're sure the Kodein container won't be needed before downloading your module you could use a `override lateinit var kodein: Kodein`, and then define it like:

```kotlin
fun onFeatureAlbumModuleDownloaded() {
      // ...
        kodein = Kodein {
            import(androidXModule(this@DemoApplication))
            import(appModule)
            import(downloadedModule)
        }
      // ...
}
```

As its a `var`, you could also override it:

```kotlin
override lateinit var kodein: Kodein

init {
    kodein = Kodein {
        import(androidXModule(this@DemoApplication))
        import(appModule)
    }
}


fun onFeatureAlbumModuleDownloaded() {
    // ...
    kodein = Kodein {
        extend(kodein)
        import(downloadedModule)
    }
    // ...
}
```

> but I wouldn't recommend it as mutability of the container is dangerous

**Comment by igorwojda** [comment]
This is the problem I am not sure, even more, I want to be able to fully utilize [Android Dynamic Delivery](https://developer.android.com/studio/projects/dynamic-delivery), so modules will be downloaded only when actually needed. 

This leads to the conclusion that we need a way to dynamically register module at any point of time sth. like:
`rooKodein.registerNewModule(kodeinModule)`

Above assumes that each Android dynamic module provides kodein module that can satisfy his dependencies (to be specific both kodein module stored in Android `app` module + kodein module stored in dynamic feature satisfy the dependencies).

**Comment by SalomonBrys** [comment]
Hi @igorwojda,
Have you taken a look at Configurable Kodein?
I believe it fits exactly your need.

https://kodein.org/Kodein-DI/?6.3/configurable

**Comment by igorwojda** [comment]
Thx for the suggestion.
So going through docs and code I still try to connect all the puzzlers together. 
I think `ConfigurableKodein` maybe what I need indeed, but I would appreciate a bit more clarification.

**1. Performance penalty**
*Note that every time a ConfigurableKodein is mutated, its cache is entirely flushed, meaning that it has a real impact on performance!*

Considering these methods...
```
configurableKodein.addImport()
configurableKodein.addImport()
configurableKodein.addExtend()
```

Is the `flushing entire cache` happens every time one of these methods is called?

**2. Add module without clearing cache**
This is a bit connected to prev question. Is it possible to achieve such a solution without clearing cache all the time?
eg.
```
-appKodeinModule
---featureProfileKodeinModule
---featureFavouritesKodeinModule
```

Now I want to add another module from a dynamically downloaded feature. Can I "just add it" without clearing cache?
(I know am mutating Kodein tree here, but in reality, I am adding dependencies. Each class is prefixed with the feature module package name, so there are no conflicts. If some dependency would be duplicated this would be a dev bug due to incorrect package name, so a crash is welcome)


**3. Android integration**
What is the best way to integrate `ConfigurableKodein` withing the Android App? 
Assuming `Kodein.lazy` is recommended starting point...
```
class ShowcaseApplication : SplitCompatApplication(), KodeinAware {
    override val kodein = Kodein.lazy {
        import(androidXModule(this@ShowcaseApplication))
        import(appModule)
    }
    ...
}
```

...should it be simply replaced with `ConfigurableKodein` like this?

```
class ShowcaseApplication : SplitCompatApplication(), KodeinAware {
    override val kodein = ConfigurableKodein().apply {
        addImport(androidXModule(this@ShowcaseApplication))
        addImport(appModule)
    }
    ...
}
```

**4. External sources**
I wonder why `ConfigurableKodein` does not support `externalSources`? Is there assumption that dependencies may be added so the fallback will never be needed? or there was no request for this feature?

**Comment by romainbsl** [comment]
1. Performance penalty

Nope, if I understand the configurable module, the container will be built at the first retrieval. 
Thus, the cache might be cleared at first mutation.

2. Add module without clearing cache

I think that if there has been retrieval between mutations the cache will be cleared. 
The Kodein container can't know in advance that your modules are not related, and that naming are different, 
so the container will be refresh, thus the cache cleared.

Nevertheless, this could be featured, but not sure this would be done quickly as we have lot of stuff on the roadmap.

3. Android integration

Sure this is right. You could also retrieve the kodein container with the `closesKodein()` method :)

4. External sources

`ConfigurableKodein` is a `Kodein` object so, you can use external sources aswell.

```kotlin
override val kodein = ConfigurableKodein(mutable = true).apply {
    addConfig {
        externalSources += ExternalSource {
            //...
        }
    }
}
```

Hope @SalomonBrys could corroborate my remarks, or extend them.

**Comment by romainbsl** [comment]
Hi @igorwojda,

Did you still need help on this one ? Otherwise I will close the issue

**Comment by igorwojda** [comment]
I made it work with dependency inversion and a bit of reflection to dynamically retrieve `KodeinModuleProvider`. I am happy with the solution for now, so I will close this issue.

Here is a reference to my solution:
https://github.com/igorwojda/android-showcase/blob/master/app/src/main/java/com/igorwojda/showcase/app/feature/FeatureManager.kt
