### ISSUE TITLE
Question -  help to use in Java android kodein provider and instance

### ISSUE THREAD

**Issue by kevinzDzul** [Kodein-Framework/Kodein-DI#241]
How to represent this in java.
I don't understand the implementation in java with android

`class KodeinContainers {

    companion object {
        @ExperimentalCoroutinesApi
        val diBaseProject = Kodein {
            bind<RetrofitConfiguration>() with provider { RetrofitConfiguration() }
            bind<MealsByBeersNetworkDatasource>() with provider { MealsByBeersNetworkDatasource(instance()) }
            bind<MealsByBeersRepository>() with provider { MealsByBeersRepositoryImpl(instance()) }
            bind<GetBeersUseCase>() with provider { GetBeersUseCase(instance()) }
            bind<MealsByBeersViewModel>() with provider { MealsByBeersViewModel(instance()) }
        }
    }
}`

i try
but my result is this
`
public class Containers {

    private final Function0<RetrofitInstance> retrofitInstance;
    private final GalleryNetworkDataSource galleryNetworkDataSource;
    private final AlbumRepository albumRepository;
    private final GetAlbumUseCase getAlbumUseCase;
    private final AlbumViewModel albumViewModel;

    public Containers(DKodein kodein) {
        retrofitInstance = kodein.Provider(TT(RetrofitInstance.class),null);
        galleryNetworkDataSource = kodein.Instance(TT(GalleryNetworkDataSource.class),null);
        albumRepository = kodein.Instance(TT(AlbumRepositoryImpl.class),null);
        getAlbumUseCase = kodein.Instance(TT(GetAlbumUseCase.class),null);
        albumViewModel = kodein.Instance(TT(AlbumViewModel.class),null);
    }
}

`

is correct?

**Comment by SalomonBrys** [comment]
Looks like it.
What's the issue ?

**Comment by romainbsl** [comment]
@kevinzDzul do you still need help on this ? What's your issue ?

**Comment by kevinzDzul** [comment]
> @kevinzDzul do you still need help on this ? What's your issue ?

yes, is not issue, but I don't understand how to represent the implementation of the library in JAVA

**Comment by romainbsl** [comment]
Ok, I'll try to give you some samples as soon as I can

**Comment by romainbsl** [comment]
Hello, 

Here is an example.

Giving the following classes:
```kotlin
// model.kt
open class A {
    open fun print(): String = "I'm A!"
}
class B {
    fun print(): String = "I'm B!"
}
class C(val s: String) : A() {
    override fun print(): String = "I'm C with '$s value as 's'!"
}
```
I've defined the kodein container:
```kotlin
// kodein.kt
class KodeinContainers {
    companion object {
        val diBaseProject = Kodein {
            bind<A>() with provider { A() } // Declaring a provider for the class A
            bind<B>() with singleton { B() } // Declaring a singleton for the class B
            bind<C>() with factory {s: String -> C(s) } // Declaring a factory for the class C
        }.direct // returning the kodein container on a non-lazy form, needed by the Java usage
    }
}
```
And, I have a service class:
```java
// MyService.java
public class MyService {
    // We've defined a provider for A, so its a function without parameter returning A
    private final Function0<A> providerForA; 
    // We've defined a singleton, so its just an instance of B we're looking for
    private final B serviceB; 
    // We've defined a factory for C, so its a function with a String parameter returning C
    private final Function1<String, C> factoryForC;

    public MyService(DKodein kodein) { // DKodein is meeded here
        // Getting a provider from kodein for the type A
        providerForA = kodein.Provider(TT(A.class), null);
        // Getting an instance from kodein for the type B
        serviceB = kodein.Instance(TT(B.class), null);
        // Getting a factory from kodein for the type C, that need a String parameter
        factoryForC = kodein.Factory(TT(String.class), TT(C.class), null);
    }

    public void printA() {
         // Invoke the provider to retrieve a A object
        A serviceA = providerForA.invoke();
        // Use the object A
        serviceA.print();
    }

    public void printB() {
        // Simply using the B object
        serviceB.print();
    }

    public void printC() {
        // Invoke the factory to retrieve a C object with a String parameter
        C serviceC = factoryForC.invoke("Romain");
        // Use the object C
        serviceC.print();
    }
}
```

Finally, you can use your service by doing:
```java
private final MyService myService = new MyService(KodeinContainers.Companion.getDiBaseProject());

myService.printA();
myService.printB();
myService.printC();
```

Hope this help.

**Comment by romainbsl** [comment]
Also you could read this thread on using kodein with java https://github.com/Kodein-Framework/Kodein-DI/issues/242
