### ISSUE TITLE
Question - how to integrate with android activity in Java?

### ISSUE THREAD

**Issue by darylsze** [Kodein-Framework/Kodein-DI#242]
in Android Activity class in Java, after implementing KodeinAware, it needs to implement both
```java
    @NotNull
    @Override
    public KodeinContext<?> getKodeinContext() {
    }

    @org.jetbrains.annotations.Nullable
    @Override
    public KodeinTrigger getKodeinTrigger() {
    }
```

In old days, I can inject kodein by `getInjector()` method
```java
   @Override
    public void inject(Kodein kodein) {
        this.getInjector().inject(kodein);
        // all dependencies retrival
    }


    @Override
    public void onInjected(Function1<? super Kodein, Unit> function1) {
      // leave it blink.
    }
```

**Comment by SalomonBrys** [comment]
What's your question?
What's not working?

**Comment by darylsze** [comment]
Thanks for reply, I am stuck because of lack of documentation for java
integration. I saw all code examples are using Kotlin but no java, and my
project contains both Kotlin and java at the meantime, it would be better
to have guidelines.



「Salomon BRYS <notifications@github.com>」在 2019年8月27日 週二，上午8:02 寫道：

**Comment by darylsze** [comment]
Indeed I have gone deep into source code, but found lots of extension class
, for example, kodeinAware.Instance, and in which returns Kotlin delegation
that not compatible with java .

Could you give me some examples on how to integration Kodein on Android
activity written in Java ? Thanks !

「sze.kf1004@gmail.com <sze.kf1004@gmail.com>」在 2019年8月27日 週二，上午8:05 寫道：

**Comment by romainbsl** [comment]
Hi @darylsze do you still need help on this one ?

In order to use Kodein with Java, you have to pass around your Kodein container on its "direct" form (`kodein.direct`), like:

```kotlin
public class MyActivity {
    private final MyService serivce;
    public MyActivity(DKodein kodein) {
         service = kodein.Instance()
    }
 }
```
if you have some factory bindings you can use the `TT` method as in:

```kotlin
public class MyActivity {
    private final MyService serivce;
    public MyActivity(DKodein kodein) {
         service = kodein.Instance(TT(Integer.class), null)
    }
 }
```

**Comment by darylsze** [comment]
Thanks for the reply ! Yes I am still looking for examples like you just
provided! Your explanation is clear and useful !

Thanks a lots dude


「Romain Boisselle <notifications@github.com>」在 2019年9月25日 週三，下午8:43 寫道：

**Comment by romainbsl** [comment]
Ok, i'll close the issue, feel free to reopen it for more help

**Comment by darylsze** [comment]
or maybe, at least, some examples that getting both 'getKodeinContext'  and 'getKodeinTrigger' from  kodein object.,

thanks a lot!

**Comment by darylsze** [comment]
finally I figured out how! For those you have declared kodein injection in your application class, and want to retrieve from java activity class, you can follow below code:
1. implement `kodeinAware` in java activity
2. you will need to implement below three method `getKodein`, `getKodeinContext`, and `getKodeinTrigger` namely. 

```

    @NotNull
    @Override
    public Kodein getKodein() {
        return ((MyApplication) getApplication()).getKodein();
    }

    @NotNull
    @Override
    public KodeinContext<?> getKodeinContext() {
        return getKodein().getKodeinContext();
    }

    @org.jetbrains.annotations.Nullable
    @Override
    public KodeinTrigger getKodeinTrigger() {
        return getKodein().getKodeinTrigger();
    }
```
