### ISSUE TITLE
Update to 1.3.50

### ISSUE THREAD

**Issue by yshrsmz** [Kodein-Framework/Kodein-DI#243]
When can we expect a build with 1.3.50?
I really would like to see this happen(and possibly a fix for [this issue](https://github.com/Kodein-Framework/Kodein-DI/issues/222)).

**Comment by romainbsl** [comment]
Unfortunately we can't make it through a hotfix, we will have to wait the release of version `6.4`.
Hopefully, it will be release in the following days, depending on the time I'll to finish the other issues.

**Comment by romainbsl** [comment]
its in the pipeline :) 1fe0fa65648a72dcd79d30a7e9dd46d477cd2ed1

**Comment by romainbsl** [comment]
If you'd like to use the dev channel you can use the repository:
`https://dl.bintray.com/kodein-framework/kodein-dev` with the version `6.4.0-dev-630`

**Comment by yshrsmz** [comment]
thanks a lot, will try dev channel!

**Comment by romainbsl** [comment]
version `6.4.0` has been released with kotlin `1.3.50`compat
