### ISSUE TITLE
Version compatible with Kotlin 1.3.50

### ISSUE THREAD

**Issue by sky-filipeuva** [Kodein-Framework/Kodein-DI#244]
Current latest version is not compatible with Kotlin 1.3.50 as ABI versions do not match.

**Comment by romainbsl** [comment]
Didn't the chance to release a version yet.
As said here https://github.com/Kodein-Framework/Kodein-DI/issues/243 you can use the dev channel version untill we release it.

**Comment by sky-filipeuva** [comment]
Thanks !

**Comment by romainbsl** [comment]
version `6.4.0` has been released with kotlin `1.3.50`compat
