### ISSUE TITLE
Resolving dependencies to lesser scope is permitted?

### ISSUE THREAD

**Issue by aisanu** [Kodein-Framework/Kodein-DI#246]
Hey i found this behavior on kodein version 6.3.3.

Let say i have an unscoped singleton binding,  that has dependencies to other scoped instance:

```
bind<ScopedObject>() with scoped(SomeScopeProvider).singleton { ScopedObject() }
bind<UnscopedObject>() with singleton { UnscopedObject(instance<ScopedObject>()) }
```

The first time i access UnscopedObject is failed as expected.
```
assertFails("This fail as expected") { kodein.direct.instance<UnscopedObject>() }
```

Then if i access it on another scope and access it back from unscoped instance, it will always return the first instance created from the scoped.
```
assertFails("Should be failing, but currently permitted") {
    kodein.direct.on(SomeScope).instance<ScopedObject>()
}

assertFails("Should still be failing, but it will return the previous instance instead") {
    kodein.direct.instance<ScopedObject>()
}
```

I believe this behavior is not the intended one since it's make scoping behavior less predictable (eg. what if i have a weak referenced scope that could be gone anytime). And it's kinda block us to update our kodein dependencies (we still stuck at version 3).

**Comment by romainbsl** [comment]
I'm sure I following your idea here, but here is what I can tell to guide you with scopes.

Here is my context (using `6.4.0`)
```kotlin
class ScopedObject {}
class UnscopedObject(val scopedObject: ScopedObject)
object SessionScope : WeakContextScope<String>()

val kodein = Kodein {
    bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject() }
    bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
}
```

1. Accessing unscoped object 
```kotlin
    assertFails("This fail as expected") {
       val unscopedObject = kodein.direct.instance<UnscopedObject>()
    }
```
Sure this will fail because you try to retrieve an unscoped object with rely on a scoped object **outside** a scope, so it cannot find a scope object as its only bound with a scope.

However, if you do something like:
```kotlin
val unscopedObject = kodein.direct.on("session1").instance<UnscopedObject>()
```
This won't fail.

2. Accessing a scoped object
```kotlin
assertFails("Should be failing, but currently permitted") {
       val scopeObject = kodein.direct.on("session1").instance<ScopedObject>()
    }
```
Of course, this will work, because I'm trying to retrieve a scoped object on a scope. What could go wrong ?

3. (Re)accessing a scope object
```kotlin
  assertFails("Should still be failing, but it will return the previous instance instead") {
        val scopedObjectWithoutScope = kodein.direct.instance<ScopedObject>()
    }
```
This will have the same effect as in **1.** it will fail because we are outside a scope.

Here my full example:
```kotlin

import org.kodein.di.Kodein
import org.kodein.di.bindings.WeakContextScope
import org.kodein.di.direct
import org.kodein.di.generic.*
import kotlin.test.assertFails
import kotlin.test.assertTrue

val kodein = Kodein {
    bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject() }
    bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
}

object SessionScope : WeakContextScope<String>()
class UnscopedObject(val scopedObject: ScopedObject)
class ScopedObject {}

fun main() {
    val ex1 = assertFails("This fail as expected") {
       val unscopedObject = kodein.direct.instance<UnscopedObject>()
        println(unscopedObject)
    }
    println("Exception will trying to retrieve scoped object outside the scope\n$ex1")
    println("-----------------------------------------------------------------------------")

   val scopeObject = kodein.direct.on("session1").instance<ScopedObject>()
    println("ScopedObject $scopeObject with scope 'session1'")
    println("-----------------------------------------------------------------------------")

    val ex2 = assertFails("Should still be failing, but it will return the previous instance instead") {
        val scopedObjectWithoutScope = kodein.direct.instance<ScopedObject>()
        println(scopedObjectWithoutScope)
    }
    println("Exception will trying to retrieve scoped object outside the scope\n$ex2")
    println("-----------------------------------------------------------------------------")

    println("Compare the two exceptions: ${assertTrue { ex1.message == ex2.message }}")
}
```

With my output:

```
// 1.
Exception will trying to retrieve scoped object outside the scope
org.kodein.di.Kodein$NotFoundException: No binding found for bind<ScopedObject>() with ? { ? }
Available bindings for this type:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
Registered in this Kodein container:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
        bind<UnscopedObject>() with singleton { UnscopedObject }

-----------------------------------------------------------------------------
// 2.
ScopedObject org.kodein.di.sandbox.scope.ScopedObject@57fa26b7 with scope 'session1'
-----------------------------------------------------------------------------
// 3.
Exception will trying to retrieve scoped object outside the scope
org.kodein.di.Kodein$NotFoundException: No binding found for bind<ScopedObject>() with ? { ? }
Available bindings for this type:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
Registered in this Kodein container:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
        bind<UnscopedObject>() with singleton { UnscopedObject }

-----------------------------------------------------------------------------
Compare the two exceptions: true
```

**Comment by aisanu** [comment]
I think i've made some typos on the second part, causing the confusion. Here is my attempt to make full test for above scenario and retested on 6.3.3. I couldn't really tested on 6.4.0 on the time being since it seems it has another error when i build the project. 

```Kotlin
package com.invoice2go.di

import org.junit.Test
import org.kodein.di.bindings.ScopeRegistry
import org.kodein.di.bindings.StandardScopeRegistry
import org.kodein.di.conf.ConfigurableKodein
import org.kodein.di.direct
import org.kodein.di.generic.bind
import org.kodein.di.generic.instance
import org.kodein.di.generic.on
import org.kodein.di.generic.scoped
import org.kodein.di.generic.singleton
import kotlin.test.assertFails

class KodeinTest {
    val kodein = ConfigurableKodein()

    @Test fun `unscoped object depends on scoped object`() {
        kodein.addConfig {
            bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject(context) }
            bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
        }

        assertFails("Accessing unscoped object with scoped deps should fail") {
            kodein.direct.instance<UnscopedObject>()
        }

        assertFails("Accessing unscoped object from scope with scoped deps should fail") {
            val instance = kodein.direct.on("Scope").instance<UnscopedObject>()
            println("Successfully retreived $instance: ${instance.dependency.contextName}")
        }

        assertFails("Accessing unscoped object with scoped deps should fail") {
            val instance = kodein.direct.instance<UnscopedObject>()
            println("$instance: ${instance.dependency.contextName}")
        }
    }

    class ScopedObject(val contextName: String)
    class UnscopedObject(val dependency: ScopedObject)

    object SessionScope: org.kodein.di.bindings.Scope<String> {
        val registryMap = mutableMapOf<String, ScopeRegistry>()
        override fun getRegistry(context: String): ScopeRegistry =
                registryMap.getOrPut(context) { StandardScopeRegistry() }

    }
}
```
Having this kind of output when i run it:
```Console
Successfully retreived com.invoice2go.di.KodeinTest$UnscopedObject@3f49dace: Scope

java.lang.AssertionError: Accessing unscoped object from scope with scoped deps should fail. Expected an exception to be thrown, but was completed successfully.
```

One gotcha that i found is this line of code:
``` Kotlin
kodein.direct.instance<UnscopedObject>()
```
Will throw exception saying it couldn't find the binding for ScopedObject which is the expected behavior.

But if i do something like this:
``` Kotlin
val unscopedObject1 = kodein.direct.on("Scope").instance<UnscopedObject>()
val unscopedObject2 = kodein.direct.instance<UnscopedObject>()
```
It will be executed successfully.

The problem is, the returned instance `unscopedObject2` is the same instance from `unscopedObject1`. Since `unscopedObject1` has dependency from "Scope", isn't it kinda leaking the scope?

Hopefully this comment doesn't have too much typos that causing more confusion.

**Comment by romainbsl** [comment]
Ok, I get it. I don't think this is a glitch, because what you try to do is mix scoped and unscoped objects. 

What happen when you do the following code ?
```kotlin
val unscopedObject1 = kodein.direct.on("Scope").instance<UnscopedObject>()
```
Kodein tries to resolve `UnscopedObject` in the scope, but it doesn't. So it tries to resolve it without scope and find a way out with 
```kotlin
bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
```
But, it also needs to resolve `ScopedObject` in order to invoke the `UnscopedObject` constructor. This object is bound in a scope, so kodein use the context "Scope" to retrieve the `ScopedObject`.

Also, if you try to retrieve an unscoped object with a scope, like:
```kotlin
...
bind<UnscopedObject2>() with singleton { UnscopedObject2() }
...
val unscopedObject2 = kodein.direct.on("Scope").instance<UnscopedObject2>()
```
This will work.

Be careful, because if you mix scoped and unscoped you will have issues.
Regarding the following  bindings:
```kotlin 
bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject() }
bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
```
if you try to retrieve the `UnscopedObject` for two differents scopes, like:
```kotlin
val unscopedObject1 = kodein.direct.on("Scope1").instance<UnscopedObject>()
println("$unscopedObject1 / ${unscopedObject1.scopedObject}")
val unscopedObject2 = kodein.direct.on("Scope2").instance<UnscopedObject>()
println("$unscopedObject2 / ${unscopedObject2.scopedObject}")
```
then you will end with:
```
org.kodein.di.sandbox.scope.UnscopedObject@782830e / org.kodein.di.sandbox.scope.ScopedObject@470e2030
org.kodein.di.sandbox.scope.UnscopedObject@782830e / org.kodein.di.sandbox.scope.ScopedObject@470e2030
```
so `unscopedObject1==unscopedObject2` and `unscopedObject1.scopedOject == unscopedObject2.scopedObject`. Because you `UnscopedObject` binding is singleton.

If you want to mix scoped and unscoped objects you should consider using a provider
```kotlin
bind<UnscopedObject>() with provider { UnscopedObject(instance()) }
```

otherwise I recommend you to scope your unscoped object too.
```kotlin
    bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject() }
    bind<UnscopedObject>() with scoped(SessionScope).singleton { UnscopedObject(instance()) }
```

**Comment by aisanu** [comment]
Yes that's what i've trying to describe. I've actually have similar provider pattern for such use case, but the fact that this binding is allowed and didn't crash is what worried me. Since mixed scope is a common pattern, for example in our project we use it to have some kind of hierarchy similar to Dagger subcomponent.

Also on code review context, when we review change similar to this:
```Kotlin
bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }

class UnscopedObject(val dependency: ScopedObject)
```
There is no way we could know that `UnscopedObject` depends to scoped. And most of the time we provide the Kodein with a scope that's relevant when we use it (the user doesn't care where the dependency comes from) it will be harder to catch the issue during runtime/sanity test.

At the moment i still use the old version of Kodein (3.4.1) and it doesn't have this issue, but yeah we need to add our custom logic so it's able to access top-level object from scoped context.

Is it possible to retain current resolution mechanism (accessing top scope singleton from lesser scoped one) while disallowing this kind of binding (top level binding to scoped one)?

We have a wrapper on top of Kodein at the moment and we have a test that explicitly disallow such behavior, and it's the only blocker that prevent us from upgrading at the moment.

**Comment by romainbsl** [comment]
> the fact that this binding is allowed and didn't crash is what worried me
From my knowledge, we do not check scope binding in that way

I'm confused, if you don't know that dependencies are scoped, how do you expect that Kodein retrieve a `ScopedObject` outside of a scope without telling it ? Or, how do you tell it in which scope are you at the retrieval time ?

> Is it possible to retain current resolution mechanism (accessing top scope singleton from lesser scoped one) while disallowing this kind of binding (top level binding to scoped one)?

Are you asking for some changes in our codebase or some help to find a smooth resolution ?

Plus, I just copied your test code and run it on (6.3 && 6.4):
```kotlin
package org.kodein.di.sandbox.scope

import org.kodein.di.Kodein
import org.kodein.di.bindings.ScopeRegistry
import org.kodein.di.bindings.StandardScopeRegistry
import org.kodein.di.bindings.WeakContextScope
import org.kodein.di.direct
import org.kodein.di.generic.*
import org.kodein.di.sandbox.singleton.kodein
import kotlin.test.assertFails
import kotlin.test.assertTrue



class ScopedObject(val contextName: String)
class UnscopedObject(val dependency: ScopedObject)

object SessionScope: org.kodein.di.bindings.Scope<String> {
    val registryMap = mutableMapOf<String, ScopeRegistry>()
    override fun getRegistry(context: String): ScopeRegistry =
        registryMap.getOrPut(context) { StandardScopeRegistry() }

}
val kodein = Kodein {
    bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject(context) }
    bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
}

fun main() {
    val ex1 = assertFails("Accessing unscoped object with scoped deps should fail") {
        kodein.direct.instance<UnscopedObject>()
    }
    println(ex1)

    val ex2 = assertFails("Accessing unscoped object from scope with scoped deps should fail") {
        val instance = kodein.direct.on("Scope").instance<UnscopedObject>()
        println("Successfully retreived $instance: ${instance.dependency.contextName}")
    }
    println(ex2)

    val ex3 = assertFails("Accessing unscoped object with scoped deps should fail") {
        val instance = kodein.direct.instance<UnscopedObject>()
        println("$instance: ${instance.dependency.contextName}")
    }
    println(ex3)
}
```
all 3 cases failed.

**Comment by aisanu** [comment]
> I'm confused, if you don't know that dependencies are scoped, how do you expect that Kodein retrieve a ScopedObject outside of a scope without telling it ?

What i mean is, usually when we retrieving a dependency for object A, we know what the scope for that object A but we don't really care about the 'scope' of the dependencies.

Let say from the example i provided, we add another binding like this:
```Kotlin
data class ScopedObject(val contextName: String)
data class UnscopedObject(val dependency: ScopedObject)
data class AnotherObject(val unscopedObject: UnscopedObject)

val kodein = Kodein {
    bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject(context) }
    bind<UnscopedObject>() with singleton { UnscopedObject(instance()) }
    bind<AnotherObject>() with scoped(SessionScope).singleton { AnotherObject(instance()) }
}

val anotherObject = kodein.direct.on("SomeScope").instance<AnotherObject>()
println(anotherObject)
```
I think it's clearer now that we have misconfiguration on the bindings, and the scoping of the dependencies should be fixed. But instead of crashing, it executes successfully and produces following output:
```
AnotherObject(unscopedObject=UnscopedObject(dependency=ScopedObject(contextName=SomeScope)))
```
And subsequent accessing UnscopedObject without any scope will return the same object from "SomeScope".


> Are you asking for some changes in our codebase or some help to find a smooth resolution ?

My main question is, whether this kind of behavior is expected on Kodein? I think it's one of the case of misconfigured binding that should crash earlier so there should be some changes in Kodein implementation to throw error for this behavior.

> all 3 cases failed

Do you mean all ex1, ex2, and ex3 is printed successfully? Because when i run it the first assertion failing as expected and ex1 is printed to the console, while the anything after ex2 is not printed because it didn't throw anything.

Here is my output when running it:
```
org.kodein.di.Kodein$NotFoundException: No binding found for bind<ScopedObject>() with ? { ? }
Available bindings for this type:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
Registered in this Kodein container:
        bind<ScopedObject>() with scoped(SessionScope).singleton { ScopedObject }
        bind<UnscopedObject>() with singleton { UnscopedObject }

Successfully retreived org.kodein.di.sandbox.scope.UnscopedObject@4c203ea1: Scope
Exception in thread "main" java.lang.AssertionError: Accessing unscoped object from scope with scoped deps should fail. Expected an exception to be thrown, but was completed successfully.
	at org.junit.Assert.fail(Assert.java:88)
	at kotlin.test.junit.JUnitAsserter.fail(JUnitSupport.kt:56)
	at kotlin.test.AssertionsKt__AssertionsKt.checkResultIsFailure(Assertions.kt:134)
	at kotlin.test.AssertionsKt.checkResultIsFailure(Unknown Source)
	at org.kodein.di.sandbox.scope.ScopingTestKt.main(ScopingTest.kt:36)
	at org.kodein.di.sandbox.scope.ScopingTestKt.main(ScopingTest.kt)
```

Also i use following artifact for the dependencies if that relevant:
```
implementation org.kodein.di:kodein-di-generic-jvm:6.3.3
implementation org.kodein.di:kodein-di-conf-jvm:6.3.3
```

**Comment by romainbsl** [comment]
Ok, I get it, its clearer with your new example. I agree that there is something wrong, but not sure what exactly for the moment.

Indeed, the `UnscopedObject` will still be the first instance created, it's a singleton. So this doesn't disturb me at all, and I think this is what I would expect from Kodein. As the object is not scoped, it will be available in every cases.

But, we still can consider adding some check to avoid such misconfiguration. However, we'll have to add it to the roadmap and discuss about it first. Unfortunately if we agree on the implementation, this couldn't be done before some time. I will create an issue for that (#252).

However, even the implementation of a misconfiguration is missing, and if you really want to upgrade, I suggest you to change your bindings, to avoid such a case. Why not scoping the `UnscopedObject` as you will always need it in a scope ? Or, if it's a test case, ignore it until we provide a solution.

> Do you mean all ex1, ex2, and ex3 is printed successfully?
No, sorry, in fact I had some bad imports making the test successful...
