### ISSUE TITLE
Is it possible to change Singleton (or any parameter) values after the initial Kodein instantiation?

### ISSUE THREAD

**Issue by JimVanG** [Kodein-Framework/Kodein-DI#247]
I’d really like to be able to change the value of my HTTP clients baseUrl value, because it can be set dynamically while using the application. I’m having trouble finding a way to change parameter values dynamically.

I’ve looked into `Multiton` binding as it seemed like a type of Singleton-Factory that would allow the arguments to be changed. But I had no luck with that.

**Here is my Api singleton:**
```Kotlin
interface LoginApi {

    @POST("Account/Login")
    @FormUrlEncoded
    fun login(
        @Field("username") username: String,
        @Field("password") password: String,
        @Field("sessionType") sessionType: String
    ): Call<BaseApiResponse<Login>>

    @GET("Account/Logout")
    fun logout(
        @Query("token") token: String
    ): Call<BaseApiResponse<Any>>

    companion object {
        operator fun invoke(
            baseUrl: String,
            cache: Cache
        ): LoginApi {

            val okHttpClient = OkHttpClient.Builder()
                .cache(cache)
                .readTimeout(60, TimeUnit.SECONDS)
                .connectTimeout(60, TimeUnit.SECONDS)
                .build()

            return Retrofit.Builder()
                .client(okHttpClient)
                .baseUrl(baseUrl)
                .addConverterFactory(JacksonConverterFactory.create())
                .build()
                .create(LoginApi::class.java)
        }
    }
}
```

**Dependency Declaration with muliton (doesn’t work):**
```Kotlin 
     import(androidXModule(this@MyApplication))

        bind<Any>() with multiton { baseUrl: String, applicationContext: Context ->
            createLoginApi(baseUrl, applicationContext)
            LoginApi(
                BuildConfig.BASE_URL,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }

        bind<LoginDataSource>() with singleton { LoginService(instance()) }
        bind<LoginRepository>() with singleton { LoginRepositoryImpl(instance()) }
        bind() from singleton { LoginViewModelFactory(instance()) }
        bind() from singleton { LoginViewModel(instance()) }
    }
```

**Dependency Declaration with no multiton (works):**
```Kotlin 
    import(androidXModule(this@MyApplication))

        bind() from singleton {
            LoginApi(
                BuildConfig.BASE_URL,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }

        bind<LoginDataSource>() with singleton { LoginService(instance()) }
        bind<LoginRepository>() with singleton { LoginRepositoryImpl(instance()) }
        bind() from singleton { LoginViewModelFactory(instance()) }
        bind() from singleton { LoginViewModel(instance()) }
    }
```

**Version**
```Groovy
    implementation 'org.kodein.di:kodein-di-generic-jvm:6.3.2'
    implementation "org.kodein.di:kodein-di-framework-android-x:6.3.2”
```
Let me know if you need any other information. This is pretty very simple example -- I’d just like to be able to change parameter values dynamically. If that isn’t possible, then is there any way that would allow me to do such a thing

Thank you in advance!

**Comment by romainbsl** [comment]
Hello,

We don't recommend to change the kodein instance at runtime. In fact, it's not possible out of the box.

You are on the right tracks, `Multiton` can be your solution, but binding `Any` is not a good idea. That's certainly why it's not working.

You need to bind `LoginApi`, as in your working example, `bind() from ...` binds the return type of the lambda, thus `LoginApi`.

Be careful, in 6.5 we will depreciate mutli arguments factories/multiton, we recommend to use `data classes`, giving you something like:

```kotlin
data class LoginArguments(val baseUrl: String, val applicationContext: Context)

bind<LoginApi>() with multiton { args: LoginArguments ->
            createLoginApi(args.baseUrl, args.applicationContext)
            LoginApi(
                BuildConfig.BASE_URL,
                Cache(args.applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }
```

tell me if that helps.

**Comment by JimVanG** [comment]
Thanks for the reply

Here’s the new `Multiton` implementation:
```Kotlin
        bind<LoginApi>() with multiton { baseUrl: String, applicationContext: Context ->
            createLoginApi(baseUrl, applicationContext)
            LoginApi(
                baseUrl,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }
```

**createLoginApi() function**: (pretty much same thing in `Multiton` block)
```Kotlin
    private fun createLoginApi(baseUrl: String, applicationContext: Context) =
        LoginApi(
            baseUrl,
            Cache(applicationContext.cacheDir, 10 * 1024 * 102)
     )
```

**Error when using Multiton:**
>java.lang.ClassCastException: kotlin.Unit cannot be cast to org.kodein.di.Multi2  
        at com.myapp$kodein$1$$special$$inlined$multiton$3.invoke(Unknown Source:2)
        at org.kodein.di.bindings.Multiton$getFactory$1$1$1.invoke(standardBindings.kt:66)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Multiton$getFactory$1$1.invoke(standardBindings.kt:66)
        at org.kodein.di.bindings.Multiton$getFactory$1$1.invoke(standardBindings.kt:37)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Multiton$getFactory$1.invoke(standardBindings.kt:66)

Let me know if you need any other information - I haven’t changed anything else.

Also:
>Be careful, in 6.5 we will depreciate mutli arguments factories/multiton, we recommend to use data classes...

This sound very nice! Looking forward!

**Comment by romainbsl** [comment]
> This sound very nice! Looking forward!

You can now use a data class, no need to wait until 6.5. In 6.5 the ability to use mutliple argument in multiton will be deprecated. So you must in data class from now.

How do you try to inject your multiton ?

**Comment by JimVanG** [comment]
Alright so i just changed to use the `data class` version of the `Multiton`. I’m now receiving a different error, the error that I originally faced when initially trying to use the `multiton` extension.

**Multiton w/ data class**
```Kotlin
        bind<LoginApi>() with multiton { args: LoginArguments ->
            createLoginApi(args.baseUrl, applicationContext)
            LoginApi(
                args.baseUrl,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }

// The Datasource is then bound with the LoginApi supplied using the `instance()` function
        bind<LoginDataSource>() with singleton { LoginService(instance()) }

```
**Error:**
```
org.kodein.di.Kodein$NotFoundException: No binding found for bind<CooltrackLoginApi>() with ?<FragmentActivity>().? { ? }
Available bindings for this type:
            //  
            // notice how it suggests doing this, when already is registered in the Kodien Container
            //
            bind<CooltrackLoginApi>() with multiton { LoginArguments -> CooltrackLoginApi }
Registered in this Kodein container:
            bind<CooltrackLoginApi>() with multiton { LoginArguments -> CooltrackLoginApi }
            bind<LoginDataSource>() with singleton { LoginService }
            bind<LoginRepository>() with singleton { LoginRepositoryImpl }
            bind<LoginViewModelFactory>() with singleton { LoginViewModelFactory }
            bind<LoginViewModel>() with singleton { LoginViewModel }
```

>How do you try to inject your multiton ?
Well I guess it’s injected via the `LoginService` constructor: `class LoginService(private val api: CooltrackLoginApi) : LoginDataSource`. 

When it comes to retrieving the dependencies (i.e. `LoginViewModel`) I use retrieval, with the `KodeinAware` interface.

**Comment by JimVanG** [comment]
I’m doing everything you previously suggested in a similar issue: https://github.com/Kodein-Framework/Kodein-DI/issues/178#issuecomment-460621917

**Comment by JimVanG** [comment]
Thanks for all the quick replies. 

(If you haven’t noticed) DI is all new to me... 

I’m curious how I would use the `LoginDataSource` the way suggested, as it’s being passed as an argument to the `LoginReposity`.

Here is my current `Kodein` declaration implementation:
```Kotlin
    override val kodein = Kodein.lazy {
        // must import Application class. NOTE: must use `androidXModule` - we're using AndroidX.
        import(androidXModule(this@CoolTrackApplication))
        registerContextTranslator { f: Fragment -> f.activity }

        bind<CooltrackLoginApi>() with multiton { args: LoginArguments ->
            createLoginApi(args.baseUrl, applicationContext)
            CooltrackLoginApi(
                args.baseUrl,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }

//        bind<LoginDataSource>() with singleton { LoginService(instance()) }
        bind<LoginDataSource>() with multiton { args: LoginArguments -> LoginService(instance(arg = args)) }
        bind<LoginRepository>() with singleton { LoginRepositoryImpl(instance()) }
        bind() from singleton { LoginViewModelFactory(instance()) }
        bind() from singleton { LoginViewModel(instance()) }
    }
```

**LoginFragment**
```Kotlin
class LoginFragment : Fragment(R.layout.fragment_login), KodeinAware {

    override val kodein by closestKodein()
    val viewModel: LoginViewModel by lazy { on(requireActivity()).direct.instance<LoginViewModel>() }
...
```

I’m curious where this: `val dataSource: LoginDataSource by kodein.instance(arg = LoginArguments("/path", context))` would come into play.


Thanks again

**Comment by JimVanG** [comment]
Ok i *think* understand after messing around a bit and have it working with the `muliton`.

Here’s what I’ve changed in the Kodein declaration block:
```Kotlin
        bind<LoginApi>() with multiton { args: LoginArguments ->
            createLoginApi(args.baseUrl, applicationContext)
            LoginApi(
                args.baseUrl,
                Cache(applicationContext.cacheDir, 10 * 1024 * 102)
            )
        }

        bind<LoginDataSource>() with multiton { args: LoginArguments -> LoginService(instance(arg = args)) }
        val loginDataSource: LoginDataSource by instance(arg = LoginArguments(BuildConfig.BASE_URL))
        // Supply the multiton loginDataSource 
        bind<LoginRepository>() with singleton { LoginRepositoryImpl(loginDataSource) }
````

Thank you!

**Comment by romainbsl** [comment]
that should work, but you're code is not entirely decoupled.

```kotlin
bind<LoginApi>() with multiton { args: LoginArguments ->
    createLoginApi(args.baseUrl, applicationContext)
    LoginApi(
        args.baseUrl,
        Cache(applicationContext.cacheDir, 10 * 1024 * 102)
    )
}

bind<LoginDataSource>() with multiton { args: LoginArguments -> LoginService(instance(arg = args)) }

bind<LoginRepository>() with singleton { 
    LoginRepositoryImpl(instance(arg = LoginArguments(BuildConfig.BASE_URL)))
}
```

When retrieving the instance of `LoginRepository` Kodein will:
1. Look for a binding for `LoginRepository`
    - that's the singleton with `LoginRepositoryImpl` waiting for a `LoginDataSource`
2. Look for `LoginDataSource` binding that need a parameter `args: LoginArguments`
    - that's the multiton returning a `LoginService` with `args: LoginArguments`as parameter
        - this is the job of `instance(arg = LoginArguments(BuildConfig.BASE_URL))`

Hope this is clear enough.

**Comment by JimVanG** [comment]
Again thanks for all the help. Really appreciate.

>but you're code is not entirely decoupled

How could I decouple this any further...? If you have time to help. Thank you!
