### ISSUE TITLE
ERROR: Failed to resolve: org.kodein.di:kodein-di-erased:6.5.0

### ISSUE THREAD

**Issue by desgraci** [Kodein-Framework/Kodein-DI#248]
Following his instructions:

`https://github.com/Kodein-Framework/Kodein-DI/blob/master/doc/core.adoc`

My main  gradle contains on the `buildscript` and the `allprojects` this block:
```
repositories {
        google()
        jcenter()
    }
```
Invalidated, cleaned, deleting the .gradle, etc, cannot be found
Also tried adding:
`maven(url = "https://dl.bintray.com/kodein-framework/Kodein-Internal-Gradle")`
and
`classpath("org.kodein.internal.gradle:kodein-internal-gradle-settings:2.9.6")` from this doc:
`https://github.com/Kodein-Framework/Kodein-DI/blob/master/settings.gradle.kts`
without any luck.

**Comment by desgraci** [comment]
Duplicated of: https://github.com/Kodein-Framework/Kodein-DI/issues/243

**Comment by romainbsl** [comment]
version `6.4.0` has been released with kotlin `1.3.50`compat
