### ISSUE TITLE
Singleton binding creates multiple instances

### ISSUE THREAD

**Issue by igorwojda** [Kodein-Framework/Kodein-DI#250]
Looking at docs this should not happen. It looks like a bug, but I need confirmation  🤔
Attaching sample Android Studio project (Kodein `6.4.0`)
[KodeinTest.zip](https://github.com/Kodein-Framework/Kodein-DI/files/3653350/KodeinTest.zip)

Take a look at `BaseApplication.kt` and `MainActivity.kt` files. The issue is that `FeatureEventBus` instance bonded as a singleton, but it is created multiple times 

Log:
![image](https://user-images.githubusercontent.com/530122/65615531-6b111d80-dfb1-11e9-8026-89741ed4a89c.png)

**Comment by romainbsl** [comment]
In fact, in `InjectionActivity` you have:

```kotlin
final override val kodein: Kodein by retainedKodein {
    extend(parentKodein, copy = Copy.All)
}
```

the `extend` function will create a new instance of Kodein, depending on the `copy` argument you'll have new instances or not. By using the `Copy.All` Kodein will copy the binding without the references.

So by doing the following code, your problem will be solved.

```kotlin
final override val kodein: Kodein by retainedKodein {
    extend(parentKodein)
}
```

Maybe the documentation needs to be improved. What part could be confusing ?

**Comment by igorwojda** [comment]
Thanks exactly what I needed.

Docs (`Activity retained sub Kodein` section) is indeed a bit confusing - the way I initially understood it was that I have to copy these modules, otherwise they will not be available.

I think we cna clarify it a bit by describing `Copy.All` behavior in more detail. Let me know what you think:
https://github.com/Kodein-Framework/Kodein-DI/pull/251

**Comment by romainbsl** [comment]
merged
