### ISSUE TITLE
Inconsistent base class injection behavior

### ISSUE THREAD

**Issue by masc3d** [Kodein-Framework/Kodein-DI#254]
while migrating from 4.x to 6.4 I found that injecting base classes does not work as it used to and depending how injection occurs, it's also inconsistent.

what is the preferred way to handle / resolve class hierarchy instances as outlined below for 6.x?

```
class KodeinSandbox {
    open class Resource1
    open class Resource2 : Resource1()

    val kodein = Kodein {
        bind<Resource1>() with singleton { Resource1() }
        bind<Resource2>() with singleton { Resource2() }
    }

    val instanceLevelResource1: Resource1 by kodein.instance()

    @Test
    fun testInjection() {
        val localResource1: Resource1 by kodein.instance()

        // Behaves as expected (as of 4.x) delivers instance explicitly bound to base-class type
        println(localResource1)

        // Throws due to ambiguity
        println(instanceLevelResource1)
    }
}
```

**Comment by masc3d** [comment]
`5.3.0` is not affected and behaves as expected

**Comment by romainbsl** [comment]
Thank you for the report and the reproducible case. I'll be looking into it ASAP, it seems we have a bug here.

**Comment by masc3d** [comment]
we have another use case where a base-class instance is overridden by another module / import, which also works in `5.3.0` but not in `6.4.0`. suppose this is related..

**Comment by romainbsl** [comment]
`6.4.1` fix the bug, I hope this will help. Tell me if you still have issues.
(publishing on jcenter may take some minutes)

**Comment by masc3d** [comment]
thank you @romainbsl for taking care of this so quickly. much appreciated!

**Comment by masc3d** [comment]
confirming, `6.4.1` fixes this, as well as the overriding issue I presumed was related.
