### ISSUE TITLE
JUnit testing - question

### ISSUE THREAD

**Issue by igorwojda** [Kodein-Framework/Kodein-DI#256]
Let's assume I have a class that has a primary constructor with single parameter (this is required by Android)
```
class PaymentViewModel(application: Application) : AndroidViewModel(application) {
}
```

...and now I need to define dependencies using `instance()` delegate (I can't add more parameters to the primary constructor)

```
class PaymentViewModel(application: Application) : AndroidViewModel(application) {
     private val featureEventBus: FeatureEventBus by instance()
}
```

The question is how to test it?
```
@RunWith(MockitoJUnitRunner.StrictStubs::class)
class PaymentViewModelTest {

   @Mock
   private lateinit var mockApplication: Application

   @Mock
   private lateinit var mockFeatureEventBus: FeatureEventBus

   private lateinit var cut: PaymentViewModel

   @Before
   fun setUp() {
        // I want FeatureEventBus property delegate to retrieve
        // mockFeatureEventBus instance
		cut = PaymentViewModel(mockApplication)
    }
}



```

**Comment by romainbsl** [comment]
to be able to write `by instance()` I assume that your class `PaymentViewModel` is `KodeinAware`. If not, it should be, right ?

But in that case you need to implement the `kodein` property, like:
```kotlin
class PaymentViewModel(application: Application) : AndroidViewModel(application), KodeinAware {
    override val kodein: Kodein
        get() = TODO("not implemented") //To change initializer of created properties use File | Settings | File Templates.
    private val featureEventBus: FeatureEventBus by instance()
}
```

If I'm right there is an extension function on `Application` giving you the closest kodein container named `kodein()` or `closestKodein()`, giving you:
```kotlin
class PaymentViewModel(application: Application) : AndroidViewModel(application), KodeinAware {
    override val kodein: Kodein = application.kodein() // or application.closestKodein()
    private val featureEventBus: FeatureEventBus by instance()
}
```

Then you'll have to mock it.

**Comment by igorwojda** [comment]
Yes `PaymentViewModel` is `KodeinAware`.

It was a bit tricky but I figured it out. I had to define a custom extension that takes application as a param (I was not able to find another way to retrieve these "mocking bindings" from kodein module defined in test class).

I had to define additional extension that takes application (or rather application mock in this example) a a argument:
`fun AndroidViewModel.kodein(application: Application) = org.kodein.di.android.kodein(application)`, so I can mock `application.kodein` call (in `PaymentViewModelTest` class) Here is complete code:
```
class PaymentViewModel(application: Application) : AndroidViewModel(application), KodeinAware {

    override val kodeinContext = kcontext<ViewModel>(this)
    override val kodein by kodein(application) //this was not possible before

	private val featureEventBus: FeatureEventBus by instance()
}
```

In the test class I had to create a custom class `KodeinAwareApplication`, so I can mock kodein module call (due to module setup in our project our custom Application class that is Kodein Aware is not available in this particular module).
```
@RunWith(MockitoJUnitRunner.StrictStubs::class)
class PaymentViewModelTest {

   abstract class KodeinAwareApplication : Application(), KodeinAware

   @Mock
   private lateinit var mockApplication: KodeinAwareApplication

   @Mock
   private lateinit var mockFeatureEventBus: FeatureEventBus

   private lateinit var cut: PaymentViewModel

   @Before
   fun setUp() {
        val testModule = Kodein.Module("testModule") {
            bind() from singleton { mockFeatureEventBus }
        }

        val kodein = Kodein.lazy {
            import(testModule)
        }

        given { mockApplication.kodein }.willReturn(kodein)

		cut = PaymentViewModel(mockApplication)
    }
}

```

**Final thoughts:**
I think that we should update the signature of `kodein` extension defined in [closest.kt](https://github.com/Kodein-Framework/Kodein-DI/blob/master/framework/android/kodein-di-framework-android-x/src/main/java/org/kodein/di/android/x/closest.kt)

from 
```
fun AndroidViewModel.kodein() 
   = kodein(getApplication<Application>())
```
to 
```
fun AndroidViewModel.kodein(application: Application? = null) 
   = kodein(application ?: getApplication<Application>())
```

The will allow to easily pass mock of the `Application` into any class that is a child of `AndroidViewModel` (like in the above example).

@romainbsl Does it feel like proper way of doing it?

**Comment by romainbsl** [comment]
I wonder why this was not working without your extension:
```kotlin
override val kodein by kodein()
```

As we have an extension on `AndroidViewModel`
```kotlin
fun AndroidViewModel.kodein() = kodein(getApplication<Application>())
```

As the signature of `AndroidViewModel` constructor is:
```java
public AndroidViewModel(@NonNull Application application) {
        mApplication = application;
    }
```
and the function `getApplication<Application>()`will do `return (T) mApplication;`.

Your mocking model should work without adding an extra extension function ? 
What I am missing ?

Otherwise, I'm not against evolving the signature but I would like to fully understand.

**Comment by igorwojda** [comment]
It looks like the extension is not needed indeed, but there is still a wired behavior. I think it may be issue related to Kotlin compiler and name resolution (delegate name `kodein` conflicts with the variable name `kodein`)

This code...
```
open class InjectionViewModel(
    application: Application
) : AndroidViewModel(application),
    KodeinAware {
    override val kodeinContext = kcontext<ViewModel>(this)
    override val kodein by kodein(application)
```

...results in error
```
> Task :feature_base:compileDebugKotlin FAILED
e: /Users/igor/StudioProjects/one-pay-fx/android/feature_base/src/main/java/com/pagofx/feature/base/presentation/base/InjectionViewModel.kt: (16, 28): Expression 'kodein' cannot be invoked as a function. The function 'invoke()' is not found
```

However, if we use fully qualified import `org.kodein.di.android.kodein` code works perfectly
```
open class InjectionViewModel(
    application: Application
) : AndroidViewModel(application),
    KodeinAware {
    override val kodeinContext = kcontext<ViewModel>(this)
    override val kodein by org.kodein.di.android.kodein(application)
```

**Comment by igorwojda** [comment]
It looks like manually adding import (`import org.kodein.di.android.kodein`)
makes the first example compile.

There is wired kotlin plugin behavior where it cannot solve all the imports. I think this may be related. 
https://youtrack.jetbrains.com/issue/KT-33318

**Comment by romainbsl** [comment]
that why we had to bring back the good `closestKodein` method, thus you don't have to specify the whole path.

**Comment by igorwojda** [comment]
adding import manually works, so I guess after Kotlin plugin will be fixed this will work properly without `closestKodein `

**Comment by romainbsl** [comment]
Yes but we bring it back for those that don't want to add the import manually :)
