### ISSUE TITLE
Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6

### ISSUE THREAD

**Issue by muliyul** [Kodein-Framework/Kodein-DI#257]
![image](https://user-images.githubusercontent.com/8338082/66768943-8094ab80-eebc-11e9-807f-3cfa7493aa37.png)

Ktor project. Generated using the IDE.

**Comment by romainbsl** [comment]
Hi, 

Since version `6.3.0` we have moved to Gradle '5', thus you need to target at least JDK 1.8.

**Comment by muliyul** [comment]
The project is scaffolded using ktor's official intellij plugin project (https://start.ktor.io/). Is this stated in the docs somewhere?

**Comment by romainbsl** [comment]
it's only visible in the CHANGELOG.md : https://github.com/Kodein-Framework/Kodein-DI/blob/master/CHANGELOG.md. I've created an issue to update the core documentation.

You can find samples here https://github.com/Kodein-Framework/Kodein-Samples with a specific point on Ktor here https://github.com/Kodein-Framework/Kodein-Samples/tree/master/di/standalone/ktor.

Targeting a specific JVM with Gradle can be done with the following snippet (Gradle Kotlin DSL):
```
tasks.withType<KotlinCompile> {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

Plus did you see that we have a module for Ktor on Kodein ? https://kodein.org/Kodein-DI/?6.4/ktor

**Comment by muliyul** [comment]
> Targeting a specific JVM with Gradle can be done with the following snippet (Gradle Kotlin DSL):

How does that look on a Groovy one?

> Plus did you see that we have a module for Ktor on Kodein ?

I'm using it

**Comment by cleemansen** [comment]
For **Maven** projects see [kotlin documentation](https://kotlinlang.org/docs/reference/using-maven.html#attributes-specific-for-jvm) for setting the `jvmTarget` option.
