### ISSUE TITLE
Add the ability to retrieve all the instances without non initialised lazy singletons

### ISSUE THREAD

**Issue by Koriit** [Kodein-Framework/Kodein-DI#266]
Kodein-DI version 6.4.1

Hi,
I have a use case where I want to retrieve all `AutoCloseable` from the container, however, without creating lazy instances which haven't been created yet.

My current code looks like it:
```kotlin
direct.allInstances<AutoCloseable>().forEach {
  it.close()
} 
```
The problem here is that it triggers creation of lazy instances, here, only to close them...

If there is a way to do it with current API then I would ask for help. If not then, please, consider it as feature request.

**Comment by romainbsl** [comment]
Hi,

Indeed, there is no option to retrieve all the already initialised instances, thus avoid lazy init on the other.
However, if you can group your instances with tags this would only trigger the one you're looking for. 

This could be taken into account as a feature request, but would take several weeks to enter into the pipeline.

**Comment by Koriit** [comment]
Well, tags don't seem to solve my use case, as I want all and only instances which were initialised.

I am in no hurry with this as what I'm trying to do is just a [cleanup](https://github.com/Koriit/kodein-application/blob/23734455b6f7db011f79b1c7be2ec55bdd99d43e/src/main/kotlin/korrit/kotlin/kodein/application/Application.kt#L42) on application shutdown. Eventual creation of instances is no big thing.

Do I need to do something to make it into official feature request?

**Comment by romainbsl** [comment]
Hi, no need, we will use this issue to follow the possible feature request.

**Comment by romainbsl** [comment]
After some thinking we won't do this, as it has no direct value for the library.

Plus, you could managed your issue by using [Scopes](https://kodein.org/Kodein-DI/?6.5/core#_using_the_environment).

**Comment by Koriit** [comment]
@romainbsl I disagree. I believe there is value in this and I have 2 issues with using Scopes here:

* Scoping your definitions introduce additional scope-induced complexity to your definitions
* Built-in scopes require values to implement ScopeCloseable ([src](https://github.com/Kodein-Framework/Kodein-DI/blob/94a4ba14aecfec88a5401386bd8394295a09e3c5/kodein-di-core/src/commonMain/kotlin/org/kodein/di/bindings/scopes.kt#L90), [doc](https://github.com/Kodein-Framework/Kodein-DI/blame/master/doc/core.adoc#L1612))

Second problem can be resolved by creating my own Scope but yet again this introduces additional complexity.

My use case is just cleaning up on application close. I think this is a good practice(...) which library such as Kodein-DI would do good in helping spreading. It feels unreasonable to introduce "Scopes" to my application _just_ to do proper cleanup. :(

It can be generalised to retrieving initialised instances. I think there should be more use cases for this in the wild.

I ask you to reconsider.
