### ISSUE TITLE
Is there a way to make the Angular DI container interact with Kodein/JS?

### ISSUE THREAD

**Issue by lamba92** [Kodein-Framework/Kodein-DI#267]
I am building an MPP project that targets JS and Android/JVM.

While the android app works just fine (it uses Kotlin, duh!), I am having a little trouble finding a clean solution for the web client which is angular 8 based.

The ideal solution would be some sort of bind translation from Kodein to the Angular container. 

Has anyone already tackled this problem, if so which solution worked for you?

**Comment by romainbsl** [comment]
I, we didn't try such a thing with Angular. Maybe you could ask on the `kodein` Slack channel, see if everyone as ever tried this.
