### ISSUE TITLE
Kotlin 1.3.60 Update 

### ISSUE THREAD

**Issue by Cilestal** [Kodein-Framework/Kodein-DI#268]
Release a new Version/Beta with Kotlin Version 1.3.60

Kotlin Native needs the same ABI Versions.

**Comment by romainbsl** [comment]
A version is available on the dev channel on the repository: https://dl.bintray.com/kodein-framework/kodein-dev

Try to use the version `6.5.0-dev-660`

It will be released ASAP.

**Comment by romainbsl** [comment]
'6.5.0` has been published
