### ISSUE TITLE
Cannot build in XCode a Kotlin/Native project with a KodeIN 6.5.0-dev-663

### ISSUE THREAD

**Issue by abrivle** [Kodein-Framework/Kodein-DI#269]
We have a Kotlin multiplatform project. When I try to compile the iOS code in XCode I get the following errors:

<img width="922" alt="Screen Shot 2019-12-03 at 18 55 37" src="https://user-images.githubusercontent.com/34343614/70082057-ac115800-161a-11ea-88c3-6ef2c62d0ae7.png">

**Errors occur because "Multi argument factories are confusing..." is a multi-line string with "\n". Can you remove "\n" from all messages, please?**

**Comment by romainbsl** [comment]
Hello,

Are you using Multi-arguments factories in your code ?
Since `6.5.0-dev+`, we recommend not to use them, but using `data class` instead, as one argument.

**Comment by romainbsl** [comment]
That's weird because those are deprecation messages from the new version `6.5.0`.

By the way `6.5.0` is out and stable.

**Comment by MitsuraIvan** [comment]
@romainbsl Hi, im the dev from same team, we used to have multiple params(2 params) at one place, which we replaced with data class wrapper after error starts to pop, but problem still remains, tried to clear android studio/xcode/ios temp data etc but thing is still there :(

we will try 6.5.0 and respond here with more info, as for today we were in 6.5.0-dev-663

**Comment by romainbsl** [comment]
Hi, 
I'm working on a patch, I way have an idea on whats going on. 
I'll keep you informed.

**Comment by romainbsl** [comment]
Hi,

KotlinConf is now over, thus we can go back to our projects :)

I just published a `6.5.1` with a fix on depreciation messages that has `\n` in it, hope this will fix the issue.

**Comment by romainbsl** [comment]
@abrivle @MitsuraIvan is the issue solved ?

**Comment by MitsuraIvan** [comment]
@romainbsl oh I thought I answered, sorry, my bad. Yes, issue solved, thank you very much!
