### ISSUE TITLE
Please include sources with Android artifacts

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/Kodein-DI#279]
Following up from 2017 (https://github.com/Kodein-Framework/Kodein-DI/issues/62) can we please get sources included?

**Comment by eygraber** [comment]
To give more context, when trying to debug (stepping through or settings breakpoints) I am being taken to the .class file that only shows signatures. This doesn't happen with other libraries.

**Comment by romainbsl** [comment]
Hi @eygraber. When you say that this doestn't happen with other libraries, does it include kodein's ones ?

> FYI we are working onto a huge refactoring for `6.6` and 7.x` thus this will be handle later on.

**Comment by eygraber** [comment]
It happens with anything Kodein related. It doesn't happen with other libraries that I use.

**Comment by romainbsl** [comment]
This should be fixed in **v7.0**.
