### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by sagarnayak** [Kodein-Framework/Kodein-DI#284]
How to use kodein to inject dependencies from the application class (kodeinaware) to broadcast receiver ?

**Comment by romainbsl** [comment]
Hello.

You have multiple options:
- constructor implementation, passing the kodein container as a parameter (depending on where you initialize the broadcast receiver):
```kotlin
class TestBroadcastReceiver(override val kodein: Kodein) : BroadcastReceiver(), KodeinAware {
    override fun onReceive(context: Context?, intent: Intent?) { }
}
```
- either use `lateinit`, cn be more error prone if the context is null:
```kotlin
class TestBroadcastReceiver : BroadcastReceiver(), KodeinAware {
    override lateinit var kodein: Kodein

    override fun onReceive(context: Context?, intent: Intent?) {
        kodein = (context?.applicationContext as KodeinAware).kodein
    }
}
```

**Comment by sagarnayak** [comment]
I used it like this -

    class PhoneState : BroadcastReceiver(), KodeinAware {

    override lateinit var kodein: Kodein

    override fun onReceive(context: Context?, intent: Intent?) {

        context?.let {
            kodein = (it.applicationContext as ApplicationClass).kodein
            val logUtil: LogUtil by instance()
            logUtil.logV("success")
        }
    ......

Is it the correct approach?

**Comment by romainbsl** [comment]
Yes, this is a valid approach, however, if in any case, your context is null, this will fail your application.

If you want to access your `LogUtil` class outside of the `let` block, you can, by doing:
```
class PhoneState : BroadcastReceiver(), KodeinAware {

override lateinit var kodein: Kodein
val logUtil: LogUtil by instance()

override fun onReceive(context: Context?, intent: Intent?) {
    context?.let {
        kodein = (it.applicationContext as ApplicationClass).kodein
        logUtil.logV("success")
    }
}
```

As Kodein is initialized lazily, this won't be a problem, unless the context is null.

**Comment by sagarnayak** [comment]
thanks for your suggestions. I have now declared the logUtil globally as you suggested.

**Comment by shawn-gosam** [comment]
Is there any workaround if ever the context is null? I implemented it in a broadcast receiver where I'm accessing my repository class where it should work when the app is open nor close. It works fine if the app is open, but not when closed, though I understand why it's happening, I'm hoping if there is a workaround even if the app is close, so that I can still access the repository class.

**Comment by superdiazzz** [comment]
how to use with Kodein 7? i can not find `ApplicationClass` so can't casting
