### ISSUE TITLE
cyclic/loop dependency when using lazy params

### ISSUE THREAD

**Issue by v-mas** [Kodein-Framework/Kodein-DI#285]
Hello
I have MVP structure. I have tried to pass presenter to view and view to presenter. To break the cycle I used `lazy initializer` - it works in dagger. Now i try to use kodein and I'm unable to make it work and I do not know why it shows me dependency recursion.

here is the example code of my problem:
```
class ExampleTest {
    @Test
    fun `kodein dependenccy loop test`() {
        val kodein = Kodein {
            bind() from singleton { View(lazy { instance<Presenter>() }) }
            bind() from singleton { Presenter(instance()) }
        }

        val view = kodein.direct.instance<View>()
        view.invoke()
    }
}

class View(private val presenter: Lazy<Presenter>) {
    fun invoke() {
        presenter.value.invoke()
    }

    fun back() {
        //nop.
    }
}

class Presenter(private val view: View) {
    fun invoke() {
        view.back()
    }
}
```
with gradle dependencies:
```
    def kodeinVersion = '6.5.1'
    implementation "org.kodein.di:kodein-di-framework-android-x:$kodeinVersion"
    implementation "org.kodein.di:kodein-di-erased:$kodeinVersion"
```

and this test output:
```
org.kodein.di.Kodein$DependencyLoopException: Dependency recursion:
     bind<View>()
    ╔╩>bind<Presenter>()
    ║  ╚>bind<View>()
    ╚════╝
```

how is that lazy initializer is still making it throw that exception?

**Comment by romainbsl** [comment]
Hello, 

When you use `kodein.direct`, laziness can be lost. Your MVP should be lazily implemented. Plus, to make your life simple, you could use the `KodeinAware` interface like:

```kotlin
import org.kodein.di.Kodein
import org.kodein.di.KodeinAware
import org.kodein.di.generic.bind
import org.kodein.di.generic.instance
import org.kodein.di.generic.singleton

fun main(){
    val kodeinContainer = Kodein {
        bind() from singleton { View(kodein) }
        bind() from singleton { Presenter(kodein) }
    }

    val view: View by kodeinContainer.instance()
    view.invoke()
}

class View(override val kodein: Kodein): KodeinAware {
    private val presenter: Presenter by instance()

    fun invoke() {
        presenter.invoke()
    }

    fun back(message: String) {
        println("YUP: $message")
    }
}

class Presenter(override val kodein: Kodein): KodeinAware {
    private val view: View by instance()
    fun invoke() {
        view.back("It's alive!")
    }
}
// Prints >>> YUP: It's alive!
```

**Comment by romainbsl** [comment]
Note that there are features dedicated to android with https://kodein.org/Kodein-DI/index.html?latest/android#_using_lateinit

**Comment by v-mas** [comment]
I was trying to make my classes pure, without references to injection engine. It means that there is no easy way to achive this and i need to make workarounds

**Comment by romainbsl** [comment]
Ok, this was just a suggestion. 
But, there is always a way. Here we provide an example of getting Kodein independent:
 https://kodein.org/Kodein-DI/index.html?latest/android#_being_kodein_independant

**Comment by v-mas** [comment]
Thanks. I will look at your suggestion and try things to best match my needs
