### ISSUE TITLE
Achieve binds in Swift

### ISSUE THREAD

**Issue by BulatMukhutdin** [Kodein-Framework/Kodein-DI#290]
I am developing multiplatform app for android and iOS. In common module I have 
```
object Di {

    val kodein = Kodein.lazy {

        bind<Domain>() with provider {
            Interactor(provideSqlDriver())
        }
    }
}

```

How can I retrieve given object in Swift code?

**Comment by romainbsl** [comment]
Actually you can't directly retrieve Kodein binding in Swift. We are working on it.
In the meantime, you can create a facade in your common code to access your instances like:

```kotlin
object Di {
    val kodein = Kodein.lazy {
        bind<Domain>() with provider {
            Interactor(provideSqlDriver())
        }
    }

  fun getProviderDomain() = kodein.direct.instance<Domain>()
}
```

and use it from Swift like:
```swift
Di.init().getProviderDomain()
```

**Comment by BulatMukhutdin** [comment]
I see, thanks.

Do you have any timeline when you plan to implement it?

**Comment by romainbsl** [comment]
We are planning it for the coming weeks, but no ETA at the moment.

**Comment by toadfrogson** [comment]
@romainbsl 
I was wondering if Kodein may have any updates regarding this issue?
Is there a way to retrieve Kodein bindings in Swift?
