### ISSUE TITLE
Crash on iOS with modules defined as val

### ISSUE THREAD

**Issue by dalewking** [Kodein-Framework/Kodein-DI#295]
So if using modules as described in the documentation, we get crashes on startup. So if I define a module like this:

    val myModule = Kodein.Module("myModule") { ... }

it crashes on startup in iOS, apparently trying to dereference null when trying to retrieve the module name.

But oddly enough it works if I turn the property instead into a function call:

    fun myModule() = Kodein.Module("myModule") { ... }

**Comment by romainbsl** [comment]
Hi, do you still have the issue? 

Just tried with DI 7.11.0 on a KMM generated project
https://github.com/romainbsl/di-issue-295

```kotlin
// Common code
class Greeting {
    private val di: DI = DI {
        importAll(straightModule)
    }

    private val platform: Platform by di.instance()
    private val url: String by di.instance(tag = "URL")

    fun greeting(): String {
        return "Hello, ${platform.get()}!\nGet in touch on $url"
    }
}

val straightModule: DI.Module = DI.Module(name = "my module") {
    bindSingleton { Platform() }
    bindConstant("URL") { "http://kodein.net/" }
}
```

```kotlin
// Android code

fun greet(): String {
    return Greeting().greeting()
}

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val tv: TextView = findViewById(R.id.text_view)
        tv.text = greet()
    }

}
```

```swift
// iOS code
struct ContentView: View {
	let greet = Greeting().greeting()

	var body: some View {
		Text(greet)
	}
}
```

No crash here.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/10594945/154970146-e58ee8d8-e81a-4f53-8a90-f85c4706e806.png">

I close the issue. Do not hesitate to re-open with some context.
