### ISSUE TITLE
Support for allInstances etc. in JavaScript?

### ISSUE THREAD

**Issue by pusolito** [Kodein-Framework/Kodein-DI#297]
Are there plans to support [allInstances](https://kodein.org/Kodein-DI/?6.5/core#_all_matches_2) in JavaScript?

```kotlin
val instances: List<Foo> = dkodein.allInstances() // not available in JS
```

If not, what are the limitations w/ Kotlin JS that prevent it?  Also, is there a good recommended work-around to get similar functionality by using the container directly?

**Comment by romainbsl** [comment]
Already answered on Slack https://kotlinlang.slack.com/archives/C0BLU9K96/p1586579782008600
> Salomon BRYS
Reflection.
In JS, there is no way to get the super class of a given class.
So, no ><.
