### ISSUE TITLE
Getting "Not enough information to infer variable type T" from instance after update

### ISSUE THREAD

**Issue by danielgomezrico** [Kodein-Framework/Kodein-DI#299]
Versions:
- kotlin_version = '1.3.71' and `1.3.72`.
- kodein = "6.5.4" and `6.5.5`.

Im getting this "error":

![image](https://user-images.githubusercontent.com/76348/79691198-bb88ea80-8223-11ea-8b1b-c90152c4bac3.png)

But the code compiles and runs fine.

**Comment by ArtRoman** [comment]
Seems to be just issue of new kotlin plugin code analysis. 
Testing with stable Android Studio 3.6.2 and 3.6.3, kotlin 1.3.71 and 1.3.72, kodein 6.5.4 and 6.5.5, kotlin plugin "1.3.71-release-Studio3.6-1" — no issues! 
Got this error after updating plugin to version "1.3.72-release-Studio3.6-1".

**Comment by romainbsl** [comment]
Yes its a Kotlin code analysis bug, you can find the relative issue here https://youtrack.jetbrains.com/issue/KT-38259
