### ISSUE TITLE
DOCUMENTATIONS ARE OUT DATED !

### ISSUE THREAD

**Issue by saidooubella** [Kodein-Framework/Kodein-DI#300]
How we can use a lib **features** either New or Old without explaining them in the **DOCS** !
You've a very **Good** library but the Docs are **poor** !

**Comment by romainbsl** [comment]
That being said.
What are your pain points? How can we help?

> PS: We are working hard on our libraries, and documentation should evolve with them.

**Comment by saidooubella** [comment]
I am new in dependency injection.
I did a search of the best and the easiest DI frameworks and I liked Kodein the problem is the documentation are out dated to learn from and there's no rich blog posts to learn from too !

**Comment by romainbsl** [comment]
This might be resolved on the mid-term. don't hesitate to raise issues or asking questions on our [slack channel](https://kotlinlang.slack.com/archives/C0BLU9K96) if you need help.
