### ISSUE TITLE
Android Scoped Multiton

### ISSUE THREAD

**Issue by backpapp** [Kodein-Framework/Kodein-DI#303]
Hi,

I've been looking for a solution for 2 days and been through the documentation all over again.

I'm getting a bundle on fragment B.

I need to pass these arguments to a multiton (which I believe to be a singleton with parameters).

    class FragmentB : Fragment, KodeinAware {

       override val kodeinContext = kcontext<Fragment>(this)
       override val kodein: Kodein = Kodein.lazy {
          extend(closestKodein())
          import(myModule)
       }

       private lateinit var navArgs: MyNavArgs
       private val viewModel: MyViewModel by kodein.instance(arg = navArgs)

       override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
         super.onViewCreated(view, savedInstanceState)
         arguments?.let {
             navArgs = MyNavArgs.fromBundle(it)
         }
       }
    }

    val myModule = Kodein.Module("") { 
    bind<MyViewModel>() with scoped<BaseFragment>(AndroidLifecycleScope).multiton { navArgs: MyNavArgs ->
        ViewModelProvider(
            context,
            MyViewModelFactory(
                navArgs
            )
        ).get(
            MyViewModel::class.java
        )
    }
    
But I'm getting 
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property navArgs has not been initialized

I thought the MyViewModel initialization was lazy, but it actually crashes during the attributes initialization.

Is there a solution to actually lazy initialize a scoped singleton with parameters ?

Cheers

**Comment by romainbsl** [comment]
Hi, 

This is a Kotlin behavior, even if kodein-DI container is lazy (evaluate at retrieval), 
your fragment will evaluate your ViewModel at initialization phase, with:
`private val viewModel: MyViewModel by kodein.instance(arg = navArgs)`

You should either evaluate your ViewModel later or in a lazy block as well.

**Comment by backpapp** [comment]
Hi,

Thanks for helping.
I'm still having difficulties understanding how to do this. Although I understand the concept, I have no idea how to write it.

`  private val viewModel: ThingsToDoDetailsViewModel by lazy {
        kodein.instance(arg = navArgs)
    } `

wouldn't compile

**Comment by romainbsl** [comment]
Then, you should avoid using `lateinit var` in this case.
May I suggest to use a lazy initializer for your **argument** retrieval:

```kotlin
private val navArgs: MyNavArgs by lazy {
    arguments?.let { MyNavArgs.fromBundle(it) }
}
```
Thus you won't need to use lazy delegate for kodein
```kotlin
private val viewModel: MyViewModel by instance(arg = navArgs)
```

**Comment by backpapp** [comment]
`arguments` does not exist during the initialization fragment. 

Making it `lateinit` brings us back to thie initial issue.

**Comment by romainbsl** [comment]
Yep, but as used in a lazy block it will be used when `viewModel` will be called, thus after fragment init

**Comment by backpapp** [comment]
I'm probably confused here. This is what I did :
```
    private val navArgs: MyNavArgs by lazy {
        arguments?.let {MyNavArgs.fromBundle(it) }!!
    }
    private val viewModel: MyViewModel by instance(arg = navArgs)
```

But since viewModel is evaluated at initialization phase, so navArgs is. `arguments` being null at this point, this seems not to be working.

Thanks for your patience.

**Comment by romainbsl** [comment]
This should work.

However, you could also use a currying factory of your view model like 
`val vm: () -> MyViewModel = { di.direct.instance(arg = navArgs) }`
using it with 
`vm()`

Hope this helps
