### ISSUE TITLE
Not able to implement DIAware an android application class

### ISSUE THREAD

**Issue by Ni3verma** [Kodein-Framework/Kodein-DI#304]
As per the documentation here : https://kodein.org/Kodein-DI/index.html?latest/android

I added **implementation "org.kodein.di:kodein-di-framework-android-x:7.0.0"** in my build.gradle (app)
I am targeting jdk version = 1.8
my kotlin version = 1.3.72
project is synced successfully.

Now I am not able to Declare the dependency bindings in the Android Application class.

my code :
class MainApplication : Application(), DIAware  {
     ....
}

Error:unresolved reference DIAware

**Comment by romainbsl** [comment]
Hello, 

Sorry for the issue, the version *7.0* is not out yet... It might be very soon!

However, its in beta and can be used with the specific repository `https://dl.bintray.com/kodein-framework/kodein-dev` in your gradle script and using the version `7.0.0-dev-56`.

Let me now if you still have some issues.

**Comment by Ni3verma** [comment]
Hi,
Thanks for the quick reply. Which is the last stable version that I can use?

**Comment by romainbsl** [comment]
The last version is `6.5.5`, but I highly recommend to use the `7.0.0` dev channel as there are some heavy changes (breaking ones...).

`7.0.0` stable version will be released in few days, so don't worry about stability ;)

**Comment by Ni3verma** [comment]
Sure, In that case I will use 7.0.0
I have two questions
1. I have noticed that now android [documentation ](https://kodein.org/Kodein-DI/index.html?latest/android) refers to version `6.5.0`. where can I find documentation of `7.0.0`?
2. I need help with how to use dev channel in android gradle? I changed `7.0.0` to `7.0.0-dev-56` like you mentioned but I got following error in gradle sync step
**ERROR: Failed to resolve: org.kodein.di:kodein-di-framework-android-x:7.0.0-dev-56**
I think I also have to mention `https://dl.bintray.com/kodein-framework/kodein-dev` in some place but I am not sure where.

Thanks for all your help

**Comment by romainbsl** [comment]
1. new documentation can be found at https://kodein.org/Kodein-DI/index.html?7.0/android
2. you need to add `https://dl.bintray.com/kodein-framework/kodein-dev` in the repository block of your gradle script https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_multiple_repositories

**Comment by Ni3verma** [comment]
Hi, Thanks for the documentation link however I am not able to solve the gradle sync error.
This is what I have done :
In **build.gradle (app)**, I have added these two dependencies:
```
implementation "org.kodein.di:kodein-di-android:$kodein_version"
implementation "org.kodein.di:kodein-di-framework-android-x:$kodein_version"
```
In **build.gradle (project)**, I added the url in buildscript (followed the link you send)

```
ext{
   // other versions
   kodein_version='7.0.0-dev-56'
}
buildscript {
    repositories {
//        TODO: remove once stable version is released
        maven {
            url "https://dl.bintray.com/kodein-framework/kodein-dev"
        }
        google()
        jcenter()

    }
}
```

**Error on gradle sync**
ERROR: Failed to resolve: org.kodein.di:kodein-di-framework-android-x:7.0.0-dev-56
Affected Modules: app

**Comment by Ni3verma** [comment]
If I add url in allprojects section then gradle sync throws no error. Here's the build.gradle (project) file
```
// other content
allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url "https://dl.bintray.com/kodein-framework/kodein-dev"
        }
    }
}
```
I hope this is the right way, correct me If I'm wrong.

However still I'm getting error on adding `kodein-di-android` dependency
error : ERROR: Failed to resolve: org.kodein.di:kodein-di-android:7.0.0-dev-56

Further I checked kodein-dev repository. Even there I can't find `kodein-di-android`
https://dl.bintray.com/kodein-framework/kodein-dev/org/kodein/di/
here I can see two valid options : `kodein-di-androidarm32` or `kodein-di-androidarm64/`
do I have to use one of them?

**Comment by romainbsl** [comment]
there is no such thing as `kodein-di-android`

it's either:
- `kodein-di-framework-android-core`
- `kodein-di-framework-android-support`
- `kodein-di-framework-android-x`

You can go with `7.0.0-dev-62` as last update

**Comment by Ni3verma** [comment]
okay thanks for all the help :) 
closing the issue
