### ISSUE TITLE
Calling kodein {...} more than once in Ktor startup throws DuplicateApplicationFeatureException

### ISSUE THREAD

**Issue by henryjcee** [Kodein-Framework/Kodein-DI#305]
Couldn't see a an existing issue for this so thought I'd raise (although I'm still investigating). 

Currently using:
- kotlinVersion=1.3.72
- coroutineVersion=1.3.5
- ktorVersion=1.3.1
- kodeinVersion=6.5.5

I have found that calling `kodein {...}` more than once during application initialisation throws a `DuplicateApplicationFeatureException`. I'm doing this as I have a base app library that sets up some bindings, meaning that downstream users don't need to worry about manually importing a module.

The intention of the code appears to be that if the Kodein feature is already installed it should get returned instead of throwing. I will step through with a debugger this eve to figure it out but it doesn't seem to be doing what it should at the moment. I'll raise a PR if I can sort it but leaving this here for now.

**Comment by romainbsl** [comment]
Hi,

This was intentional from our side. We had the idea to be able to declare multiple Kodein-DI features, but we decided to make the declaration uniqueness explicit to avoid misuse of the feature.

However, you still can have sub container in controllers or routes.
If you do want to provide a library without letting your users importing your modules, you can provide a function to call inside the `Kodein { ... }` builder by your users.

**Comment by henryjcee** [comment]
That makes sense. Might I raise a PR to update the comment on the function from:
```
/**
 * Gets or installs a [DIFeature] feature for the this [Application] and runs a [configuration] script on it
 */
```
to 
```
/**
 * Installs a [DIFeature] feature for the this [Application] and runs a [configuration] script on it or throws [DuplicateApplicationFeatureException] if the feature has already been installed.
 */
```
?

**Comment by romainbsl** [comment]
Of course! Any contribution is welcome.

However, don't be afraid when pulling the master branch... a new version of Kodein-DI will be out in few days, and we have made some huge refactoring, thus `Kodein { }` will become `DI { }`.

more information in a coming blog post, plus you can also have a first look at the upcoming migration guide https://kodein.org/Kodein-DI/?7.0/migration-6to7
