### ISSUE TITLE
not enough information to infer type variable t

### ISSUE THREAD

**Issue by kazimdsaidul** [Kodein-Framework/Kodein-DI#306]
private val factory: HomePageFactory by instance()

Android studio show this warring message. **"not enough information to infer type variable t"**

<img width="846" alt="Screen Shot 2020-05-31 at 12 59 08 AM" src="https://user-images.githubusercontent.com/7722028/83337059-26751900-a2da-11ea-9d52-34b337dbcfd2.png">

**Comment by romainbsl** [comment]
This has already been answered here https://github.com/Kodein-Framework/Kodein-DI/issues/299
> Yes its a Kotlin code analysis bug, you can find the relative issue here https://youtrack.jetbrains.com/issue/KT-38259

You can disable it here 
<img width="1328" alt="Screenshot 2020-05-30 at 21 05 26" src="https://user-images.githubusercontent.com/10594945/83337157-6bd51e80-a2b9-11ea-87e2-93b74606b1d9.png">

**Comment by kazimdsaidul** [comment]
Thanks for sharing.

**Comment by devggaurav** [comment]
it's not an option for an android studio on ubuntu

**Comment by romainbsl** [comment]
This is enabled by default since Kotlin 1.4 so your issue seems could be different.

**Comment by harshidsinghs** [comment]
> it's not an option for an android studio on ubuntu

even on windows

**Comment by mdsardar** [comment]
What to do if the above option is unavailable in IntelliJ IDEA 2023.1.6 (Ultimate Edition) ? My screen looks as below 

<img width="1318" alt="kotlin " src="https://github.com/kosi-libs/Kodein/assets/25147319/297b5f50-c977-427b-938c-7a2078a5292f">
