### ISSUE TITLE
Kodein 7 Doesn't Protect Bound interface from R8 Dead Code Elimination

### ISSUE THREAD

**Issue by eygraber** [Kodein-Framework/Kodein-DI#309]
Our Android app is using R8 in full mode for release builds, and we've run into issues with Kodein 7, where it marks some of our interfaces as dead code, which causes a crash at runtime. There is no issue with Kodein 6.

Neither `AgeValidator` nor `AgeValidatorImpl` are referenced anywhere other than in the kodein binding.

```
interface AgeValidator {
  fun validate(age: LocalDate): Boolean
}

internal class AgeValidatorImpl : AgeValidator {
  override fun validate(age: LocalDate) = true // not the actual implementation; condensed for clarity
}

val validatorModule = DI.Module("Validators") {
  bind<AgeValidator>() with provider {
    AgeValidatorImpl()
  }
}

class MyApp : Application(), DIAware {
  override val di = DI.lazy {
    import(validatorModule)
  }
}
```

The crash at runtime is:

```
Binding bind<Any>() with ? { ? } must not override an existing binding.
```

Digging into the bytecode on Kodein 6 yields the following for `AgeValidator` and `AgeValidatorImpl`:

```
// AgeValidator
.class public interface abstract LiK0;
.super Ljava/lang/Object;
.source "AgeValidator.kt"

// AgeValidatorImpl; note that validate is not present because R8 eliminated it
.class public final LjK0;
.super Ljava/lang/Object;
.source "AgeValidator.kt"

# interfaces
.implements LiK0;


# direct methods
.method public constructor <init>()V
    .registers 1

    .line 18
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
```

For Kodein 7, AgeValidator has been completely eliminated and reduced into `Any`, so that now AgeValidatorImpl simply extends `Any`:

```
// AgeValidatorImpl
.class public final LDE1;
.super Ljava/lang/Object;
.source "AgeValidator.kt"


# direct methods
.method public constructor <init>()V
    .registers 1

    .line 18
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
```
The crash makes sense, because `AgeValidator` gets replaced with `Any` which transforms `validatorModule` into:

```
val validatorModule = DI.Module("Validators") {
  bind<Any>() with provider {
    AgeValidatorImpl()
  }
}
```
which crashes the second time this happens because we try binding `Any` twice, and don't allow overriding.

I'm not sure what changed in Kodein 7 that would cause R8 to not recognize usage of a class as a type parameter for `bind`, but something did.

**Comment by eygraber** [comment]
Attached a repro project.

The following command builds and installs the app with Kodein 6 and does not crash:

```
./gradlew :app-kodein-6:installRelease
```

The following command builds and installs the app with Kodein 7 and does crash:
```
./gradlew :app-kodein-7:installRelease
```

[kodeinissue39.zip](https://github.com/Kodein-Framework/Kodein-DI/files/4741333/kodeinissue39.zip)

**Comment by romainbsl** [comment]
Thanks a lot @eygraber for the feedback.
We are very sorry for the issues that you encountered... we will check it out as fast as possible!

**Comment by eygraber** [comment]
@romainbsl I also filed an issue with Google if you want to track that - https://issuetracker.google.com/issues/158407950

**Comment by eygraber** [comment]
The response from Google is that they have something blocking them internally from addressing this scenario.

Regardless, Kodein v6 didn't have this problem. I'm not sure what changed in v7 that prevents R8 from keeping the interface. Any ideas?

**Comment by SalomonBrys** [comment]
We have absolutely no idea what v7 does different than v6 in this regard, sorry.

This is an R8 issue, not Kodein.
In the meantine, you need to change the R8 config to explicitely keep these classes (or create an annotation for this purpose).

Sorry we can't do better.

**Comment by ArtRoman** [comment]
I have faced the same issue. We have some DI modules in project, some of them extents another using subDI. All singleton instances have their own interfaces. Decompiles injection has TypeToken with class like 
`public final class _ServiceModuleKt$$special$$inlined$subDI$1$lambda$1 extends TypeReference<IMyService>`.
Unused interfaces were removed by R8 optimization as dead code, so TypeTokens converts to `TypeReference<Object>` or even `TypeReference<?>` if using last android plugin. As a result, there was an error if two or more types were removed. @Keep annotation is not sufficient for the whole module.

Solution was to keep interfaces in proguard config for each module:
`-keep,allowobfuscation interface mypackage.services.contracts.** { *; }`.
Using **allowSilentOverride** is not sufficient if any module contains two or more removed types, and **allowOverride** for each binding is not convenient to use.

**Comment by eygraber** [comment]
I started digging into this more because it is affecting us significantly.

Changing one line fixes the problem; unfortunately it's not as simple as just changing that line:

```
public inline fun <reified T : Any> DI.Builder.bind(tag: Any? = null, overrides: Boolean? = null): DI.Builder.TypeBinder<T> = Bind(generic<T>(), tag, overrides)
```

changing the `generic<T>()` to `erased()` solves the problem:

```
public inline fun <reified T : Any> DI.Builder.bind(tag: Any? = null, overrides: Boolean? = null): DI.Builder.TypeBinder<T> = Bind(erased(), tag, overrides)
```

I will look closer at what `erased` and `generic` are doing to see if there's anything that can be changed in `generic` that would make it work with R8.

**Comment by eygraber** [comment]
It seems like the reason this is happening is because R8 doesn't see a direct path to use of `T` from `generic`. I put together a naive solution that looks like this:

```
@PublishedApi internal class JVMDelegatingClassTypeToken<T>(
  override val jvmType: Class<T>,
  private val typeToken: TypeToken<T>
) : JVMAbstractTypeToken<T>() {
  override fun simpleErasedDispString() = typeToken.simpleErasedDispString()

  override fun qualifiedErasedDispString() = typeToken.qualifiedErasedDispString()

  override fun getRaw() = typeToken.getRaw()

  override fun isGeneric() = typeToken.isGeneric()

  override fun getGenericParameters() = typeToken.getGenericParameters()

  override fun isWildcard() = typeToken.isWildcard()

  override fun getSuper() = typeToken.getSuper()
}
```

And then `generic` becomes:

```
public actual inline fun <reified T : Any> generic(): TypeToken<T> = JVMDelegatingClassTypeToken(
  jvmType = T::class.javaObjectType,
  typeToken = typeToken((object : TypeReference<T>() {}).superType) as TypeToken<T>
)
```

This seems to fix the initial issue, but at runtime it throws a `java.lang.TypeNotPresentException` in some case.

Additionally, it looks like the newer version of R8 (in 7.0.0-alpha15) causes issues with having scoped factory and factory bindings for the same type:

```
Binding bind<iG0> { ?<Fragment>().? { ? } } must not override an existing binding.
```

In that case I have:

```
bind<iG0>() with factory { context: Context -> ... }
bind<iG0>() with fragmentSingleton { ... }
bind<iG0>() with activitySingleton { ... }
```

I'll keep looking. In any case, @SalomonBrys marking these things as `@Keep` doesn't actually help in most of these cases, and even if it did, it's unfeasible to mark everything as `@Keep`; we might as well turn off obfuscation if everything that gets injected needs to be kept. I'm also not so sure that this is an R8 problem, since they're constrained by needing a way to decide to keep a type, and `generic` doesn't allow for that.

I'm going to run another test where I use `erased` for everything and see if that fixes all of the new issues.

**Comment by romainbsl** [comment]
That's a nice suggestion @eygraber, thank you. 
We have bring a solution inside Kodein-Type. 
We should build a snapshot version for Type and DI to help you test this.

On which Kotlin version do you need this ? 1.4.32 / 1.5 ?
Let me know and I will publish a test version.

**Comment by eygraber** [comment]
Thanks! Kotlin 1.5

**Comment by romainbsl** [comment]
We have published the version ´ 7.6.0-r8-fix-SNAPSHOT' available on the maven snapshot repository. (https://oss.sonatype.org/content/repositories/snapshots)

It refers to Kodein-Type version ´1.7.1-tt-as-interface-SNAPSHOT'.

**Comment by eygraber** [comment]
Looks like it's working!

The following rules need to be added to proguard though:

```
-keep, allowobfuscation, allowoptimization class org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest

-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest
```

It could be added on a project by project basis, but it would probably be easier if it was bundled with the library.

**Comment by romainbsl** [comment]
Nice. You are probably right, this might belong to the library level. But I think it could be define in the Kodein-Type.
But, we need to change the KMP configuration for that, so we need to think about it.
I created a dedicated issue for that: https://github.com/Kodein-Framework/Kodein-Type/issues/6

In the meantime, I will publish a release of Kodein-DI 7.6 with Kotlin 1.5. with this fix.

**Comment by romainbsl** [comment]
FYI Kodein-DI 7.6 is out !

**Comment by Cilestal** [comment]
How can I fix this issue with Kotlin 1.3.72 and Kodein 7.0.0?

**Comment by eygraber** [comment]
Try adding the following to your proguard file:

```
-keep, allowobfuscation, allowoptimization class org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest

-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.TypeReference
-keep, allowobfuscation, allowoptimization class * extends org.kodein.type.JVMAbstractTypeToken$Companion$WrappingTest
```

**Comment by Cilestal** [comment]
I've added the given lines to my proguard file but the app still crashes with
Binding bind <Any> () with? {? } must not override an existing binding.

**Comment by eygraber** [comment]
Could be a separate issue. Try updating to the latest version and see if that fixes it.

**Comment by romainbsl** [comment]
> Binding bind <Any> () with? {? } must not override an existing binding.

This specific error occurs when you are using modules or extending a container and you have declared the same binding in those modules/containers without specifying that you wanted to override one or another.

**Comment by Cilestal** [comment]
The error appears only when using obfuscation. Unfortunately we cannot upgrade the version of Kotlin due to project restrictions.
