### ISSUE TITLE
set binding implementation limits reuseability

### ISSUE THREAD

**Issue by encodeering** [Kodein-Framework/Kodein-DI#311]
Hey,

we are using `6.5.3` and wanted to implement some sort of conditionals by returning a `NoopBinder` in the case that the condition is false. 

```
bind<Type> ()
conditional<Type> (predicate)
```

It' currently not possible to create a new TypeBinder because `inSet` is implemented as extension function.

```
inline fun <reified T: Any> Kodein.Builder.TypeBinder<T>.inSet() = InSet(generic())
```

This leads to a class cast exception if the type doesn't match kodein default [implementation](https://github.com/Kodein-Framework/Kodein-DI/blob/0a34cd97386e789a4cc91e07bbd70b19649ecdf3/kodein-di/src/commonMain/kotlin/org/kodein/di/bindings/set.kt#L95)

We also tried to return some interfaces with a proper `inSet` definition, but it's currently also not so easy to create a `ParameterizedTypeToken` or type token in general, that would match the required key signature, resulting in a

```
Exception in thread "main" java.lang.IllegalStateException: No set binding to bind<Set<Type>>() with ? { ? 
```

Do you have any hints how to create a proper parameterized token with TT?
We've tried with the following definition 

```
bind () from setBinding<Type> ()

// key represented as -> bind<Set<out T>>() with ? { ? }


InSet (CompositeTypeToken (generic<Set<T>> (), TT (type)))

// key represented as -> bind<Set<T>>() with ? { ? }

``` 

Many thanks in advance

**Comment by romainbsl** [comment]
Hi. Kodein-DI `7.5` is out and the good news is that set bindings can now be detached from the `TypeBinder`.

example:
```kotlin
        val di = DI {
            bindSet<IPerson>()

            inSet<IPerson> { singleton { Person("Salomon") } }
            inSet<IPerson> { provider { Person("Romain") } }
        }
```

The same goes for argument set bindings. 

About the TypeToken API, this has been entirely refactored with the [Kodein-Type](https://github.com/Kodein-Framework/Kodein-Type) library. 

Let me know if you still need help.
