### ISSUE TITLE
Can not use in Kotlin 1.4 in K/N

### ISSUE THREAD

**Issue by yashims** [Kodein-Framework/Kodein-DI#312]
When update to Kotlin 1.4, and build with K/N.
Happen failure as below:

```
> Task :myLib:cinteropUICKeyChainStoreIosX64 FAILED
w: Skipping "${HOME}/.gradle/caches/modules-2/files-2.1/org.kodein.di/kodein-di-iosx64/7.0.0/ccc9ef9022eb8cf1593b92bd2c3c17bea317c157/kodein-di.klib" as it is a pre 1.4 library
e: Could not find "${HOME}/.gradle/caches/modules-2/files-2.1/org.kodein.di/kodein-di-iosx64/7.0.0/ccc9ef9022eb8cf1593b92bd2c3c17bea317c157/kodein-di.klib" in [${HOME}/project/kotlin-Denco/ios/Pods, ${HOME}/.konan/klib, ${HOME}/.konan/kotlin-native-prebuilt-macos-1.4-M2/klib/common, ${HOME}/.konan/kotlin-native-prebuilt-macos-1.4-M2/klib/platform/ios_x64].
```

Would you rebuild and distribute with Kotlin 1.4-M2?

**Comment by romainbsl** [comment]
Sorry, its impossible for use to release Kodein-DI on 1.4-M2, because of this https://youtrack.jetbrains.com/issue/KT-39807
it breaks the compiler on most of the code used by DI in our test suite.

**Comment by yashims** [comment]
Oh...
I understood it.

Thank you for respond.

**Comment by romainbsl** [comment]
Those changes have been fixed on M3, so I will certainly be able to build on top of it.
