### ISSUE TITLE
Extended DirectDI not returning same instance of singleton

### ISSUE THREAD

**Issue by charleskorn** [Kodein-Framework/Kodein-DI#317]
I have a container that I later extend with further bindings using `extend()` - something like this: 

```kt
fun main(args: Array<String>) {
    val firstContainer = DI.direct {
        bind<Thing>() with singleton { Thing() }
    }

    val firstInstance = firstContainer.instance<Thing>()

    val secondContainer = DI.direct {
        extend(firstContainer, copy = Copy.All)
    }

    val secondInstance = secondContainer.instance<Thing>()

    println("From first container: $firstInstance")
    println("From second container: $secondInstance")
}

class Thing
```

I would expect the instances of `Thing` to be the same, regardless of which container I get them from, but I get different instances from each, even if I retrieve the instance from the first container before creating the second container.

I've created a sample project at https://github.com/charleskorn/kodein-singleton-extends-issue that demonstrates the issue - the output is something like this:

```
From first container: com.charleskorn.kodeinsingletonextendsissue.Thing@2d363fb3
From second container: com.charleskorn.kodeinsingletonextendsissue.Thing@7d6f77cc
```

Am I doing something wrong or is this a bug?

**Comment by romainbsl** [comment]
Extending container doesn't mean that they share their context. It just means that they have (at least) the same set of bindings.

If you want different container to share some context, you must define a relation between them, like Parent / Child containers.

Using `subDI` can help: 
```kotlin 
fun main() {
    val firstContainer = DI {
        bind<Thing>() with singleton { Thing() }
    }

    val firstInstance = firstContainer.direct.instance<Thing>()

    val secondContainer = subDI(firstContainer) {}

    val secondInstance = secondContainer.direct.instance<Thing>()

    println("From first container: $firstInstance")
    println("From second container: $secondInstance")
}

class Thing
```

giving the output 
```
From first container: Thing@9c9dafa8
From second container: Thing@9c9dafa8
```

**Comment by charleskorn** [comment]
Thanks for the quick response @romainbsl. 

Turns out `subDI` uses `extend` internally - the problematic bit of how I was using `extend` was setting `copy = Copy.All`, which copies all the bindings across, rather than referencing the bindings from the parent container. Removing `copy = Copy.All` solved the problem for me.
