### ISSUE TITLE
BoM / Platform artifact

### ISSUE THREAD

**Issue by tobias-** [Kodein-Framework/Kodein-DI#321]
It would be nice to have a Bill of Material (Maven) and also a platform (Gradle) artifact published for easier version configuration.

syntax for dependencies would then be
```
dependencies {
    implementation(platform("org.kodein.di:kodein-di-bom:7.0.0"))
    implementation("org.kodein.di:kodein-di-generic-jvm")
    implementation("org.kodein.di:kodein-di-generic-js")
    ...
}
```

**Comment by romainbsl** [comment]
In which context would you need this ?

For Kotlin/Multiplatform projects Gradle metadata already do the job of retrieving the right dependency with the given version, depending on the targeted platform.

```kotlin
kotlin {
   jvm()
   js()
   iosX64()

    sourceSets {
        commonMain {
            dependencies {
                implementation "org.kodein.di:kodein-di:7.1.0"
            }
        }
    }
}
```

Source sets for `jvm` / `js` / `ios` will have the right implementation of kodein-di.

**Comment by tobias-** [comment]
You're right. I was doing it wrong. I'm closing this issue.
