### ISSUE TITLE
Lots of broken documentation links

### ISSUE THREAD

**Issue by dalewking** [Kodein-Framework/Kodein-DI#325]
Your documentation is pretty much inaccessible at the moment

Seeing lots of broken links.
- migration guide link from github readme
- documentation link from both github readme
- getting started from https://kodein.org/di/
- core documentation from https://kodein.org/di/

**Comment by romainbsl** [comment]
Sorry for the trouble, we are moving the documentation onto Antora, so the the link format has changed.

The new docs will be available in a couple of days!

**Comment by romainbsl** [comment]
docs are back https://kodein.org/Kodein-DI/index.html.
Sorry again.
