### ISSUE TITLE
The quickstart documentation references 7.2.0 but it doesn't seem to be available

### ISSUE THREAD

**Issue by aaronbond** [Kodein-Framework/Kodein-DI#332]
I just thought i'd point out when i click the link to the docs it brings me to a version of the documents that instructs me to install "org.kodein.di:kodein-di:7.2.0" however 7.1.0 appears to be the latest version available in jcenter.

**Comment by romainbsl** [comment]
7.2.0 is the dev (unstable) version and usually comes with a suffix at the end.
