### ISSUE TITLE
Documentation for TT static function

### ISSUE THREAD

**Issue by squeekeek** [Kodein-Framework/Kodein-DI#337]
**Problem**
For Kodein 7+, the documentation is outdated regarding the `TT()` static function.

**Details**
In this [documentation file](https://github.com/Kodein-Framework/Kodein-DI/blob/master/doc/modules/core/pages/injection-retrieval.adoc), it talks about the `TT()` static function to get a `TypeToken` instance. However, it has been deprecated in favor of the `erased()` or `erasedOf()` functions. Additionally, I think the `TypesKt` class does not exist too.

Just found out when I was upgrading my Android codebase to Kodein 7+, where I used a `ViewModelFactory` retrieving stuff from Kodein.

**Comment by romainbsl** [comment]
Thank you. It has been fixed. 

Indeed, thing have changed, type management has been moved to an external project: https://github.com/Kodein-Framework/Kodein-Type
