### ISSUE TITLE
Java Scrip IR compiler issue

### ISSUE THREAD

**Issue by mustafaozhan** [Kodein-Framework/Kodein-DI#339]
Hello 👋

I updated my multiplatform project to kotlin 1.4.10. During migration I follow
https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html

It seems the IR compiler not supported by Kodein yet
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':web:packageJson'.
> Could not resolve all dependencies for configuration ':web:npm'.
   > Could not resolve org.kodein.di:kodein-di:7.1.0.
     Required by:
         project :web > project :common
      > No matching variant of org.kodein.di:kodein-di:7.1.0 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir'
....
...
..
.
```

**Comment by romainbsl** [comment]
Hi, Kodein-DI supports IR compilation, or it should be. 
However, we have an issue with the compiler, and are waiting for the version `1.4.30` to retry. (see https://github.com/Kodein-Framework/Kodein-DI/issues/319)

**Comment by romainbsl** [comment]
As kotlin 1.4.30-M1 is out we have built Kodein-DI upon it to deliver JS-IR compatibility!

You can try it by using our dev repository (`maven(url = "https://dl.bintray.com/kodein-framework/kodein-dev")`) and using the Kodein-DI version `7.3.0-kotlin-1.4.30-M1-107`
