### ISSUE TITLE
DIViewModelFactory reifed type

### ISSUE THREAD

**Issue by WiMank** [Kodein-Framework/Kodein-DI#342]
The documentation contains a non-working example of a factory for ViewModel.

**generic(modelClass)** Cannot use 'T' as reified type parameter. Use a class instead.

```
class DIViewModelFactory(val di: DI) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T =
        di.direct.Instance(generic(modelClass))
}
```

[link docs](https://docs.kodein.org/kodein-di/7.1/framework/android.html)

**Comment by romainbsl** [comment]
Documentation has been fixed, you can use `erased(modelClass)` instead. 
But I think this might be provided by Kodein-DI directly. We'll look into it.
