### ISSUE TITLE
Get the list of all available containers

### ISSUE THREAD

**Issue by daweedm** [Kodein-Framework/Kodein-DI#344]
I'm facing an issue when trying to retrieve a specific container in an Android fragment.

AFAIK, I don't have any other tool provided by Kodein to retrieve a container in an Android Fragment other than `closestDI` which gives me a container but not the one that I want.

Is there any kind of global map or something that holds all of the available containers over which I could iterate to get a specific container ?

**Comment by daweedm** [comment]
Although I have the DI container that I need in some reference before creating the fragment, I can't pass it as an arg in the constructor because Android forbid it. The bundle way doesn't seem to be a solution neither because the DI object is not serializable.

**Comment by romainbsl** [comment]
By default, Kodein-DI doesn't use global context, thus their is no possibility to retrieve a list of containers.
However, we provide a module to manage global container https://docs.kodein.org/kodein-di/7.1/extension/configurable.html
But we do not recommand its use.

What are you trying to achieve, from where your container comes from to not be reachable with the closest pattern? 
Could using a module be a solution?

**Comment by daweedm** [comment]
Thanks for your suggestion

> What are you trying to achieve, from where your container comes from to not be reachable with the closest pattern?

I'm building a plugin system where some code is loaded dynamically based on the installed list of plugins. Therefore each plugin has its own Kodein-DI container which extends a "core" Kodein-DI container (defined in the main `Application` class). The problem I was facing was the following : the Activities and Fragments defined in each plugin could not reach the DI container of the plugin they belong to, `closestDI` was always giving me the "core" container.

> Could using a module be a solution?

Finally, I managed to solve this issue by using a custom proxy function to define my containers so I can store them in a global map (referenced in the core Kodein-DI module). Then when I need a specific container, I can retrieve it directly from the map.

```kotlin
object DIProxy {
    private val containers: MutableMap<String, DI> = mutableMapOf()
    fun bind(name: String, di: DI) = containers.put(name, di)
    fun di(name: String) = lazy { containers[name]!! }
}
```

```kotlin
fun di() = DIProxy.di(BuildConfig.LIBRARY_PACKAGE_NAME)
fun DI.bindProxy() = DIProxy.bind(BuildConfig.LIBRARY_PACKAGE_NAME, this)
```

```kotlin
// when defining a container
// (...)
override val di: DI by DI.lazy {
    extend(commonDI)
    import(...)
    di.bindProxy()
}
```

```kotlin
// retrieve a stored container
import (..).di
// (...)
override val di by di()
