### ISSUE TITLE
Remove "Available bindings for this type" logs

### ISSUE THREAD

**Issue by jeggy** [Kodein-Framework/Kodein-DI#345]
It would be great if I could disable the logging of a full list of available options when I'm doing some mistake and I have forgot to bind the dependency.

Example in a huge project this list just goes on for every single module & dependency that I have defined
![image](https://user-images.githubusercontent.com/51459/100518236-4356b000-3188-11eb-960c-28d429e9fbf5.png)

The first line is very helpful, but it get's a bit annoying to scroll all the way up to find that line.

**Comment by romainbsl** [comment]
Showing the container tree is now an option:
```kotlin
val di = DI {
    fullContainerTreeOnError = true
    // Bindings
}
```

This will be available in `7.4.0`
