### ISSUE TITLE
kodein-di-framework-ktor-server-jvm 7.2.0 is not uploaded to jcenter

### ISSUE THREAD

**Issue by NorbertSandor** [Kodein-Framework/Kodein-DI#346]
https://jcenter.bintray.com/org/kodein/di/kodein-di-framework-ktor-server-jvm/7.2.0/ does not exist.

**Comment by MateuszKrawczuk** [comment]
I have the same problem for kodein-di-framework-android-x

**Comment by romainbsl** [comment]
Hello, indeed, we had some issues on the publication of our framework extensions. You should stick to the 7.1, until we fix the CI. (Probably next week)

**Comment by romainbsl** [comment]
Frameworks are now available for '7.2', sorry for the inconvenience.
