### ISSUE TITLE
StandardScopeRegistry.clear() calls ScopeCloseable.close() methods in non-deterministic order

### ISSUE THREAD

**Issue by NorbertSandor** [Kodein-Framework/Kodein-DI#349]
It would be better to call ScopeCloseable.close() in reverse of the initialization order.

**Comment by romainbsl** [comment]
What do you mean by the *in reverse of the initialization order* ? 
We do not track init order in the DI container, neither of what we registered in the `StandardScopeRegistry`, 
it might take a specific implementation for that.

**Comment by NorbertSandor** [comment]
"it might take a specific implementation for that" - OK, thanks.
