### ISSUE TITLE
New package repository (JCenter/Bintray shutdown)

### ISSUE THREAD

**Issue by holgergp** [Kodein-Framework/Kodein-DI#354]
Hi all,

you might already be aware of this, but kodein-di is most probably affected by the recently announced JCenter/Bintray [shutdown](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), as it hosts its distributions on [bintray](https://docs.kodein.org/kodein-di/7.3/getting-started.html#_with_gradle).
To ensure availability of kodein-di a new place to distribute packages has to be found.

Kind regards

Holger

**Comment by romainbsl** [comment]
Hi,

It's surely on the top priorities we have for all of our librairies.
We should move to mavenCentral ASAP, firstly for all the existing versions, then for the next releases.

Keeping this open 'till Kodein-DI is available on mavenCentral

**Comment by holgergp** [comment]
Thanks! 👍
(And thanks for this awesome lib btw!)

**Comment by romainbsl** [comment]
Its done :-)
https://twitter.com/KodeinKoders/status/1361223727053160449

 -> https://repo1.maven.org/maven2/org/kodein/

**Comment by holgergp** [comment]
Thanks a lot!
