### ISSUE TITLE
Misleading output printing the bindings

### ISSUE THREAD

**Issue by dalewking** [Kodein-Framework/Kodein-DI#357]
Say I have this type:

```
fun interface SimpleUseCase<in P, out R> where R : Any {
    operator fun invoke(param: P): R
}
```

And I have multiple bindings on that:

     bind<SimpleUseCase<Int, String>>() with singleton { SimpleUseCase{"int = $it" } }
     bind<SimpleUseCase<String, String>>() with singleton { SimpleUseCase {"string = $it" } }

Kodein has no trouble distinguishing these by type, but if you dump the list of bindings (or get an error that causes bindings to be dumped) you will get misleading info:

        bind<SimpleUseCase<*, out String>>() with singleton { SimpleUseCase<*, out String> }
        bind<SimpleUseCase<*, out String>>() with singleton { SimpleUseCase<*, out String> }

It is showing wildcard when it is fully type safe. This misleading output made me doubt that Kodein was properly handling generic types, but testing proved it was and it is only the conversion to string at fault here.

**Comment by romainbsl** [comment]
In fact, you are right, this seems type safe, and actually on Native the output is surely:
```
SimpleUseCase<String, Int>
```

But on the JVM we get that output:
```
SimpleUseCase<*, out Int>
```
On the JVM, Kotlin transfigure `SimpleUseCase<? super String, ? extends Int>`, hence the wildcard on `? super String`, because type system don't know what `? ` would be.
