### ISSUE TITLE
Function to extract all di entities by type

### ISSUE THREAD

**Issue by mpetuska** [Kodein-Framework/Kodein-DI#361]
Started in [slack](https://kotlinlang.slack.com/archives/C0BLU9K96/p1615493023009800)

Could you provide a way to extract all DI entities (with their tags) from a DI container? This would be very useful for CLI applications, where you have some tagged processors controlled by cli flag that do same work in different context. Consider this example using kotlinx-cli:
```kotlin
val di = DI {
  bind<MavenScannerService<*>>("mavenCentral") with singleton { MavenScannerServiceImpl(...) }
  bind<MavenScannerService<*>>("jCenter") with singleton { MavenScannerServiceImpl(...) }
  bind<MavenScannerService<*>>("google") with singleton { MavenScannerServiceImpl(...) }
}

fun main(args: Array<string>) {
  val parser = ArgParser("scanner")
  val scanners: Set<Pair<String?, DIProvider<MavenScannerService<*>>>> = di.direct.allProviderBindings<MavenScannerService<*>>() // <--------------- New API, alternatives for instances and factories omitted

  val scanner by parser.argument(
    type = ArgType.Choice(scanners.mapNotNull { it.first }, { scanners.find { (tag, _) ->  it == tag } }),
    description = "Repository alias to scan for"
  )
  parser.parse(args)

  // do stuff with scanner
}

```

**Comment by romainbsl** [comment]
This can be a nice to have indeed, but regarding your use case you can do it without the `allProviderBindings` function.
What arguments do you pass to the `MavenScannerServiceImpl` constructor ?

To solve your issue you could use a [multiton](https://docs.kodein.org/kodein-di/7.4/core/bindings.html#_multiton_binding).
Giving something like:

```kotlin
MavenScannerServiceImpl(mavenHost: MavenHost)

bind<MavenHost>("mavencentral") with singleton { MavenHost(...) }
bind<MavenHost>("jcenter") with singleton { MavenHost(...) }
bind<MavenHost>("google") with singleton { MavenHost(...) }

bind<MavenScannerService<*>>() with multiton { host: String ->  
    MavenScannerServiceImpl(instance<MavenHost>(tag = host))
}
```

Then on call site you can retrieve it like:
```kotlin
val scanner: MavenScannerService by instance("jcenter") // or whatever suits your use case
```

What do you think of this ?

**Comment by mpetuska** [comment]
My use case is actually the opposite of this :D

Basically, given a type, I need a definitive list of registered bindings for it to populate CLI choice (by tags). At this stage my focus is on all registered bindings for it, rather than a specific instance.

**Comment by romainbsl** [comment]
Just came across an undocumented API in *Kodein-DI* to search bindings...

```kotlin
val di = DI {
    bind<Person>(tag = "Author") with singleton { Person("Salomon") }
    bind<Person>(tag = "Maintainer") with singleton { Person("Romain") }
}

val personBindings = di.container.tree.findAllBindings {
    +binding<Person>()
}

val personList = personBindings.map { (key, _) ->
    di.container.factory(key as DI.Key<Any, Unit, Person>, Any()).invoke(Unit)
}

println(personList) // output: [Person(name=Romain), Person(name=Salomon)]
```

`findAllBindings` DSL can take parameter to filter on `binding` / `context` / `argument` / `tag`

**Comment by mpetuska** [comment]
While this definitely solves my issue, could I ask that this issue is reopened in order to lift up those undocumented APIs into public domain?

**Comment by romainbsl** [comment]
I will think about that.
This is kind of hacking the container, I will see if we really want to document this.

If so, I will create a another issue. Thx
