### ISSUE TITLE
Extend the ktor-DI Container inside the application-scope

### ISSUE THREAD

**Issue by triplem** [Kodein-Framework/Kodein-DI#364]
This seems to be a duplicate of #305, but I do have a couple of issues with this.

Could be, that I am trying to mis-use kodein but:

I do have a config, in which I do define some security-related configuration:

```
fun Application.securityConfig() {

    di {
        bind<JwtHandler>() with singleton {
            JwtHandler(
                environment
            )
        }
    }

    install(Authentication) {
        jwt {
            val jwtHandler by di().instance<JwtHandler>()
            verifier(jwtHandler.makeJwtVerifier())
            validate { credential ->
                JWTPrincipal(credential.payload)
            }
        }
    }
}
```

If I would use the suggestion, I would have to split this config into two parts (the di-init as well as the application scope stuff). Furthermore with the above solution I would be able to put this into one if-clause, 
if I would like to use the above only if a certain parameter is set:

```
if (environment.config.propertyOrNull("jwt.enabled")?.getString()?.toBoolean() != false) {
    securityConfig()
}
```

I do have the impression, that it would be rather helpful to be able to access the DI-Feature and the underlying container directly and assign additional bindings to it.

**Comment by romainbsl** [comment]
First of all, Ktor doesn't allow to install the same feature multiple times, as it can easily lead to bad design. The Routing feature is the only exception I know of. 

Accessing the nearest DI container is possible from anywhere in your application.

```kotlin
fun Application.main() {
    di { /* your bindings */ }
}

fun Application.securityConfig() {
     val di by di() // Get the DIFeature
}
```

But, you cannot extend the main's DI container. Kodein-DI is intentionally design that way, to avoid messing around with bindings. Thus, you cannot update / override / remove bindings implicitly!

However DI extension is possible, by creating a sub container, based on the main's one.

```kotlin
fun Application.main() {
    di { /* your bindings */ }
}

fun Application.securityConfig() {
    val subDI = DI {
        extend(di())
        /* other bindings */
    }

     // Do whatever you want with subDI
}

fun Application.user() {  }
```

Note that `subDI` is scoped to the `securityConfig` module, thus it cannot be used inside the `user` module. 

If doesn't fits with your need do not hesitate to ask for help on your use case.
