### ISSUE TITLE
Backend Internal error: Exception during file facade code generation

### ISSUE THREAD

**Issue by sp0xffwork** [Kodein-Framework/Kodein-DI#365]
Kodein 7.4.0
Kotlin 1.4.31

I write in Acivity next
`override val di by di()`
and get error during building 
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during file facade code generation
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:122)
......

If i write 
`di = (applicationContext as DIAware).di`
building is good

**Comment by romainbsl** [comment]
Hi @sp0xffwork, you may have a wrong import on `di`. The `di()` function is under `org.kodein.di.android.di`, can you check that out?

**Comment by sp0xffwork** [comment]
> Hi @sp0xffwork, you may have a wrong import on `di`. The `di()` function is under `org.kodein.di.android.di`, can you check that out?

thanks man. indeed, there was no import
`import org.kodein.di.android.di
`

**Comment by romainbsl** [comment]
Yeah, but it's not the first time, thus, we might think of a way of avoiding this.
FYI there is an equivalent function named `closestDI()`.
