### ISSUE TITLE
Proguard causes java.lang.RuntimeException: Invalid TypeToken; must specify type parameters

### ISSUE THREAD

**Issue by THEAccess** [Kodein-Framework/Kodein-DI#370]
The latest Kodein-DI version will cause on Android if you are using Proguard without additional rules
```
05-28 12:34:00.588  1916  1916 E AndroidRuntime: Caused by: java.lang.RuntimeException: Invalid TypeToken; must specify type parameters
05-28 12:34:00.588  1916  1916 E AndroidRuntime:        at org.kodein.type.TypeReference.void <init>()(TypeReference.java:0)
05-28 12:34:00.588  1916  1916 E AndroidRuntime:        at io.grpc.internal.InUseStateAggregator.void $r8$init$bridge()(InUseStateAggregator.java:0)
05-28 12:34:00.588  1916  1916 E AndroidRuntime:        at [...].DependencyInjectionKt$defaultDI$1$1$invoke$$inlined$provider$1.null <init>(null)(DependencyInjectionKt.java:1)
```

To resolve the issue you need to add the following line to your  `proguard-rules.pro`: 
```
-keep class org.kodein.type.TypeReference { *; }
```
I'm not sure if the rule can be made more explicit but I think it should be included in the `consumer-rules.pro` of the android module or included in the documentation.

**Comment by romainbsl** [comment]
OH, this is kind of an issue indeed. we should include this in the library responsible for the TypeToken API.
I added an [issue](https://github.com/Kodein-Framework/Kodein-Type/issues/6) but didn't think this was such an issue, we'll make a fix ASAP.

**Comment by THEAccess** [comment]
Since it can be resolved easily by adding a line to Proguard it is not a high priority issue. But it took me at least one hour to figure it out and this can be good reference for other devs.

**Comment by romainbsl** [comment]
We will add something into the documentation for sure.
It's not critical but it was introduced by some changes into a dependency, though migration should be seem less for users.

**Comment by romainbsl** [comment]
doc has been updated https://docs.kodein.org/kodein-di/7.6/framework/android.html#_proguard_configuration
