### ISSUE TITLE
Add js support to kodein-di-framework-compose

### ISSUE THREAD

**Issue by dragossusi** [Kodein-Framework/Kodein-DI#376]
I am making an app with Compose for Android/Desktop/Web and I'm using kodein for DI, the new version added support for web, but now I can't run my project, because kodein does not have a js version.

**Comment by romainbsl** [comment]
I upgraded Kodein-DI to use the last pre-release of Compose-jb (`0.5.0-build245`) with Kotlin `1.5.10`.

You can try it from sonatype snapshot repository with the version `7.7.0-master-SNAPSHOT`.

**Comment by dragossusi** [comment]
It didn't work for me. @romainbsl 

No matching variant of org.jetbrains.compose.material:material:0.5.0-build245 was found. The consumer was configured to find a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js', attribute 'org.jetbrains.kotlin.js.compiler' with value 'ir' but:

**Comment by dragossusi** [comment]
```
org.gradle.internal.resolve.ArtifactNotFoundException: Could not find kodein-di-framework-compose-7.7.0-master-SNAPSHOT-samplessources-7.7.0-master-SNAPSHOT.jar (org.kodein.di:kodein-di-framework-compose:7.7.0-master-SNAPSHOT:20210725.113606-4).
Searched in the following locations:
    https://oss.sonatype.org/content/repositories/snapshots/org/kodein/di/kodein-di-framework-compose/7.7.0-master-SNAPSHOT/kodein-di-framework-compose-7.7.0-master-SNAPSHOT-samplessources.jar
```

**Comment by dragossusi** [comment]
DId you add js as legacy or IR to the snapshot?

**Comment by romainbsl** [comment]
Done in https://github.com/Kodein-Framework/Kodein-DI/commit/64b3391f8aefeb166340e83f5b714851542eaec9
