### ISSUE TITLE
Kotlin 1.6.10 released

### ISSUE THREAD

**Issue by slavonnet** [Kodein-Framework/Kodein-DI#389]

**Comment by romainbsl** [comment]
In the pipes... but we need JB Compose to align with 1.6.0 compiler.

**Comment by slavonnet** [comment]
In russia say "7 people will don;t wait for one (to drink vodka)". Mosе current users allready  used it without Compose part. )

**Comment by romainbsl** [comment]
I do agree, I am looking for a workaround.

**Comment by slavonnet** [comment]
https://developer.android.com/jetpack/androidx/releases/compose-compiler#1.1.0-beta04

added support kotlin 1.6

**Comment by romainbsl** [comment]
We found our way for Compose. But, there is an issue for KMP project building Android target. 
We probably need to wait Kotlin 1.6.10 for a stable release.
I could manage to build a snapshot upon 1.6 by the end of the week.

**Comment by slavonnet** [comment]
please push 1.6.10

thx

**Comment by romainbsl** [comment]
Kotlin 1.6 broke our Kotlin/Multiplatform build toolchain (thanks windows...), we need to fix this first.

**Comment by romainbsl** [comment]
7.10.0 is out with Kotlin 1.6.10.
Sorry for the delay 🙏
