### ISSUE TITLE
Issue with iOS Injection Modules

### ISSUE THREAD

**Issue by RicardoDS90** [Kodein-Framework/Kodein-DI#391]
Adding various modules which are then imported DI.MainBuilder {} seems to crash when running the iOS app.

```
DI {
   import(module)
...
}

val module = DI.Module("module_name") {
...
}
```

This seems to work on Android, but running the same code on iOS crashes.

![Screenshot 2021-11-30 at 08 22 19](https://user-images.githubusercontent.com/54929502/144030463-d6ec2e5c-fe20-497c-97fd-e4066f966f99.png)

**Comment by romainbsl** [comment]
duplicates #295
