### ISSUE TITLE
Ktor DI / Ktor 2.0 refactoring

### ISSUE THREAD

**Issue by mikedawson** [Kodein-Framework/Kodein-DI#410]
Ktor 2.0 has refactored the class names for Application, ApplicationCall, PipelineContext etc (now found in io.ktor.server) as per their [migration guide](https://ktor.io/docs/migrating-2.html). 

Unfortunately KodeIn 7.11 DI with Ktor 2.0 doesn't compile. Is this something being looked at, or something that needs a pull request?

**Comment by romainbsl** [comment]
There is a branch waiting for 2.0 release, already migrated on 2.0 BETA in https://github.com/Kodein-Framework/Kodein-DI/tree/snapshot/ktor-2-beta1, so, just need few adjustments. 
Will do ASAP

**Comment by romainbsl** [comment]
Hello, 
I would like to finish some work (#407) before releasing 8.0.0 (Ktor introduced lot of breaking changes), thus I published a SNAPSHOT version of Ktor 2.0.0 with Kodein-DI.

You can use it with le maven repository `https://s01.oss.sonatype.org/content/repositories/snapshots/` under the version `8.0.0-ktor-2-SNAPSHOT`.

**Comment by mriehl** [comment]
This is great, thanks a lot @romainbsl !
