### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by freynder** [Kodein-Framework/Kodein-DI#412]
Hi, I'm new to Kodein, experiencing some issues due to documentation inconsistencies:
- references wrong artifact ids: "kodein-conf-di" instead of "kodein-di-conf" in https://docs.kodein.org/kodein-di/7.10/extension/configurable.html
- getting started for 7.10.0 code shows KodeinAware instead of renamed DiAware

**Comment by romainbsl** [comment]
Fixed for 7.11 docs. Will be available soon. Thank you.
