### ISSUE TITLE
sugestions

### ISSUE THREAD

**Issue by salongbass** [Kodein-Framework/Kodein-DI#77]
Kodein is very sexy DI library, It will become a next spring in kotlin.
I have some sugestion:
1. More flexible type matcher, eg. C > B > A, instance&lt;A&gt; and instance&lt;B&gt; also can get the instance of C
2. Use annotation processor gernerate kodein module, less coding and less dependecy
3. Auto Set. bind same type beans more times, retrieve it as Set<Bean>. don't need bind inSet()

**Comment by SalomonBrys** [comment]
Thank you for these suggestions.

1. Can you be more specific ?
2. Not going to happen. Sorry. Kodein exists specifically as an alternative to annotation processor based DI frameworks. If you want annotation processor, use Dagger ;)
3. I understand the use case, but this is kind of complicated to do in the current implementation. I might give a try, but no promises whatsoever ;)

**Comment by SalomonBrys** [comment]
1. Implemented in [Kodein 5.0-Beta1](https://salomonbrys.github.io/Kodein/?5.0).
2. Still not going to happen.
3. Not going to happen either. It confilcts with override checks. Sorry :(

I will close this issue once the stable 5.0 will be released.

**Comment by SalomonBrys** [comment]
Kodein 5.0 stable has been released :)
