### ISSUE TITLE
Add support for testing injection.

### ISSUE THREAD

**Issue by flipper83** [Kodein-Framework/Kodein-DI#79]
Hi, I'm trying to write some espresso tests with Kotlin and using Kodein for DI. The technique I'm using is based on the replacement of production code using test doubles. 

When using Kodein from my instrumentation tests everything works like a charm. If I replace the application graph with a custom one before the test is executed and every dependency is provided before the test activity is launched everything works as expected. This is working because I can replace the application module using one created from my test. But I've found a problem when the module used is initialized from the activity and not from the application. Here you have an initialization example when running a test:

The application starts: the app module is configured and initialized.
The test starts: My test module, configured with some test doubles, is added.
The activity is initialized: The activity modules are added to the graph.

Expected result: The graph does not replace the already configured dependencies using a test double.
Actual result: If I use the "override" param I lost my test module provision because the dependency has been replaced with the new one. If I remove the "override" param the app crashes.

I'd like to propose a feature request where by configuration we could allow a silent injection that doesn't apply the override and does not throw any exception. If you are ok with this new feature I can send a pull request.

I'd really like to resolve this issue even if you think there is a better approach. We can use this issue to talk about and after that send a PR :)

I found a tricky solution that allows to me fix this problem but I adding coding in production related with the tests and this is not the best solution. 

if you like to view our approach for Java code you can read this blog post http://blog.karumi.com/world-class-testing-development-pipeline-for-android-part-4/

Thanks for your time and this awesome library!

**Comment by SalomonBrys** [comment]
I'm sorry but I fail to really understand the issue.
Are you using `Kodein.global` or passing a `Kodein` object around ?
Do you have a code example ?
I fail to understand what exactly is the issue.

**Comment by flipper83** [comment]
Sorry for the late response but I didn’t see the email notification :disappointed:

I’m working on this Kata project: [KataScreenshotKotlin](https://github.com/Karumi/KataScreenshotKotlin). Some of the code that is there is also shared in some other applications we have.

 The approach we follow for writing tests is to use Kodein to replace production code for our own mocks/test doubles in test time.

I’m using the workaround you can see here: [AcceptanceTest](https://github.com/Karumi/KataScreenshotKotlin/blob/master/app/src/androidTest/java/com/karumi/ui/view/AcceptanceTest.kt). If you take a look, you’ll realize we are creating a new module called `overrideModule` to override dependencies before the activity is created. If you take a look at this part of the code ([SuperHeroesApplication](https://github.com/Karumi/KataScreenshotKotlin/blob/master/app/src/main/java/com/karumi/SuperHeroesApplication.kt)), in the method `addModule`, we manage to override part of the dependency graph with our own test module.

We know this is not the best way to replace dependencies as we need to add explicit code in our production package in order to do so. A more clean alternative would be to remove the `overrideModule` and to be able to inject our own dependencies once the graph is created but in those cases we don’t want an exception to be thrown if a provision for that class already exists.

**Comment by bernardo-macedo** [comment]
Hello,

Is there any updates on this?

Perhaps it would help to add an example of how to override the dependency graph for test doubles in the docs.

**Comment by flipper83** [comment]
In this sample that we wrote for practice screenshot testing you can check
how we provided testing mocks using kodein.

https://github.com/Karumi/KataScreenshotKotlin/blob/master/app/src/androidTest/java/com/karumi/ui/view/MainActivityTest.kt

If @SalomonBrys likes I can write and small sample for the readme.

**Comment by SalomonBrys** [comment]
Please do ;)

**Comment by flipper83** [comment]
Ok, this weekend I will create a  Small Application that injects something in the activity and modify the value in testing time.

I can modify the demo-activity, but I need change some code and could be bad for the demo-android readability. 

I will create a module called demo-activity-test. ^_^ And you can review it and give feedback.

**Comment by flipper83** [comment]
I've created this easy sample project, it's here https://github.com/Karumi/kodein-sample-testing I don't know if you prefer to link the sample from the README.md, or include the sample in your own Repo, or I can send a PR creating a folder, or keep this Issue open, as you prefer.

**Comment by streetsofboston** [comment]
@flipper83 Not sure if that would solve your particular issue, but you can declare your own subclassed `Application` instance for running instrumentation tests. This would allow you to override or declare test-specific dependencies.

Say your Application object is of class `open class MyApplication : Application()`:
```
lateinit var AppKodein: Kodein

open open class MyApplication : Application() {
    override fun onCreate() {
        super.onCreate()

        AppKodein = Kodein { 
            import(createAppModule)
        }
    }

    fun createAppModule() : Kodein.Module {
        ...
    }
}
```

In your instrumentation tests (androidTest), you create a class call MyTestApplication:
```
class MyTestApplication: MyApplication() {
    override fun createAppModule() : Kodein.Module {
        val appModule = super.createAppModule()
        val myTestOverridesModule = Kodein.Module(allowSilentOverrides = true) {
            // Create your test-only bindings below that override the ones from 'appModule'
            ...
        }
        
        AppKodein = Kodein { 
            import(appModule)
            import(myTestOverridesModule, allowOverrides = true)
        }
    }
```

Then you create your own test-runner to make sure an instance of `MyTestApplication` is created as your Application object when running your instrumentation tests.

```
class MyTestRunner : AndroidJUnitRunner() {
    override fun newApplication(cl: ClassLoader?, className: String?, context: Context?): Application = 
            super.newApplication(cl, MyTestApplication::class.java.name, context)
}
```

And declare this in your build.gradle's `defaultConfig` clause:
`testInstrumentationRunner "com.myapp.something.MyTestRunner"`

Now your instrumentation tests will instantiate a `MyTestRunner` each time they are run, which will cause your tests to use a `MyTestApplication` instance to be created as your Application object during your test-runs. This then will allow you to override the necessary Kodein bindings (see the `myTestOverridesModule`).

**Comment by flipper83** [comment]
@streetsofboston if you check the project sample, we are doing something really close. And we add code to replace the activity scope modules as well.

**Comment by streetsofboston** [comment]
Mmmmm..... strange. If I have some time, I'll take a closer look at your project sample. 
For us, our setup works fine without the need for a special testing injection.

**Comment by streetsofboston** [comment]
@flipper83 A quick scan of your repo, I can't find where you replace your `KodeinSampleApp` with a sub-class of it when running instrumentation tests.... And I can't find code that does something like this:
```
class MyTestRunner : AndroidJUnitRunner() {
    override fun newApplication(cl: ClassLoader?, className: String?, context: Context?): Application = 
            super.newApplication(cl, TestableKodeinSampleApp::class.java.name, context)
}
```

**Comment by SalomonBrys** [comment]
Kodein has moved to the 5.x paradigm that specifically allows for activity specific Kodein.

This issue is not relevant to Kodein 5.x

**Comment by RafaO** [comment]
Hi @SalomonBrys is there any sample taking advantage of this activity specific Kodein to override the global scope bindings in a test for an activity?

I guess I should extend the activity's kodein object in a new kodein object created in the test class, but then I am not sure how to tell the activity to use this new kodein object.

Thanks in advance!
