### ISSUE TITLE
erased<MyClass<T>> does not generate star-projection for generic type

### ISSUE THREAD

**Issue by jdorleans** [Kodein-Framework/Kodein-DI#84]
I’m trying to use `erased` similar to what’s suggested in the docs:
`erased<Set<String>> will yield a TypeToken representing Set<*>.`

In my case, I’m trying to do like:
```
bind<MyClass<*>>() with multiton { p: Obj<T> -> MyClass<T>(p) }
and
kodein.with(p).Instance(erased<MyClass<T>>())
```

Basically, what I’m trying to do is to create a bind for MyClass regardless the generics T it must receive. So, I’m binding it with `bind<MyClass<*>>`. However, it seems that `erased<MyClass<T>>` generated `MyClass`instead of the star-projection `MyClass<*>` as mentioned on the docs in the case of `Set`.

Is there anything I can do to make this right?

Doc reference:
https://salomonbrys.github.io/Kodein/#erased-comp

**Comment by salongbass** [comment]
try this:
`
Bind(erased<MyClass<*>>()) with multiton { p: Obj<T> -> MyClass<T>(p) }
and
kodein.with(p).Instance(erased<MyClass<T>>())
`

**Comment by SalomonBrys** [comment]
I've looked at correcting this, but unfortunately the performance cost is way too high (multiplies the performance of the `generic` function by 4, while it is already a performance pitfall).

The easiest way is to go with erased all the way, including on binding:

```kotlin
Bind<MyClass<*>>(erased()) with multiton { p: Obj<T> -> MyClass<T>(p) }
```
and then
```kotlin
kodein.with(p).Instance(erased<MyClass<T>>())
```

**Comment by jdorleans** [comment]
Wow... gotcha! I didn't have time to try that just yet. It seems a feasible solution though. I'll report back as soon as I get my hands on this again. Thx.

**Comment by SalomonBrys** [comment]
Reopenning this as I may have found a way to fix this without a significant impact performance.

**Comment by SalomonBrys** [comment]
I think this is corrected in Kodein 5.
Feel free to reopen this if it is not.
